select 
	ed.code as domaine_code,
	ed.id as domaine_id,
	ed.nom as domaine_nom, 
	ed.campagne as domaine_campagne, 
	edi.code as dispositif_code, 
	edi.id as dispositif_id, 
	edi.type as dispositif_type, 
	es.code as sdc_code, 
	es.id as sdc_id, 
	es.nom as sdc_nom, 
	es.modalite_suivi_dephy as sdc_modalite_suivi_dephy, 
	es.code_dephy as sdc_code_dephy, 
	es.commentaire as sdc_commentaire, 
	es.validite as sdc_valide, 
	es.filiere as sdc_filiere,
	es.type_production as sdc_type_production,
	es.type_agriculture as sdc_type_agriculture,
	es.strategie_categorie as sdc_strategie_categorie,
	es.part_sau_domaine as sdc_part_sau_domaine,
	es.part_mo_domaine as sdc_part_mo_domaine,
	es.part_materiel_domaine as sdc_part_materiel_domaine,
	es.couverts_associes,
	es.ci_effet_allelo_ou_biocide,
	es.ci_attractives_pour_auxiliaires,
	es.cipan,
	es.semis_precoce,
	es.semis_tardif,
	es.exportation_menu_pailles,
	es.destruction_litiere,
	es.dose_adaptee_surf_foliaire,
	es.filet_anti_insectes,
	es.taille_organes_contamines,
	es.taille_limitant_risques_sanitaires,
	es.faible_densite,
	es.forte_densite,
	es.faible_ecartement,
	es.ajustement_fertilisation,
	es.ajustement_irrigation,
	es.desherbage_autre_forme,
	es.cultures_pieges,
	es.desherbage_meca_frequent,
	es.desherbage_meca_occasionnel,
	es.desherbage_thermique,
	es.adaptation_lutte_a_la_parcelle,
	es.optim_conditions_application,
	es.reduction_dose_autres_phyto,
	es.reduction_dose_fongi,
	es.reduction_dose_herbi,
	es.reduction_dose_insec,
	es.traitement_localise,
	es.utilisation_adjuvants,
	es.utilisation_seuils,
	es.utilisation_oad,
	es.var_competitives_adventice,
	es.var_peu_sensibles_verse,
	es.var_peu_sensibles_maladies,
	es.var_peu_sensibles_ravageurs,
	es.lutte_bio_confu_sexuelle,
	es.lutte_bio_autre,
	es.melange,
	es.gestion_residus,
	es.monoculture_rotation_courte,
	es.rotation_cultures_rustiques,
	es.rotation_diversifiee_avec_pt,
	es.rotation_diversifiee_sans_pt,
	es.rotation_diversifiee_intro_une_culture,
	es.enherbement_seme,
	es.enherbement_naturel,
	es.agroforesterie,
	es.arbres_bordure_parcelle,
	es.broyage_bordure,
	es.gestion_bordure_de_bois,
	es.haies_anciennes,
	es.haies_jeunes,
	es.bandes_enherbees,
	es.bandes_fleuries,
	es.bois_bosquet,
	es.decompactage_occasionnel,
	es.decompactage_frequent,
	es.faux_semis_ponctuels,
	es.faux_semis_intensifs,
	es.labour_occasionnel,
	es.labour_frequent,
	es.labour_systematique,
	es.semis_direct_occasionnel,
	es.semis_direct_systematique,
	es.strip_till_occasionnel,
	es.strip_till_frequent,
	es.tcs,
	es.reseaux_ir,
	es.reseaux_it,
	es.codes_convention_dephy,
	es.modes_commercialisation
from entrepot_sdc es	
left join entrepot_dispositif edi on es.dispositif_id = edi.id
left join entrepot_domaine ed on edi.domaine_id = ed.id
join entrepot_dispositif_filtres_outils_can edifoc on ed.id = edifoc.id;
