select
 	"id"::text,
	code_dephy::text as "dephyNb",
	"realized"::text,
    true as "validation",
	"sdc_id"::text,
	synthetise_id::text as "systeme_synthetise_id",
	-- entite_id,
	-- dispositif_id,
	-- domaine_id,
	-- commune_id,
    "reseaux_ir"::text,
	"reseaux_it"::text,
	"latitude"::numeric,
	"longitude"::numeric,
	codeinsee::text as "codeinsee",
	"arrondissement"::text,
	---------
	'DEPHY Ferme' as "c100_networksource",
	filiere::text as "c101_sector",
	pz0::text as "c102_pz0",
	"c103_networkYears"::text,
	new_campagne::integer as "c104_campaign_dis",
	region::text as "c105_administrativeRegion",
	ancienne_region::text as "c106_regionPre2015",
	departement::text as "c107_departement",
	bassin_viticole::text as "c108_wineBasin",
    'France' as "c109_country",
	---------
	type_agriculture::text as "c110_managementType",
	"c111_species"::text,
	"c112_variety"::text,
	"c113_grapeVar"::text,
	---------
	-- type_production,
	"c120_arboriculture_typo_sdc"::text,
	"c121_maraichage_typo_sdc"::text,
	"c122_horticulture_typo_sdc"::text,
	"c123_cult_tropicales_typo_sdc"::text,
	"c124_gcpe_typo_sdc"::text,
	---------
	-- surface_par_unite_de_travail_humain,
	-- nombre_uth_necessaires,
	type_de_travail_du_sol::text as "c201_groundWorkType",
	utili_desherbage_meca::text as "c203_mechanicalWeeding",
	nbre_de_passages_desherbage_meca::double precision as "c204_mechanicalWeedingInterventionFrequency",
	---------
	tps_travail_total as "c301_workingTime",
	tps_utilisation_materiel as "c302_mechanizationTime",
	tps_travail_manuel as "c303_labourTime",
	conso_carburant as "c304_fuelConsumption",
	---------
	ferti_n_tot as "c401_fertilizationUnityN",
	ferti_n_mineral as "c402_fertilizationMineralUnityN",
	ferti_n_organique as "c403_fertilizationOrganicUnityN",
	ferti_p2o5_tot as "c404_fertilizationUnityP",
	ferti_p2o5_mineral as "c405_fertilizationMineralUnityP",
	ferti_p2o5_organique as "c406_fertilizationOrganicUnityP",
	ferti_k2o_tot as "c407_fertilizationUnityK",
	ferti_k2o_mineral as "c408_fertilizationMineralUnityK",
	ferti_k2o_organique as "c409_fertilizationOrganicUnityK",
	---------
	pb_std_mil_avec_autoconso as "c501_grossProceeds",
	mb_std_mil_avec_autoconso as "c502_grossProfit",
	msn_reelle_avec_autoconso as "c503_semiNetMargin",
	"c504_outLabourTotalExpenses",
	co_tot_std_mil as "c505_operatingExpenses",
	-- c_main_oeuvre_tractoriste_std_mil,
	-- c_main_oeuvre_manuelle_std_mil,
	c_main_oeuvre_tot_std_mil as "c506_labourExpenses",
	cm_std_mil as "c507_mechanizationExpenses",
	md_std_mil_avec_autoconso as "c508_DirectMargin",                     -- INVISIBLE
	---------
	-- ift_cible_non_mil_chimique_tot,
	ift_cible_non_mil_chim_tot_hts as "c601_totalIFT",
	-- ift_cible_non_mil_hh,
	"c602_IFT_hh_hts",
    ift_cible_non_mil_biocontrole as "c603_biocontrolIFT",
	ift_cible_non_mil_h as "c605_herbicideIFT",
	ift_cible_non_mil_i as "c607_insecticideIFT",
	ift_cible_non_mil_f as "c608_fungicideIFT",
	-- ift_cible_non_mil_ts,
	ift_cible_non_mil_a as "c609_otherIFT",
	recours_aux_moyens_biologiques as "c610_biologicalWaysSolution",
	---------
	hri1_hts as "c633_hri1tothts",
	hri1_g1_hts as "c634_hri1g1hts",
	hri1_g2_hts as "c635_hri1g2hts",
	hri1_g3_hts as "c636_hri1g3hts",
	hri1_g4_hts as "c637_hri1g4hts",
	---------
	qsa_tot_hts as "c640_qteSubstActive",                                 -- INVISIBLE
	qsa_cmr_hts as "c641_qteSubstCMR",                                    -- INVISIBLE
	qsa_toxique_utilisateur_hts as "c642_qteSubsttoxique",                -- INVISIBLE
	qsa_glyphosate_hts as "c643_qteSubstglyphosate",                      -- INVISIBLE
	qsa_danger_environnement_hts as "c644_qteSubstdangerenvironnement",   -- INVISIBLE
	qsa_cuivre_tot_hts as "c645_qteSubstcuivre",                          -- INVISIBLE
	qsa_soufre_tot_hts as "c646_qteSubstsoufre",                          -- INVISIBLE
	---------
	-- "c701_totalIFT_evol_diff",
	-- "c702_IFT_hh_hts_evol_diff",
	-- "c703_biocontrolIFT_evol_diff",
	-- "c705_herbicideIFT_evol_diff",
	-- "c707_insecticideIFT_evol_diff",
	-- "c708_fungicideIFT_evol_diff",
	-- "c709_otherIFT_evol_diff",
	-- "c710_biologicalWaysSolution_evol_diff",
	---------
	"c701_totalIFT_evol_ratio",
	"c702_IFT_hh_hts_evol_ratio",
	"c703_biocontrolIFT_evol_ratio",
	"c705_herbicideIFT_evol_ratio",
	"c707_insecticideIFT_evol_ratio",
	"c708_fungicideIFT_evol_ratio",
	"c709_otherIFT_evol_ratio",
	"c710_biologicalWaysSolution_evol_ratio",
	-- c640_stdTotalIFT
	------- POUR IPM
    'DEPHY Ferme' as "c1001_networksource",
    null::double precision as "c9303_labourTime",
    null::double precision as "c9502_grossProfit",
    null::double precision as "c9503_semiNetMargin",
    null::double precision as "c9506_labourExpenses",
    null::double precision as "c9633_hri1tothts_ipm",
    null::double precision as "c9634_hri1g1hts_ipm" ,
    null::double precision as "c9635_hri1g2hts_ipm",
    null::double precision as "c9636_hri1g3hts_ipm",
    null::double precision as "c9637_hri1g4hts_ipm"
from entrepot_main_dephygraph
where entrepot_main_dephygraph.filiere != 'Cultures tropicales'
UNION ALL
SELECT
	cast(uuid_generate_v4() as text) as "id",
	"dephyNb"::text,
	null::text as "realized",
	true as "validation",
	"sdc_id"::text,
	"systeme_synthetise_id"::text,
	null::text as "reseaux_ir",
	null::text as "reseaux_it",
	"latitude"::numeric,
	"longitude"::numeric,
	null::text as "codeinsee",
	c107_departement::text as "arrondissement",
	--------
	'DEPHY Ferme' as "c100_networksource",
	"c101_sector"::text,
	"c102_pz0"::text,
	"c103_networkYears"::text,
	"c104_campaign_dis"::integer,
	"c105_administrativeRegion"::text,
	"c106_regionPre2015"::text,
	"c107_departement"::text,
	null::text as "c108_wineBasin",
	'France' as "c109_country",
	---------
	"c110_managementType"::text,
	"c111_species"::text,
	"c112_variety"::text,
	null::text as "c113_grapeVar",
	---------
	"c120_arboriculture_typo_sdc"::text,
	"c121_maraichage_typo_sdc"::text,
	"c122_horticulture_typo_sdc"::text,
	"c123_cult_tropicales_typo_sdc"::text,
	"c124_gcpe_typo_sdc"::text,
	---------
	"c201_groundWorkType"::text,
	"c203_mechanicalWeeding"::text,
	"c204_mechanicalWeedingInterventionFrequency",
	---------
	"c301_workingTime",
	"c302_mechanizationTime",
	"c303_labourTime",
	"c304_fuelConsumption",
	---------
	"c401_fertilizationUnityN",
	"c402_fertilizationMineralUnityN",
	"c403_fertilizationOrganicUnityN",
	"c404_fertilizationUnityP",
	"c405_fertilizationMineralUnityP",
	"c406_fertilizationOrganicUnityP",
	"c407_fertilizationUnityK",
	"c408_fertilizationMineralUnityK",
	"c409_fertilizationOrganicUnityK",
	---------
	"c501_grossProceeds",
	"c502_grossProfit",
	"c503_semiNetMargin",
	"c504_outLabourTotalExpenses",
	"c505_operatingExpenses",
	"c506_labourExpenses",
	"c507_mechanizationExpenses",
	null::double precision as "c508_DirectMargin",
	---------
	"c601_totalIFT",
	"c602_IFT_hh_hts",
	"c603_biocontrolIFT",
	"c605_herbicideIFT",
	"c607_insecticideIFT",
	"c608_fungicideIFT",
	"c609_otherIFT",
	"c610_biologicalWaysSolution",
	---------
	null::double precision as "c633_hri1tothts",
	null::double precision as "c634_hri1g1hts",
	null::double precision as "c635_hri1g2hts",
	null::double precision as "c636_hri1g3hts",
	null::double precision as "c637_hri1g4hts",
	---------
	null::double precision as "c640_qteSubstActive",
	null::double precision as "c641_qteSubstCMR",
	null::double precision as "c642_qteSubsttoxique",
	null::double precision as "c643_qteSubstglyphosate",
	null::double precision as "c644_qteSubstdangerenvironnement",
	null::double precision as "c645_qteSubstcuivre",
	null::double precision as "c646_qteSubstsoufre",
	---------
	"c701_totalIFT_evol_ratio",
	"c702_IFT_hh_hts_evol_ratio",
	"c703_biocontrolIFT_evol_ratio",
	"c705_herbicideIFT_evol_ratio",
	"c707_insecticideIFT_evol_ratio",
	"c708_fungicideIFT_evol_ratio",
	"c709_otherIFT_evol_ratio",
	"c710_biologicalWaysSolution_evol_ratio",
	------- POUR IPM
	'DEPHY Ferme' as "c1001_networksource",
	null::double precision as "c9303_labourTime",
	null::double precision as "c9502_grossProfit",
	null::double precision as "c9503_semiNetMargin",
	null::double precision as "c9506_labourExpenses",
	null::double precision as "c9633_hri1tothts_ipm",
	null::double precision as "c9634_hri1g1hts_ipm",
	null::double precision as "c9635_hri1g2hts_ipm",
	null::double precision as "c9636_hri1g3hts_ipm",
	null::double precision as "c9637_hri1g4hts_ipm"
from entrepot_data_culture_trop_for_dephygraph
UNION ALL
SELECT
	cast(uuid_generate_v4() as text) as "id", 
	"dephyNb"::text,
	"realized"::text,
	true as "validation",
	"sdc_id"::text,
	"systeme_synthetise_id"::text,
	null::text as "reseaux_ir", 
	null::text as "reseaux_it",
	"latitude"::numeric,
	"longitude"::numeric,
	null::text as "codeinsee", 
	"arrondissement"::text,
	---------
	"c100_networksource"::text,
	"c101_sector"::text,
	"c102_pz0"::text,
	"c103_networkYears"::text,
	"c104_campaign_dis"::integer,
	"c105_administrativeRegion"::text,
	"c106_regionPre2015"::text,
	"c107_departement"::text,
	"c108_wineBasin"::text,
	"c109_country"::text,
	---------
	"c110_managementType"::text,
	"c111_species"::text,
	"c112_variety"::text,
	"c113_grapeVar"::text,
	---------
	"c120_arboriculture_typo_sdc"::text,
	"c121_maraichage_typo_sdc"::text,
	"c122_horticulture_typo_sdc"::text,
	"c123_cult_tropicales_typo_sdc"::text,
	"c124_gcpe_typo_sdc"::text,
	---------
	"c201_groundWorkType"::text,
	"c203_mechanicalWeeding"::text,
	"c204_mechanicalWeedingInterventionFrequency",
	---------
	"c301_workingTime",
	"c302_mechanizationTime",
	"c303_labourTime",
	"c304_fuelConsumption",
	---------
	"c401_fertilizationUnityN",
	"c402_fertilizationMineralUnityN",
	"c403_fertilizationOrganicUnityN",
	"c404_fertilizationUnityP",
	"c405_fertilizationMineralUnityP",
	"c406_fertilizationOrganicUnityP",
	"c407_fertilizationUnityK",
	"c408_fertilizationMineralUnityK",
	"c409_fertilizationOrganicUnityK",
	---------
	"c501_grossProceeds",
	"c502_grossProfit",
	"c503_semiNetMargin",
	"c504_outLabourTotalExpenses",
	"c505_operatingExpenses",
	"c506_labourExpenses",
	"c507_mechanizationExpenses",
	"c508_DirectMargin",
	---------
	"c601_totalIFT",
	"c602_IFT_hh_hts",
	"c603_biocontrolIFT",
	"c605_herbicideIFT",
	"c607_insecticideIFT",
	"c608_fungicideIFT",
	"c609_otherIFT",
	"c610_biologicalWaysSolution",
	---------
	"c633_hri1tothts",
	"c634_hri1g1hts",
	"c635_hri1g2hts",
	"c636_hri1g3hts",
	"c637_hri1g4hts",
	---------
	"c640_qteSubstActive",
	"c641_qteSubstCMR",
	"c642_qteSubsttoxique",
	"c643_qteSubstglyphosate",
	"c644_qteSubstdangerenvironnement",
	"c645_qteSubstcuivre",
	"c646_qteSubstsoufre",
	---------
	"c701_totalIFT_evol_ratio",
	"c702_IFT_hh_hts_evol_ratio",
	"c703_biocontrolIFT_evol_ratio",
	"c705_herbicideIFT_evol_ratio",
	"c707_insecticideIFT_evol_ratio",
	"c708_fungicideIFT_evol_ratio",
	"c709_otherIFT_evol_ratio",
	"c710_biologicalWaysSolution_evol_ratio",
	--------- POUR IPM
	"c1001_networksource",
	"c9303_labourTime",
	"c9502_grossProfit",
	"c9503_semiNetMargin",
	"c9506_labourExpenses",
	"c9633_hri1tothts_ipm",
	"c9634_hri1g1hts_ipm",
	"c9635_hri1g2hts_ipm",
	"c9636_hri1g3hts_ipm",
	"c9637_hri1g4hts_ipm"
from entrepot_data_ipmgraph_for_dephygraph;