select
 	"id",
	code_dephy as "dephyNb",
	"realized",
    true as "validation",
	"sdc_id",
	synthetise_id as "systeme_synthetise_id",
	-- entite_id,
	-- dispositif_id,
	-- domaine_id,
	-- commune_id,
    "reseaux_ir",
	"reseaux_it",
	---------
	new_campagne as "c104_campaign_dis",
	pz0 as "c102_pz0",
	"c103_networkYears",
	---------
	"codeinsee",
	departement as "c107_departement",
	region as "c105_administrativeRegion",
	bassin_viticole as "c108_wineBasin",
	ancienne_region as "c106_regionPre2015",
    'France' as "c109_country",
	"latitude",
	"longitude",
	"arrondissement",
	---------
    'DEPHY Ferme' as "c100_networksource",
	filiere as "c101_sector",
	-- type_production,
	type_agriculture as "c110_managementType",
	---------
	"c111_species",
	"c112_variety",
	"c113_grapeVar",
	---------
	"c120_arboriculture_typo_sdc",
	"c121_maraichage_typo_sdc",
	"c122_horticulture_typo_sdc",
	"c123_cult_tropicales_typo_sdc",
	"c124_gcpe_typo_sdc",
	---------
	-- ift_cible_non_mil_chimique_tot,
	ift_cible_non_mil_chim_tot_hts as "c601_totalIFT",
	-- ift_cible_non_mil_hh,
	"c602_IFT_hh_hts",
    ift_cible_non_mil_biocontrole as "c603_biocontrolIFT",
	ift_cible_non_mil_h as "c605_herbicideIFT",
	ift_cible_non_mil_i as "c607_insecticideIFT",
	ift_cible_non_mil_f as "c608_fungicideIFT",
	-- ift_cible_non_mil_ts,
	ift_cible_non_mil_a as "c609_otherIFT",
	recours_aux_moyens_biologiques as "c610_biologicalWaysSolution",
	---------
	hri1_hts as "c633_hri1tothts",
	hri1_g1_hts as "c634_hri1g1hts",
	hri1_g2_hts as "c635_hri1g2hts",
	hri1_g3_hts as "c636_hri1g3hts",
	hri1_g4_hts as "c637_hri1g4hts",
	---------
	qsa_tot_hts as "c640_qteSubstActive",                                 -- INVISIBLE
	qsa_danger_environnement_hts as "c644_qteSubstdangerenvironnement",   -- INVISIBLE
	qsa_toxique_utilisateur_hts as "c642_qteSubsttoxique",                -- INVISIBLE
	qsa_cmr_hts as "c641_qteSubstCMR",                                    -- INVISIBLE
	qsa_glyphosate_hts as "c643_qteSubstglyphosate",                      -- INVISIBLE
	qsa_cuivre_tot_hts as "c645_qteSubstcuivre",                          -- INVISIBLE
	qsa_soufre_tot_hts as "c646_qteSubstsoufre",                          -- INVISIBLE
	---------
	ferti_n_tot as "c401_fertilizationUnityN",
	ferti_n_mineral as "c402_fertilizationMineralUnityN",
	ferti_n_organique as "c403_fertilizationOrganicUnityN",
	ferti_p2o5_tot as "c404_fertilizationUnityP",
	ferti_p2o5_mineral as "c405_fertilizationMineralUnityP",
	ferti_p2o5_organique as "c406_fertilizationOrganicUnityP",
	ferti_k2o_tot as "c407_fertilizationUnityK",
	ferti_k2o_mineral as "c408_fertilizationMineralUnityK",
	ferti_k2o_organique as "c409_fertilizationOrganicUnityK",
	---------
	pb_std_mil_avec_autoconso as "c501_grossProceeds",
	mb_std_mil_avec_autoconso as "c502_grossProfit",
	msn_reelle_avec_autoconso as "c503_semiNetMargin",
	md_std_mil_avec_autoconso as "c508_DirectMargin",                     -- INVISIBLE
	---------
	"c504_outLabourTotalExpenses",
	co_tot_std_mil as "c505_operatingExpenses",
	cm_std_mil as "c507_mechanizationExpenses",
	c_main_oeuvre_tot_std_mil as "c506_labourExpenses",
	-- c_main_oeuvre_tractoriste_std_mil,
	-- c_main_oeuvre_manuelle_std_mil,
	conso_carburant as "c304_fuelConsumption",
	---------
	tps_utilisation_materiel as "c302_mechanizationTime",
	tps_travail_manuel as "c303_labourTime",
	tps_travail_total as "c301_workingTime",
	---------
	-- surface_par_unite_de_travail_humain,
	-- nombre_uth_necessaires,
	nbre_de_passages_desherbage_meca as "c204_mechanicalWeedingInterventionFrequency",
	utili_desherbage_meca as "c203_mechanicalWeeding",
	type_de_travail_du_sol as "c201_groundWorkType",
	---------
	-- "c701_totalIFT_evol_diff",
	-- "c702_IFT_hh_hts_evol_diff",
	-- "c703_biocontrolIFT_evol_diff",
	-- "c705_herbicideIFT_evol_diff",
	-- "c707_insecticideIFT_evol_diff",
	-- "c708_fungicideIFT_evol_diff",
	-- "c709_otherIFT_evol_diff",
	-- "c710_biologicalWaysSolution_evol_diff",
	---------
	"c701_totalIFT_evol_ratio",
	"c702_IFT_hh_hts_evol_ratio",
	"c703_biocontrolIFT_evol_ratio",
	"c705_herbicideIFT_evol_ratio",
	"c707_insecticideIFT_evol_ratio",
	"c708_fungicideIFT_evol_ratio",
	"c709_otherIFT_evol_ratio",
	"c710_biologicalWaysSolution_evol_ratio",
	-- c640_stdTotalIFT
	---------
    -- pour IPM
    'DEPHY Ferme' as "c1001_networksource",
    null as "c9303_labourTime",
    null as "c9502_grossProfit",
    null as "c9503_semiNetMargin",
    null as "c9506_labourExpenses",
    null as "c9633_hri1tothts_ipm",
    null as "c9634_hri1g1hts_ipm" ,
    null as "c9635_hri1g2hts_ipm",
    null as "c9636_hri1g3hts_ipm",
    null as "c9637_hri1g4hts_ipm"
from entrepot_main_dephygraph

UNION

SELECT
	uuid_generate_v4() as "id"
	"dephyNb",
	"latitude",
	"longitude",
	"realized",
	"sdc_id",
	"systeme_synthetise_id",
	true as "validation",
	null as "codeinsee",
	c107_departement as "arrondissement",
	null as "reseaux_ir",
	null as "reseaux_it"
	'DEPHY Ferme' as "c100_networksource",
	"c101_sector",
	"c102_pz0",
	"c103_networkYears",
	"c104_campaign_dis",
	"c105_administrativeRegion",
	"c106_regionPre2015",
	"c107_departement",
	null as "c108_wineBasin",
	'France' as "c109_country",
	"c110_managementType",
	"c111_species",
	"c112_variety",
	null as "c113_grapeVar",
	"c120_arboriculture_typo_sdc",
	"c121_maraichage_typo_sdc",
	"c122_horticulture_typo_sdc",
	"c123_cult_tropicales_typo_sdc",
	"c124_gcpe_typo_sdc",
	"c201_groundWorkType",
	"c203_mechanicalWeeding",
	"c204_mechanicalWeedingInterventionFrequency",
	"c301_workingTime",
	"c302_mechanizationTime",
	"c303_labourTime",
	"c304_fuelConsumption",
	"c401_fertilizationUnityN",
	"c402_fertilizationMineralUnityN",
	"c403_fertilizationOrganicUnityN",
	"c404_fertilizationUnityP",
	"c405_fertilizationMineralUnityP",
	"c406_fertilizationOrganicUnityP",
	"c407_fertilizationUnityK",
	"c408_fertilizationMineralUnityK",
	"c409_fertilizationOrganicUnityK",
	"c501_grossProceeds",
	"c502_grossProfit",
	"c503_semiNetMargin",
	"c504_outLabourTotalExpenses",
	"c505_operatingExpenses",
	"c506_labourExpenses",
	"c507_mechanizationExpenses",
	null as "c508_DirectMargin",
	"c601_totalIFT",
	"c602_IFT_hh_hts",
	"c603_biocontrolIFT",
	"c605_herbicideIFT",
	"c607_insecticideIFT",
	"c608_fungicideIFT",
	"c609_otherIFT",
	"c610_biologicalWaysSolution",
	null as "c633_hri1tothts",
	null as "c634_hri1g1hts",
	null as "c635_hri1g2hts",
	null as "c636_hri1g3hts",
	null as "c637_hri1g4hts",
	null as "c640_qteSubstActive",
	null as "c641_qteSubstCMR",
	null as "c642_qteSubsttoxique",
	null as "c643_qteSubstglyphosate",
	null as "c644_qteSubstdangerenvironnement",
	null as "c645_qteSubstcuivre",
	null as "c646_qteSubstsoufre",
	"c701_totalIFT_evol_ratio",
	"c702_IFT_hh_hts_evol_ratio",
	"c703_biocontrolIFT_evol_ratio",
	"c705_herbicideIFT_evol_ratio",
	"c707_insecticideIFT_evol_ratio",
	"c708_fungicideIFT_evol_ratio",
	"c709_otherIFT_evol_ratio",
	"c710_biologicalWaysSolution_evol_ratio",
	------- POUR IPM
	null as "c1001_networksource",
	null as "c9303_labourTime",
	null as "c9502_grossProfit",
	null as "c9503_semiNetMargin",
	null as "c9506_labourExpenses",
	null as "c9633_hri1tothts_ipm",
	null as "c9634_hri1g1hts_ipm",
	null as "c9635_hri1g2hts_ipm",
	null as "c9636_hri1g3hts_ipm",
	null as "c9637_hri1g4hts_ipm",
from entrepot_data_culture_trop_for_dephygraph

UNION

SELECT
	null as "codeinsee", 
	uuid_generate_v4() as "id", 
	null as "reseaux_ir", 
	null as "reseaux_it",
	"realized",
	"dephyNb",
	"latitude",
	"longitude",
	"arrondissement",
	"validation",
	"sdc_id",
	"systeme_synthetise_id",
	"c101_sector",
	"c102_pz0",
	"c103_networkYears",
	"c104_campaign_dis",
	"c105_administrativeRegion",
	"c106_regionPre2015",
	"c107_departement",
	"c108_wineBasin",
	"c110_managementType",
	"c111_species",
	"c112_variety",
	"c113_grapeVar",
	"c120_arboriculture_typo_sdc",
	"c121_maraichage_typo_sdc",
	"c122_horticulture_typo_sdc",
	"c123_cult_tropicales_typo_sdc",
	"c124_gcpe_typo_sdc",
	"c201_groundWorkType",
	"c203_mechanicalWeeding",
	"c204_mechanicalWeedingInterventionFrequency",
	"c301_workingTime",
	"c302_mechanizationTime",
	"c303_labourTime",
	"c304_fuelConsumption",
	"c401_fertilizationUnityN",
	"c402_fertilizationMineralUnityN",
	"c403_fertilizationOrganicUnityN",
	"c404_fertilizationUnityP",
	"c405_fertilizationMineralUnityP",
	"c406_fertilizationOrganicUnityP",
	"c407_fertilizationUnityK",
	"c408_fertilizationMineralUnityK",
	"c409_fertilizationOrganicUnityK",
	"c501_grossProceeds",
	"c502_grossProfit",
	"c503_semiNetMargin",
	"c504_outLabourTotalExpenses",
	"c505_operatingExpenses",
	"c506_labourExpenses",
	"c507_mechanizationExpenses",
	"c508_DirectMargin",
	"c601_totalIFT",
	"c602_IFT_hh_hts",
	"c603_biocontrolIFT",
	"c605_herbicideIFT",
	"c607_insecticideIFT",
	"c608_fungicideIFT",
	"c609_otherIFT",
	"c610_biologicalWaysSolution",
	"c701_totalIFT_evol_ratio",
	"c702_IFT_hh_hts_evol_ratio",
	"c703_biocontrolIFT_evol_ratio",
	"c705_herbicideIFT_evol_ratio",
	"c707_insecticideIFT_evol_ratio",
	"c708_fungicideIFT_evol_ratio",
	"c709_otherIFT_evol_ratio",
	"c710_biologicalWaysSolution_evol_ratio",
	"c100_networksource",
	"c109_country",
	"c9633_hri1tothts_ipm",
	"c9634_hri1g1hts_ipm",
	"c9635_hri1g2hts_ipm",
	"c9636_hri1g3hts_ipm",
	"c9637_hri1g4hts_ipm",
	"c633_hri1tothts",
	"c634_hri1g1hts",
	"c635_hri1g2hts",
	"c636_hri1g3hts",
	"c637_hri1g4hts",
	"c640_qteSubstActive",
	"c641_qteSubstCMR",
	"c642_qteSubsttoxique",
	"c643_qteSubstglyphosate",
	"c644_qteSubstdangerenvironnement",
	"c645_qteSubstcuivre",
	"c646_qteSubstsoufre",
	"c9303_labourTime",
	"c9502_grossProfit",
	"c9503_semiNetMargin",
	"c9506_labourExpenses",
	"c1001_networksource"
from entrepot_data_ipmgraph_for_dephygraph;