CREATE TABLE entrepot_materiel AS
SELECT 
    rm.topiaid as id,
    case 
        when rm.topiadiscriminator like '%Traction%' then 'Tracteur'
        when rm.topiadiscriminator like '%Automoteur%' then 'Automoteur'
        when rm.topiadiscriminator like '%Outil%' then 'Outil'
        when rm.topiadiscriminator like '%Irrigation%' then 'Irrigation'
    end categorie,
    rm.typemateriel1,
    rm.typemateriel2,
    rm.typemateriel3,
    rm.typemateriel4,
    rm.uniteparan,
    rm.unite,
    rm.active,
    rm.idtypemateriel,
    rm.codetype,
    rm.idsoustypemateriel,
    rm.commentairesurmateriel,
    rm.millesime,
    rm.coderef,
    rm.prixneufunite,
    rm.prixmoyenachat,
    rm.chargesfixesparan,
    rm.chargesfixesparunitedevolumedetravailannuelunite,
    rm.chargesfixesparunitedevolumedetravailannuel,
    rm.energieunite,
    rm.coutenergieparunitedetravail,
    rm.couttotalunite,
    rm.couttotalparunitedetravailannuel,
    rm.code_materiel_gestim,
    rm.masse,
    rm.duree_vie_theorique,
    rm.codeedi,
    rm.source,
    rm.chargesfixesannuelleunite,
    rm.reparationsunite,
    rm.reparationsparunitedetravailannuel,
    rm.carburantcoutunite,
    rm.carburantparunitedetravail,
    rm.lubrifiantcoutunite,
    rm.lubrifiantparunitedetravail,
    rm.couttotalaveccarburantparunitedetravailannuel,
    rm.couttotalsanscarburantparunitedetravailannuel,
    rm.puissancechiso,
    rm.volumecarterhuilemoteurunite,
    rm.volumecarterhuilemoteur,
    rm.performanceunite,
    rm.performance,
    rm.performancecouttotalunite,
    rm.performancecouttotalaveccarburantparh,
    rm.performancecouttotalsanscarburantparh,
    rm.donneestauxdechargemoteur,
    rm.donneesamortissement1,
    rm.donneesamortissement2,
    rm.donneestransport1unite,
    rm.donneestransport1,
    rm.donneestransport2unite,
    rm.donneestransport2,
    rm.donneestransport3unite,
    rm.donneestransport3,
    rm.puissancechisounite,
    rm.pneuscoutunite,
    rm.pneusparunitedetravail,
    rm.volumecarterhuilebvunite,
    rm.volumecarterhuilebv,
    rm.pneusavtaille,
    rm.pneusavprix,
    rm.pneusavprixunite,
    rm.pneusavdureevieunite,
    rm.pneusavdureevie,
    rm.pneusarprixunite,
    rm.pneusarprix,
    rm.pneusardureevieunite,
    rm.pneusardureevie,
    rm.performancecouttotal,
    rm.donneespuissance1adequateunite,
    rm.donneespuissance1adequate,
    rm.petitmateriel
FROM refmateriel rm;

ALTER TABLE entrepot_materiel
ADD CONSTRAINT entrepot_materiel_PK
PRIMARY KEY (id);
