--------------------
-- performances à l'échelle intrant
--------------------
DROP TABLE IF EXISTS entrepot_utilisation_intrant_performance CASCADE;

create table entrepot_utilisation_intrant_performance AS
SELECT
    replace(replace(id_usage,CHR(13)||CHR(10),'<br>'),CHR(10),'<br>') AS utilisation_intrant_id,
    approche_de_calcul AS approche_de_calcul,
	-- IFT
    ift_a_l_ancienne_ift_chimique_total AS ift_histo_chimique_tot,
    ift_a_l_ancienne_ift_chimique_tot_hts AS ift_histo_chim_tot_hts,
    ift_a_l_ancienne_ift_h AS ift_histo_h,
    ift_a_l_ancienne_ift_f AS ift_histo_f,
    ift_a_l_ancienne_ift_i AS ift_histo_i,
    ift_a_l_ancienne_ift_ts AS ift_histo_ts,
    ift_a_l_ancienne_ift_a AS ift_histo_a,
    ift_a_l_ancienne_ift_hh AS ift_histo_hh,
    ift_a_l_ancienne_ift_biocontrole AS ift_histo_biocontrole,
    ift_a_l_ancienne_tx_completion AS ift_histo_tx_comp,
    replace(replace(ift_a_l_ancienne_detail_champs_non_renseig,CHR(13)||CHR(10),'<br>'),CHR(10),'<br>') AS ift_histo_chmps_non_rens,
    replace(replace(ift_a_l_ancienne_dose_reference,CHR(13)||CHR(10),'<br>'),CHR(10),'<br>') AS ift_histo_dose_ref,
    replace(replace(ift_a_l_ancienne_dose_reference_unite,CHR(13)||CHR(10),'<br>'),CHR(10),'<br>') AS ift_histo_dose_ref_unite,
    ift_a_la_cible_non_mil_ift_chimique_total AS ift_cible_non_mil_chimique_tot,
    ift_a_la_cible_non_mil_ift_chimique_tot_hts AS ift_cible_non_mil_chim_tot_hts,
    ift_a_la_cible_non_mil_ift_h AS ift_cible_non_mil_h,
    ift_a_la_cible_non_mil_ift_f AS ift_cible_non_mil_f,
    ift_a_la_cible_non_mil_ift_i AS ift_cible_non_mil_i,
    ift_a_la_cible_non_mil_ift_ts AS ift_cible_non_mil_ts,
    ift_a_la_cible_non_mil_ift_a AS ift_cible_non_mil_a,
    ift_a_la_cible_non_mil_ift_hh AS ift_cible_non_mil_hh,
    ift_a_la_cible_non_mil_ift_biocontrole AS ift_cible_non_mil_biocontrole,
    ift_a_la_cible_non_mil_taux_de_completion AS ift_cible_non_mil_tx_comp,
    replace(replace(ift_a_la_cible_non_mil_detail_champs_non_renseig,CHR(13)||CHR(10),'<br>'),CHR(10),'<br>') AS ift_cible_non_mil_chmps_non_rens,
    replace(replace(ift_a_la_cible_non_mil_dose_reference,CHR(13)||CHR(10),'<br>'),CHR(10),'<br>') AS ift_cible_non_mil_dose_ref,
    replace(replace(ift_a_la_cible_non_mil_dose_reference_unite,CHR(13)||CHR(10),'<br>'),CHR(10),'<br>') AS ift_cible_non_mil_dose_ref_unite,
    ift_a_la_cible_mil_ift_chimique_total AS ift_cible_mil_chimique_tot,
    ift_a_la_cible_mil_ift_chimique_tot_hts AS ift_cible_mil_chim_tot_hts,
    ift_a_la_cible_mil_ift_h AS ift_cible_mil_h,
    ift_a_la_cible_mil_ift_f AS ift_cible_mil_f,
    ift_a_la_cible_mil_ift_i AS ift_cible_mil_i,
    ift_a_la_cible_mil_ift_ts AS ift_cible_mil_ts,
    ift_a_la_cible_mil_ift_a AS ift_cible_mil_a,
    ift_a_la_cible_mil_ift_hh AS ift_cible_mil_hh,
    ift_a_la_cible_mil_ift_biocontrole AS ift_cible_mil_biocontrole,
    ift_a_la_cible_mil_taux_de_completion AS ift_cible_mil_tx_comp,
    replace(replace(ift_a_la_cible_mil_detail_champs_non_renseig,CHR(13)||CHR(10),'<br>'),CHR(10),'<br>') AS ift_cible_mil_chmps_non_rens,
    replace(replace(ift_a_la_cible_mil_dose_reference,CHR(13)||CHR(10),'<br>'),CHR(10),'<br>') AS ift_cible_mil_dose_ref,
    replace(replace(ift_a_la_cible_mil_dose_reference_unite,CHR(13)||CHR(10),'<br>'),CHR(10),'<br>') AS ift_cible_mil_dose_ref_unite,
    ift_a_la_culture_non_mil_ift_chimique_total AS ift_culture_non_mil_chimique_tot,
    ift_a_la_culture_non_mil_ift_chimique_tot_hts AS ift_culture_non_mil_chim_tot_hts,
    ift_a_la_culture_non_mil_ift_h AS ift_culture_non_mil_h,
    ift_a_la_culture_non_mil_ift_f AS ift_culture_non_mil_f,
    ift_a_la_culture_non_mil_ift_i AS ift_culture_non_mil_i,
    ift_a_la_culture_non_mil_ift_ts AS ift_culture_non_mil_ts,
    ift_a_la_culture_non_mil_ift_a AS ift_culture_non_mil_a,
    ift_a_la_culture_non_mil_ift_hh AS ift_culture_non_mil_hh,
    ift_a_la_culture_non_mil_ift_biocontrole AS ift_culture_non_mil_biocontrole,
    ift_a_la_culture_non_mil_taux_de_completion AS ift_culture_non_mil_tx_comp,
    replace(replace(ift_a_la_culture_non_mil_detail_champs_non_renseig,CHR(13)||CHR(10),'<br>'),CHR(10),'<br>') AS ift_culture_non_mil_chmp_no_rens,
    replace(replace(ift_a_la_culture_non_mil_dose_reference,CHR(13)||CHR(10),'<br>'),CHR(10),'<br>') AS ift_culture_non_mil_dose_ref,
    replace(replace(ift_a_la_culture_non_mil_dose_reference_unite,CHR(13)||CHR(10),'<br>'),CHR(10),'<br>') AS ift_culture_non_mil_dose_ref_unite,
    ift_a_la_culture_mil_ift_chimique_total AS ift_culture_mil_chimique_tot,
    ift_a_la_culture_mil_ift_chimique_tot_hts AS ift_culture_mil_chim_tot_hts,
    ift_a_la_culture_mil_ift_h AS ift_culture_mil_h,
    ift_a_la_culture_mil_ift_f AS ift_culture_mil_f,
    ift_a_la_culture_mil_ift_i AS ift_culture_mil_i,
    ift_a_la_culture_mil_ift_ts AS ift_culture_mil_ts,
    ift_a_la_culture_mil_ift_a AS ift_culture_mil_a,
    ift_a_la_culture_mil_ift_hh AS ift_culture_mil_hh,
    ift_a_la_culture_mil_ift_biocontrole AS ift_culture_mil_biocontrole,
    ift_a_la_culture_mil_taux_de_completion AS ift_culture_mil_tx_comp,
    replace(replace(ift_a_la_culture_mil_detail_champs_non_renseig,CHR(13)||CHR(10),'<br>'),CHR(10),'<br>') AS ift_culture_mil_chmps_non_rens,
    replace(replace(ift_a_la_culture_mil_dose_reference,CHR(13)||CHR(10),'<br>'),CHR(10),'<br>') AS ift_culture_mil_dose_ref,
    replace(replace(ift_a_la_culture_mil_dose_reference_unite,CHR(13)||CHR(10),'<br>'),CHR(10),'<br>') AS ift_culture_mil_dose_ref_unite,
    -- Recours aux moyens bio
    recours_moyens_biologiques AS recours_aux_moyens_biologiques,
    recours_macroorganismes,
    recours_produits_biotiques_sansamm,
    recours_produits_abiotiques_sansamm,
    -- CO
    charges_operationnelles_tot_reelles AS CO_tot_reelles,
    charges_operationnelles_tot_reelles_taux_de_completion AS CO_tot_reelles_tx_comp,
    replace(replace(charges_operationnelles_tot_reelles_detail_champs_non_renseig,CHR(13)||CHR(10),'<br>'),CHR(10),'<br>') AS CO_tot_reell_chmps_non_rens,
    charges_operationnelles_tot_std_mil AS CO_tot_std_mil,
    charges_operationnelles_tot_std_mil_taux_de_completion AS CO_tot_std_mil_tx_comp,
    replace(replace(charges_operationnelles_tot_std_mil_detail_champs_non_renseig,CHR(13)||CHR(10),'<br>'),CHR(10),'<br>') AS CO_tot_std_mil_chp_non_rens,
    -- CO decomposees
    charges_operationnelles_semis_reelles as CO_semis_reel,
    charges_operationnelles_semis_std_mil as CO_semis_std_mil,
    charges_operationnelles_fertimin_reelles as CO_fertimin_reel,
    charges_operationnelles_fertimin_std_mil as CO_fertimin_std_mil,
    charges_operationnelles_epandage_orga_reelles as CO_epandage_orga_reelles,
    charges_operationnelles_epandage_orga_std_mil as CO_epandage_orga_std_mil,
    charges_operationnelles_phyto_sans_amm_reelles as CO_phyto_sans_amm_reelles,
    charges_operationnelles_phyto_sans_amm_std_mil as CO_phyto_sans_amm_std_mil,
    charges_operationnelles_phyto_avec_amm_reelles as CO_phyto_avec_amm_reelles,
    charges_operationnelles_phyto_avec_amm_std_mil as CO_phyto_avec_amm_std_mil,
    charges_operationnelles_trait_semence_reelles as CO_trait_semence_reelles,
    charges_operationnelles_trait_semence_std_mil as CO_trait_semence_std_mil,
    charges_operationnelles_irrigation_reelles as CO_irrigation_reelles,
    charges_operationnelles_irrigation_std_mil as CO_irrigation_std_mil,
    charges_operationnelles_substrats_reelles as CO_substrats_reelles,
    charges_operationnelles_substrats_std_mil as CO_substrats_std_mil,
    charges_operationnelles_pots_reelles as CO_pots_reelles,
    charges_operationnelles_pots_std_mil as CO_pots_std_mil,
    charges_operationnelles_intrants_autres_reelles as CO_intrants_autres_reelles,
    charges_operationnelles_intrants_autres_std_mil as CO_intrants_autres_std_mil,
    charges_operationnelles_reelles_decomposees_taux_de_completion as CO_decomposees_reel_tx_comp,
    charges_operationnelles_std_mil_decomposees_taux_de_completion as CO_decomposees_std_mil_tx_comp,
    replace(replace(charges_operationnelles_reelles_decomposees_detail_champs_non_r,CHR(13)||CHR(10),'<br>'),CHR(10),'<br>') AS CO_decomposees_reel_chp_non_rens,
    replace(replace(charges_operationnelles_std_mil_decomposees_detail_champs_non_r,CHR(13)||CHR(10),'<br>'),CHR(10),'<br>') AS CO_decomposees_std_mil_chp_non_rens,
    
	-- Ferti
    ferti_N_tot,
    ferti_N_mineral,
    ferti_N_organique,
    ferti_P2O5_tot,
    ferti_P2O5_mineral,
    ferti_P2O5_organique,
    ferti_K2O_tot,
    ferti_K2O_mineral,
    ferti_K2O_organique,
    ferti_Ca_mineral,
    ferti_CaO_organique,
    ferti_MgO_mineral,
    ferti_MgO_organique,
    ferti_SO3_mineral,
    ferti_S_organique,
    ferti_B_mineral,
    ferti_Cu_mineral,
    ferti_Fe_mineral,
    ferti_Mn_mineral,
    ferti_Mo_mineral,
    ferti_Na2O_mineral,
    ferti_Zn_mineral,
    -- Substances actives
    hri1_tot,
    hri1_hts,
    hri1_tot_taux_de_completion,
    replace(replace(hri1_tot_detail_champs_non_renseig,CHR(13)||CHR(10),'<br>'),CHR(10),'<br>') as hri1_tot_detail_champs_non_renseig,
    hri1_g1_tot,
    hri1_g1_hts,
    hri1_g1_tot_taux_de_completion,
    replace(replace(hri1_g1_tot_detail_champs_non_renseig,CHR(13)||CHR(10),'<br>'),CHR(10),'<br>') as hri1_g1_tot_detail_champs_non_renseig,
    hri1_g2_tot,
    hri1_g2_hts,
    hri1_g2_tot_taux_de_completion,
    replace(replace(hri1_g2_tot_detail_champs_non_renseig,CHR(13)||CHR(10),'<br>'),CHR(10),'<br>') as hri1_g2_tot_detail_champs_non_renseig,
    hri1_g3_tot,
    hri1_g3_hts,
    hri1_g3_tot_taux_de_completion,
    replace(replace(hri1_g3_tot_detail_champs_non_renseig,CHR(13)||CHR(10),'<br>'),CHR(10),'<br>') as hri1_g3_tot_detail_champs_non_renseig,
    hri1_g4_tot,
    hri1_g4_hts,
    hri1_g4_tot_taux_de_completion,
    replace(replace(hri1_g4_tot_detail_champs_non_renseig,CHR(13)||CHR(10),'<br>'),CHR(10),'<br>') as hri1_g4_tot_detail_champs_non_renseig,
    qsa_tot,
    qsa_tot_hts,
    qsa_tot_taux_de_completion,
    replace(replace(qsa_tot_detail_champs_non_renseig,CHR(13)||CHR(10),'<br>'),CHR(10),'<br>') as qsa_tot_detail_champs_non_renseig,
    qsa_danger_environnement,
    qsa_danger_environnement_hts,
    qsa_toxique_utilisateur,
    qsa_toxique_utilisateur_hts,
    qsa_cmr,
    qsa_cmr_hts,
    qsa_substances_candidates_substitution,
    qsa_substances_candidates_substitution_hts,
    qsa_substances_faible_risque,
    qsa_substances_faible_risque_hts,
    qsa_glyphosate,
    qsa_glyphosate_hts,
    qsa_chlortoluron,
    qsa_chlortoluron_hts,
    qsa_diflufenican,
    qsa_diflufenican_hts,
    qsa_prosulfocarbe,
    qsa_prosulfocarbe_hts,
    qsa_smetolachlore,
    qsa_smetolachlore_hts,
    qsa_boscalid,
    qsa_boscalid_hts,
    qsa_fluopyram,
    qsa_fluopyram_hts,
    qsa_lambda_cyhalothrine,
    qsa_lambda_cyhalothrine_hts,
    qsa_cuivre_metal_tot,
    qsa_cuivre_metal_tot_hts,
    qsa_cuivre_metal_phyto,
    qsa_cuivre_metal_phyto_hts,
    qsa_cuivre_metal_ferti,
    qsa_cuivre_metal_mfsc_hts,
    qsa_cuivre_mfsc_hts,
    qsa_cuivre_phyto,
    qsa_cuivre_phyto_hts,
    qsa_soufre_tot,
    qsa_soufre_tot_hts,
    qsa_soufre_phyto,
    qsa_soufre_phyto_hts,
    qsa_soufre_ferti,
    qsa_bixafen,
	qsa_dicamba,
	qsa_mancozeb,
	qsa_phosmet,
	qsa_tebuconazole,
	qsa_dimethenamidp,
	qsa_pendimethalin,
	qsa_flufenacet,
	qsa_aclonifen,
	qsa_isoxaben,
	qsa_beflutamid,
	qsa_isoproturon ,
	qsa_clothianidine,
	qsa_imidaclopride,
	qsa_thiamethoxam,
	qsa_acetamipride,
	qsa_thiaclopride,
	qsa_neonicotinoides,
    qsa_abamectine,
    qsa_abamectine_hts,
    qsa_alpha_cypermethrine,
    qsa_alpha_cypermethrine_hts,
    qsa_azadirachtine,
    qsa_azadirachtine_hts,
    qsa_beta_cyfluthrine,
    qsa_beta_cyfluthrine_hts,
    qsa_chlorpyrifos_methyl,
    qsa_chlorpyrifos_methyl_hts,
    qsa_cyantraniliprole,
    qsa_cyantraniliprole_hts,
    qsa_cypermethrine,
    qsa_cypermethrine_hts,
    qsa_deltamethrine,
    qsa_deltamethrine_hts,
    qsa_dimethoate,
    qsa_dimethoate_hts,
    qsa_emamectine,
    qsa_emamectine_hts,
    qsa_esfenvalerate,
    qsa_esfenvalerate_hts,
    qsa_flonicamide,
    qsa_flonicamide_hts,
    qsa_huile_de_colza,
    qsa_huile_de_colza_hts,
    qsa_huile_de_paraffine,
    qsa_huile_de_paraffine_hts,
    qsa_indoxacarbe,
    qsa_indoxacarbe_hts,
    qsa_primicarbe,
    qsa_primicarbe_hts,
    qsa_pymetrozine,
    qsa_pymetrozine_hts,
    qsa_pyrethrine,
    qsa_pyrethrine_hts,
    qsa_silicate_aluminium,
    qsa_silicate_aluminium_hts,
    qsa_spinosad,
    qsa_spinosad_hts,
    qsa_spirotetramate,
    qsa_spirotetramate_hts,
    qsa_tau_fluvalinate,
    qsa_tau_fluvalinate_hts,
    qsa_benfluralin_hts,
    qsa_bentazone_hts,
    qsa_cycloxydim_hts,
    qsa_dichlorprop_p_hts,
    qsa_dimethachlor_hts,
    qsa_flazasulfuron_hts,
    qsa_fluazifop_p_hts,
    qsa_flumetralin_hts,
    qsa_fluometuron_hts,
    qsa_flurochloridone_hts,
    qsa_haloxyfop_p_hts,
    qsa_imazamox_hts,
    qsa_isoxaflutole_hts,
    qsa_lenacil_hts,
    qsa_mcpa_hts,
    qsa_metazachlor_hts,
    qsa_metobromuron_hts,
    qsa_metribuzin_hts,
    qsa_napropamide_hts,
    qsa_nicosulfuron_hts,
    qsa_oxyfluorfene_hts,
    qsa_penoxsulame_hts,
    qsa_phenmedipham_hts,
    qsa_propyzamide_hts,
    qsa_prosulfuron_hts,
    qsa_pyroxsulam_hts,
    qsa_sulcotrione_hts,
    qsa_tembotrione_hts,
    qsa_terbuthylazine_hts,
    qsa_triflusulfuron_formerly_triflusulfuron_methyl_hts as qsa_triflusulfuron_hts,
    qsa_tritosulfuron_hts,
    qsa_azoxystrobin,
    qsa_azoxystrobin_hts,
    qsa_benthiavalicarb_hts,
    qsa_benzovindiflupyr_hts,
    qsa_bromuconazole_hts,
    qsa_captan,
    qsa_captan_hts,
    qsa_cymoxanil,
    qsa_cymoxanil_hts,
    qsa_cyprodinil,
    qsa_cyprodinil_hts,
    qsa_dazomet_hts,
    qsa_difenoconazole,
    qsa_difenoconazole_hts,
    qsa_dimethomorph_hts,
    qsa_dimoxystrobin_hts,
    qsa_dithianon_hts,
    qsa_etofenprox_hts,
    qsa_fludioxonil,
    qsa_fludioxonil_hts,
    qsa_fluopicolide,
    qsa_fluopicolide_hts,
    qsa_fluxapyroxad,
    qsa_fluxapyroxad_hts,
    qsa_folpet,
    qsa_folpet_hts,
    qsa_metconazole_hts,
    qsa_metiram_hts,
    qsa_prothioconazole,
    qsa_prothioconazole_hts,
    qsa_pyraclostrobin,
    qsa_pyraclostrobin_hts,
    qsa_spiroxamine_hts,
    qsa_ziram,
    qsa_ziram_hts,
    qsa_cyflufenamid_hts,
    qsa_fluazinam,
    qsa_fluazinam_hts,
    qsa_flutianil_hts,
    qsa_flutolanil,
    qsa_flutolanil_hts,
    qsa_mefentrifluconazole_hts,
    qsa_oxathiapiproline,
    qsa_oxathiapiproline_hts,
    qsa_penthiopyrade,
    qsa_penthiopyrade_hts,
    qsa_picoxystrobine_hts,
    qsa_tetraconazole,
    qsa_tetraconazole_hts,
    qsa_trifloxystrobin_hts,
    qsa_triflumizole_hts,
    qsa_acrinathrine_hts,
    qsa_bifenthrine_hts,
    qsa_chlorantraniliprole,
    qsa_chlorantraniliprole_hts,
    qsa_chlormequat_hts,
    qsa_cyflumetofen_hts,
    qsa_fipronil,
    qsa_fipronil_hts,
    qsa_flubendiamide_hts,
    qsa_flufenoxuron_hts,
    qsa_fosthiazate_hts,
    qsa_gamma_cyhalothrine_hts,
    qsa_metaflumizone_hts,
    qsa_oxamyl_hts,
    qsa_pirimiphos_methyl_hts,
    qsa_pyridalyle_hts,
    qsa_spinetoram_hts,
    qsa_sulfoxaflor_hts,
    qsa_tefluthrin,
    qsa_tefluthrin_hts,
    qsa_triflumuron_hts,
    qsa_zinc_phosphide_hts,
    qsa_totale_herbicides_parsada,
    qsa_totale_herbicides_parsada_hts,
    qsa_totale_parsada,
    qsa_totale_parsada_hts,
    qsa_pfas,
    qsa_pfas_hts,
    qsa_h,
    qsa_h_hts,
    qsa_f,
    qsa_f_hts,
    qsa_i,
    qsa_i_hts,
    qsa_ts,
    qsa_a,
    qsa_a_hts,
    -- GESTIM
    ges_ferti_orga_directes_co2,
    ges_ferti_orga_directes_ch4,
    ges_ferti_orga_directes_n2o,
    ges_ferti_orga_directes_ges_total,
    ges_ferti_orga_total_co2,
    ges_ferti_orga_total_ch4,
    ges_ferti_orga_total_n2o,
    ges_ferti_orga_total_ges_total,
    pa_ferti_orga_directes_so2,
    pa_ferti_orga_directes_nox,
    pa_ferti_orga_directes_nh3,
    pa_ferti_orga_total_so2,
    pa_ferti_orga_total_nox,
    pa_ferti_orga_total_nh3,
    energie_ferti_orga,
    ges_phyto_indirectes_co2,
    ges_phyto_indirectes_ch4,
    ges_phyto_indirectes_n2o,
    ges_phyto_indirectes_ges_total,
    ges_phyto_total_co2,
    ges_phyto_total_ch4,
    ges_phyto_total_n2o,
    ges_phyto_total_ges_total,
    pa_phyto_indirectes_so2,
    pa_phyto_indirectes_nox,
    pa_phyto_indirectes_nh3,
    pa_phyto_total_so2,
    pa_phyto_total_nox,
    pa_phyto_total_nh3,
    energie_phyto,
    ges_traitement_semences_indirectes_co2,
    ges_traitement_semences_indirectes_ch4,
    ges_traitement_semences_indirectes_n2o,
    ges_traitement_semences_indirectes_ges_total,
    ges_traitement_semences_total_co2,
    ges_traitement_semences_total_ch4,
    ges_traitement_semences_total_n2o,
    ges_traitement_semences_total_ges_total,
    pa_traitement_semences_indirectes_so2,
    pa_traitement_semences_indirectes_nox,
    pa_traitement_semences_indirectes_nh3,
    pa_traitement_semences_total_so2,
    pa_traitement_semences_total_nox,
    pa_traitement_semences_total_nh3,
    energie_traitement_semences,
    ges_ferti_min_directes_co2,
    ges_ferti_min_directes_ch4,
    ges_ferti_min_directes_n2o,
    ges_ferti_min_directes_ges_total,
    ges_ferti_min_indirectes_co2,
    ges_ferti_min_indirectes_ch4,
    ges_ferti_min_indirectes_n2o,
    ges_ferti_min_indirectes_ges_total,
    ges_ferti_min_total_co2,
    ges_ferti_min_total_ch4,
    ges_ferti_min_total_n2o,
    ges_ferti_min_total_ges_total,
    pa_ferti_min_directes_so2,
    pa_ferti_min_directes_nox,
    pa_ferti_min_directes_nh3,
    pa_ferti_min_indirectes_so2,
    pa_ferti_min_indirectes_nox,
    pa_ferti_min_indirectes_nh3,
    pa_ferti_min_total_so2,
    pa_ferti_min_total_nox,
    pa_ferti_min_total_nh3,
    energie_ferti_min,
    ges_semis_indirectes_co2,
    ges_semis_indirectes_ch4,
    ges_semis_indirectes_n2o,
    ges_semis_indirectes_ges_total,
    ges_semis_total_co2,
    ges_semis_total_ch4,
    ges_semis_total_n2o,
    ges_semis_total_ges_total,
    pa_semis_indirectes_so2,
    pa_semis_indirectes_nox,
    pa_semis_indirectes_nh3,
    pa_semis_total_so2,
    pa_semis_total_nox,
    pa_semis_total_nh3,
    energie_semis,
    ges_totaux_directes_co2,
    ges_totaux_directes_ch4,
    ges_totaux_directes_n2o,
    ges_totaux_directes_ges_total,
    ges_totaux_indirectes_co2,
    ges_totaux_indirectes_ch4,
    ges_totaux_indirectes_n2o,
    ges_totaux_indirectes_ges_total,
    ges_totaux_total_co2,
    ges_totaux_total_ch4,
    ges_totaux_total_n2o,
    ges_totaux_total_ges_total,
    pa_totaux_directes_so2,
    pa_totaux_directes_nox,
    pa_totaux_directes_nh3,
    pa_totaux_indirectes_so2,
    pa_totaux_indirectes_nox,
    pa_totaux_indirectes_nh3,
    pa_totaux_total_so2,
    pa_totaux_total_nox,
    pa_totaux_total_nh3,
    energie_totale_indirectes,
    energie_totale_directes,
    -- Alertes
    alerte_rendement,
    -- Recours produits hors bio
    recours_produits_cmr,
    recours_produits_cmr_hts,
    recours_produits_toxiques_utilisateurs,
    recours_produits_toxiques_utilisateurs_hts,
    recours_produits_danger_environnement,
    recours_produits_danger_environnement_hts
    FROM echelle_intrant ei
    LEFT JOIN entrepot_utilisation_intrant_realise euir on euir.id = ei.id_usage
    LEFT JOIN entrepot_utilisation_intrant_synthetise euis on euis.id = ei.id_usage
    where (euir.id is not null and euis.id is null) OR (euir.id is null and euis.id is not null);

DO $$
BEGIN
    BEGIN
        alter table entrepot_utilisation_intrant_performance
        add constraint utilisation_intrant_performance_PK
        PRIMARY KEY (utilisation_intrant_id);
    EXCEPTION
        WHEN others THEN
            RAISE WARNING '⚠ Impossible de créer la primary key : %', SQLERRM;
    END;
END $$;
