---------------------------------------------------------------
-- performances à l'échelle de la zone pour les réalisés
---------------------------------------------------------------

create table entrepot_zone_realise_performance AS
SELECT
    replace(replace(zone_id,CHR(13)||CHR(10),'<br>'),CHR(10),'<br>') AS zone_id,
    approche_de_calcul AS approche_de_calcul,
	-- IFT
    ift_a_l_ancienne_ift_chimique_total AS ift_histo_chimique_tot,
    ift_a_l_ancienne_ift_chimique_tot_hts AS ift_histo_chim_tot_hts,
    ift_a_l_ancienne_ift_h AS ift_histo_h,
    ift_a_l_ancienne_ift_f AS ift_histo_f,
    ift_a_l_ancienne_ift_i AS ift_histo_i,
    ift_a_l_ancienne_ift_ts AS ift_histo_ts,
    ift_a_l_ancienne_ift_a AS ift_histo_a,
    ift_a_l_ancienne_ift_hh AS ift_histo_hh,
    ift_a_l_ancienne_ift_biocontrole AS ift_histo_biocontrole,
    ift_a_l_ancienne_tx_completion AS ift_histo_tx_comp,
    ift_a_la_cible_non_mil_ift_chimique_total AS ift_cible_non_mil_chimique_tot,
    ift_a_la_cible_non_mil_ift_chimique_tot_hts AS ift_cible_non_mil_chim_tot_hts,
    ift_a_la_cible_non_mil_ift_h AS ift_cible_non_mil_h,
    ift_a_la_cible_non_mil_ift_f AS ift_cible_non_mil_f,
    ift_a_la_cible_non_mil_ift_i AS ift_cible_non_mil_i,
    ift_a_la_cible_non_mil_ift_ts AS ift_cible_non_mil_ts,
    ift_a_la_cible_non_mil_ift_a AS ift_cible_non_mil_a,
    ift_a_la_cible_non_mil_ift_hh AS ift_cible_non_mil_hh,
    ift_a_la_cible_non_mil_ift_biocontrole AS ift_cible_non_mil_biocontrole,
    ift_a_la_cible_non_mil_taux_de_completion AS ift_cible_non_mil_tx_comp,
    ift_a_la_cible_mil_ift_chimique_total AS ift_cible_mil_chimique_tot,
    ift_a_la_cible_mil_ift_chimique_tot_hts AS ift_cible_mil_chim_tot_hts,
    ift_a_la_cible_mil_ift_h AS ift_cible_mil_h,
    ift_a_la_cible_mil_ift_f AS ift_cible_mil_f,
    ift_a_la_cible_mil_ift_i AS ift_cible_mil_i,
    ift_a_la_cible_mil_ift_ts AS ift_cible_mil_ts,
    ift_a_la_cible_mil_ift_a AS ift_cible_mil_a,
    ift_a_la_cible_mil_ift_hh AS ift_cible_mil_hh,
    ift_a_la_cible_mil_ift_biocontrole AS ift_cible_mil_biocontrole,
    ift_a_la_cible_mil_taux_de_completion AS ift_cible_mil_tx_comp,
    ift_a_la_culture_non_mil_ift_chimique_total AS ift_culture_non_mil_chimique_tot,
    ift_a_la_culture_non_mil_ift_chimique_tot_hts AS ift_culture_non_mil_chim_tot_hts,
    ift_a_la_culture_non_mil_ift_h AS ift_culture_non_mil_h,
    ift_a_la_culture_non_mil_ift_f AS ift_culture_non_mil_f,
    ift_a_la_culture_non_mil_ift_i AS ift_culture_non_mil_i,
    ift_a_la_culture_non_mil_ift_ts AS ift_culture_non_mil_ts,
    ift_a_la_culture_non_mil_ift_a AS ift_culture_non_mil_a,
    ift_a_la_culture_non_mil_ift_hh AS ift_culture_non_mil_hh,
    ift_a_la_culture_non_mil_ift_biocontrole AS ift_culture_non_mil_biocontrole,
    ift_a_la_culture_non_mil_taux_de_completion AS ift_culture_non_mil_tx_comp,
    ift_a_la_culture_mil_ift_chimique_total AS ift_culture_mil_chimique_tot,
    ift_a_la_culture_mil_ift_chimique_tot_hts AS ift_culture_mil_chim_tot_hts,
    ift_a_la_culture_mil_ift_h AS ift_culture_mil_h,
    ift_a_la_culture_mil_ift_f AS ift_culture_mil_f,
    ift_a_la_culture_mil_ift_i AS ift_culture_mil_i,
    ift_a_la_culture_mil_ift_ts AS ift_culture_mil_ts,
    ift_a_la_culture_mil_ift_a AS ift_culture_mil_a,
    ift_a_la_culture_mil_ift_hh AS ift_culture_mil_hh,
    ift_a_la_culture_mil_ift_biocontrole AS ift_culture_mil_biocontrole,
    ift_a_la_culture_mil_taux_de_completion AS ift_culture_mil_tx_comp,
    -- Recours aux moyens bio
    recours_moyens_biologiques AS recours_aux_moyens_biologiques,
    recours_macroorganismes,
    recours_produits_biotiques_sansamm,
    recours_produits_abiotiques_sansamm,
    -- temps de travail
    temps_utilisation_du_materiel_janvier AS tps_utilisation_materiel_janvier,
    temps_utilisation_du_materiel_fevrier AS tps_utilisation_materiel_fevrier,
    temps_utilisation_du_materiel_mars  AS tps_utilisation_materiel_mars,
    temps_utilisation_du_materiel_avril AS tps_utilisation_materiel_avril,
    temps_utilisation_du_materiel_mai AS tps_utilisation_materiel_mai,
    temps_utilisation_du_materiel_juin AS tps_utilisation_materiel_juin,
    temps_utilisation_du_materiel_juillet AS tps_utilisation_materiel_juillet,
    temps_utilisation_du_materiel_aout AS tps_utilisation_materiel_aout,
    temps_utilisation_du_materiel_septembre AS tps_utilisation_materiel_sept,
    temps_utilisation_du_materiel_octobre AS tps_utilisation_materiel_oct,
    temps_utilisation_du_materiel_novembre AS tps_utilisation_materiel_nov,
    temps_utilisation_du_materiel_decembre AS tps_utilisation_materiel_dec,
    temps_utilisation_du_materiel AS tps_utilisation_materiel,
    temps_utilisation_du_materiel_taux_de_completion AS tps_utilisation_materiel_tx_comp,
    temps_travail_manuel_janvier AS tps_travail_manuel_janvier,
    temps_travail_manuel_fevrier AS tps_travail_manuel_fevrier,
    temps_travail_manuel_mars AS tps_travail_manuel_mars,
    temps_travail_manuel_avril AS tps_travail_manuel_avril,
    temps_travail_manuel_mai AS tps_travail_manuel_mai,
    temps_travail_manuel_juin AS tps_travail_manuel_juin,
    temps_travail_manuel_juillet AS tps_travail_manuel_juillet,
    temps_travail_manuel_aout AS tps_travail_manuel_aout,
    temps_travail_manuel_septembre AS tps_travail_manuel_septembre,
    temps_travail_manuel_octobre AS tps_travail_manuel_octobre,
    temps_travail_manuel_novembre AS tps_travail_manuel_novembre,
    temps_travail_manuel_decembre AS tps_travail_manuel_decembre,
    temps_travail_manuel AS tps_travail_manuel,
    temps_travail_manuel_taux_de_completion AS tps_travail_manuel_tx_comp,
    temps_travail_mecanise_janvier AS tps_travail_mecanise_janvier,
    temps_travail_mecanise_fevrier AS tps_travail_mecanise_fevrier,
    temps_travail_mecanise_mars AS tps_travail_mecanise_mars,
    temps_travail_mecanise_avril AS tps_travail_mecanise_avril,
    temps_travail_mecanise_mai AS tps_travail_mecanise_mai,
    temps_travail_mecanise_juin AS tps_travail_mecanise_juin,
    temps_travail_mecanise_juillet AS tps_travail_mecanise_juillet,
    temps_travail_mecanise_aout AS tps_travail_mecanise_aout,
    temps_travail_mecanise_septembre AS tps_travail_mecanise_septembre,
    temps_travail_mecanise_octobre AS tps_travail_mecanise_octobre,
    temps_travail_mecanise_novembre AS tps_travail_mecanise_novembre,
    temps_travail_mecanise_decembre AS tps_travail_mecanise_decembre,
    temps_travail_mecanise AS tps_travail_mecanise,
    temps_travail_mecanise_taux_de_completion AS tps_travail_mecanise_tx_comp,
    temps_travail_total_janvier AS tps_travail_total_janvier,
    temps_travail_total_fevrier AS tps_travail_total_fevrier,
    temps_travail_total_mars AS tps_travail_total_mars,
    temps_travail_total_avril AS tps_travail_total_avril,
    temps_travail_total_mai AS tps_travail_total_mai,
    temps_travail_total_juin AS tps_travail_total_juin,
    temps_travail_total_juillet AS tps_travail_total_juillet,
    temps_travail_total_aout AS tps_travail_total_aout,
    temps_travail_total_septembre AS tps_travail_total_septembre,
    temps_travail_total_octobre AS tps_travail_total_octobre,
    temps_travail_total_novembre AS tps_travail_total_novembre,
    temps_travail_total_decembre AS tps_travail_total_decembre,
    temps_travail_total AS tps_travail_total,
    temps_travail_total_taux_de_completion AS tps_travail_total_tx_comp,
    nombre_de_passages_janvier AS nbre_de_passages_janvier,
    nombre_de_passages_fevrier AS nbre_de_passages_fevrier,
    nombre_de_passages_mars AS nbre_de_passages_mars,
    nombre_de_passages_avril AS nbre_de_passages_avril,
    nombre_de_passages_mai AS nbre_de_passages_mai,
    nombre_de_passages_juin AS nbre_de_passages_juin,
    nombre_de_passages_juillet AS nbre_de_passages_juillet,
    nombre_de_passages_aout AS nbre_de_passages_aout,
    nombre_de_passages_septembre AS nbre_de_passages_septembre,
    nombre_de_passages_octobre AS nbre_de_passages_octobre,
    nombre_de_passages_novembre AS nbre_de_passages_novembre,
    nombre_de_passages_decembre AS nbre_de_passages_decembre,
    nombre_de_passages AS nbre_de_passages,
    replace(replace(nombre_de_passages_taux_de_completion,CHR(13)||CHR(10),'<br>'),CHR(10),'<br>') AS nbre_de_passages_tx_comp,
    -- Travail du sol
    nombre_de_passages_labour AS nbre_de_passages_labour,
    nombre_de_passages_labour_taux_de_completion AS nbre_de_passages_labour_tx_comp,
    nombre_de_passages_TCS AS nbre_de_passages_tcs,
    nombre_de_passages_TCS_taux_de_completion AS nbre_de_passages_tcs_tx_comp,
    nombre_de_passages_desherbage_mecanique AS nbre_de_passages_desherbage_meca,
    nombre_de_passages_desherbage_mecanique_taux_de_completion AS nbre_de_passages_desherbage_meca_tx_comp,
    utilisation_desherbage_mecanique AS utili_desherbage_meca,
    utilisation_desherbage_mecanique_taux_de_completion AS utili_desherbage_meca_tx_comp,
    type_de_travail_du_sol,
    type_de_travail_du_sol_taux_de_completion AS type_de_travail_du_sol_tx_comp,
    -- CO
    charges_operationnelles_tot_reelles AS CO_tot_reelles,
    charges_operationnelles_tot_reelles_taux_de_completion AS CO_tot_reelles_tx_comp,
    charges_operationnelles_tot_std_mil AS CO_tot_std_mil,
    charges_operationnelles_tot_std_mil_taux_de_completion AS CO_tot_std_mil_tx_comp,
    -- CO decomposees
    charges_operationnelles_semis_reelles as CO_semis_reel,
    charges_operationnelles_semis_std_mil as CO_semis_std_mil,
    charges_operationnelles_fertimin_reelles as CO_fertimin_reel,
    charges_operationnelles_fertimin_std_mil as CO_fertimin_std_mil,
    charges_operationnelles_epandage_orga_reelles as CO_epandage_orga_reelles,
    charges_operationnelles_epandage_orga_std_mil as CO_epandage_orga_std_mil,
    charges_operationnelles_phyto_sans_amm_reelles as CO_phyto_sans_amm_reelles,
    charges_operationnelles_phyto_sans_amm_std_mil as CO_phyto_sans_amm_std_mil,
    charges_operationnelles_phyto_avec_amm_reelles as CO_phyto_avec_amm_reelles,
    charges_operationnelles_phyto_avec_amm_std_mil as CO_phyto_avec_amm_std_mil,
    charges_operationnelles_trait_semence_reelles as CO_trait_semence_reelles,
    charges_operationnelles_trait_semence_std_mil as CO_trait_semence_std_mil,
    charges_operationnelles_irrigation_reelles as CO_irrigation_reelles,
    charges_operationnelles_irrigation_std_mil as CO_irrigation_std_mil,
    charges_operationnelles_substrats_reelles as CO_substrats_reelles,
    charges_operationnelles_substrats_std_mil as CO_substrats_std_mil,
    charges_operationnelles_pots_reelles as CO_pots_reelles,
    charges_operationnelles_pots_std_mil as CO_pots_std_mil,
    charges_operationnelles_intrants_autres_reelles as CO_intrants_autres_reelles,
    charges_operationnelles_intrants_autres_std_mil as CO_intrants_autres_std_mil,
    charges_operationnelles_reelles_decomposees_taux_de_completion as CO_decomposees_reel_tx_comp,
    charges_operationnelles_std_mil_decomposees_taux_de_completion as CO_decomposees_std_mil_tx_comp,
    -- CM
    charges_de_mecanisation_reelles AS CM_reelles,
    charges_de_mecanisation_reelles_taux_de_completion AS CM_reelles_tx_comp,
    charges_de_mecanisation_std_mil AS CM_std_mil,
    charges_de_mecanisation_std_mil_taux_de_completion AS CM_std_mil_tx_comp,
    -- C main oeuvre
    charges_main_oeuvre_tot_reelles as C_main_oeuvre_tot_reelle,   
    charges_main_oeuvre_tot_reelles_taux_de_completion as C_main_oeuvre_tot_reelle_tx_comp,   
    charges_main_oeuvre_tot_std_mil as C_main_oeuvre_tot_std_mil,   
    charges_main_oeuvre_tot_std_mil_taux_de_completion as C_main_oeuvre_tot_std_mil_tx_comp,   
    charges_main_oeuvre_tractoriste_reelles as C_main_oeuvre_tractoriste_reelle,   
    charges_main_oeuvre_tractoriste_reelles_taux_de_completion as C_main_oeuvre_tractoriste_reelle_tx_comp,   
    charges_main_oeuvre_tractoriste_std_mil as C_main_oeuvre_tractoriste_std_mil,   
    charges_main_oeuvre_tractoriste_std_mil_taux_de_completion as C_main_oeuvre_tractoriste_std_mil_tx_comp,   
    charges_main_oeuvre_manuelle_reelles as C_main_oeuvre_manuelle_reelle,   
    charges_main_oeuvre_manuelle_reelles_taux_de_completion as C_main_oeuvre_manuelle_reelle_tx_comp,   
    charges_main_oeuvre_manuelle_std_mil as C_main_oeuvre_manuelle_std_mil,   
    charges_main_oeuvre_manuelle_std_mil_taux_de_completion as C_main_oeuvre_manuelle_std_mil_tx_comp,   
    -- Produit brut
    produit_brut_reel_sans_autoconso AS PB_reel_sans_autoconso,
    produit_brut_reel_avec_autoconso AS PB_reel_avec_autoconso,
    produit_brut_reel_taux_de_completion AS PB_reel_tx_comp,
    produit_brut_std_mil_avec_autoconso AS PB_std_mil_avec_autoconso,
    produit_brut_std_mil_sans_autoconso AS PB_std_mil_sans_autoconso,
    produit_brut_std_mil_taux_de_completion AS PB_std_mil_tx_comp,
    -- Marges
    marge_brute_reelle_sans_autoconso AS MB_reelle_sans_autoconso,
    marge_brute_reelle_avec_autoconso AS MB_reelle_avec_autoconso,
    marge_brute_reelle_taux_de_completion AS MB_reelle_tx_comp,
    marge_brute_std_mil_avec_autoconso AS MB_std_mil_avec_autoconso,
    marge_brute_std_mil_sans_autoconso AS MB_std_mil_sans_autoconso,
    marge_brute_std_mil_taux_de_completion AS MB_std_mil_tx_comp,
    marge_semi_nette_reelle_sans_autoconso AS MSN_reelle_sans_autoconso,
    marge_semi_nette_reelle_avec_autoconso AS MSN_reelle_avec_autoconso,
    marge_semi_nette_reelle_taux_de_completion AS MSN_reelle_tx_comp,
    marge_semi_nette_std_mil_sans_autoconso AS MSN_std_mil_sans_autoconso,
    marge_semi_nette_std_mil_avec_autoconso AS MSN_std_mil_avec_autoconso,
    marge_semi_nette_std_mil_taux_de_completion AS MSN_std_mil_tx_comp,
    marge_directe_reelle_sans_autoconso AS MD_reelle_sans_autoconso,
    marge_directe_reelle_avec_autoconso AS MD_reelle_avec_autoconso,
    marge_directe_reelle_taux_de_completion AS MD_reelle_tx_comp,
    marge_directe_std_mil_sans_autoconso AS MD_std_mil_sans_autoconso,
    marge_directe_std_mil_avec_autoconso AS MD_std_mil_avec_autoconso,
    marge_directe_std_mil_taux_de_completion AS MD_std_mil_tx_comp,
    -- Performances sociales
    nombre_uth_necessaires,
    consommation_de_carburant AS conso_carburant,
    consommation_de_carburant_taux_de_completion AS conso_carburant_tx_comp,
    consommation_eau as conso_eau,
    consommation_eau_taux_de_completion as conso_eau_tx_comp,
    -- Fertilisation
    ferti_N_tot,
    ferti_N_mineral,
    ferti_N_organique,
    ferti_P2O5_tot,
    ferti_P2O5_mineral,
    ferti_P2O5_organique,
    ferti_K2O_tot,
    ferti_K2O_mineral,
    ferti_K2O_organique,
    ferti_Ca_mineral,
    ferti_CaO_organique,
    ferti_MgO_mineral,
    ferti_MgO_organique,
    ferti_SO3_mineral,
    ferti_S_organique,
    ferti_B_mineral,
    ferti_Cu_mineral,
    ferti_Fe_mineral,
    ferti_Mn_mineral,
    ferti_Mo_mineral,
    ferti_Na2O_mineral,
    ferti_Zn_mineral,
    -- Substances actives
    hri1_tot,
    hri1_hts,
    hri1_tot_taux_de_completion,
    hri1_g1_tot,
    hri1_g1_hts,
    hri1_g1_tot_taux_de_completion,
    hri1_g2_tot,
    hri1_g2_hts,
    hri1_g2_tot_taux_de_completion,
    hri1_g3_tot,
    hri1_g3_hts,
    hri1_g3_tot_taux_de_completion,
    hri1_g4_tot,
    hri1_g4_hts,
    hri1_g4_tot_taux_de_completion,
    qsa_tot,
    qsa_tot_taux_de_completion,
    qsa_tot_hts,
    qsa_danger_environnement,
    qsa_danger_environnement_hts,
    qsa_toxique_utilisateur,
    qsa_toxique_utilisateur_hts,
    qsa_cmr,
    qsa_cmr_hts,
    qsa_substances_candidates_substitution,
    qsa_substances_candidates_substitution_hts,
    qsa_substances_faible_risque,
    qsa_substances_faible_risque_hts,
    qsa_glyphosate,
    qsa_glyphosate_hts,
    qsa_chlortoluron,
    qsa_chlortoluron_hts,
    qsa_diflufenican,
    qsa_diflufenican_hts,
    qsa_prosulfocarbe,
    qsa_prosulfocarbe_hts,
    qsa_smetolachlore,
    qsa_smetolachlore_hts,
    qsa_boscalid,
    qsa_boscalid_hts,
    qsa_fluopyram,
    qsa_fluopyram_hts,
    qsa_lambda_cyhalothrine,
    qsa_lambda_cyhalothrine_hts,
    qsa_cuivre_tot,
    qsa_cuivre_tot_hts,
    qsa_cuivre_phyto,
    qsa_cuivre_phyto_hts,
    qsa_cuivre_ferti,
    qsa_soufre_tot,
    qsa_soufre_tot_hts,
    qsa_soufre_phyto,
    qsa_soufre_phyto_hts,
    qsa_soufre_ferti,
    qsa_bixafen,
	qsa_dicamba,
	qsa_mancozeb,
	qsa_phosmet,
	qsa_tebuconazole,
	qsa_dimethenamidp,
	qsa_pendimethalin,
	qsa_flufenacet,
	qsa_aclonifen,
	qsa_isoxaben,
	qsa_beflutamid,
	qsa_isoproturon ,
	qsa_clothianidine,
	qsa_imidaclopride,
	qsa_thiamethoxam,
	qsa_acetamipride,
	qsa_thiaclopride,
	qsa_neonicotinoides,
    surface_par_unite_de_travail_humain, 
    surface_par_unite_de_travail_humain_taux_de_completion, 
    surface_par_unite_de_travail_humain_detail_champs_non_renseig
FROM realise_echelle_zone rez
JOIN entrepot_zone ez on ez.id = rez.zone_id;


alter table entrepot_zone_realise_performance
add constraint zone_realise_performance_pk
PRIMARY KEY (zone_id);

alter table entrepot_zone_realise_performance
add FOREIGN KEY (zone_id) REFERENCES entrepot_zone(id);
