-- REALISE
SELECT
    COALESCE(sdc.code_dephy, 'CODE_DEPHY_ABSENT') || '_' || sdc.campagne
        AS id_code_dephy_campagne,
    sdc.code_dephy as sdc_code_dephy,
    sdc.campagne as campagne_donnees,
    dispo."type" as dispositif_type,
    errsotdbc.reseaux_ir as reseaux_ir,
    errsotdbc.reseaux_it as reseaux_it,
    dom.id as domaine_id,
    dom.nom as domaine_nom,
    dom.departement as departement,
    dom.sau_totale as sau_domaine,
    dom.campagne as domaine_campagne,
    'synthétisé' as approche_de_calcul,
    sdc.id as sdc_id,
    sdc.nom as sdc_nom, 
    sdc.part_sau_domaine as sdc_part_sau_domaine, 
    esrotdbc.surface_sdc as surface_sdc,
    sdc.type_agriculture as sdc_type_agriculture,
    sdc.type_production as sdc_type_production,
    null as systeme_synthetise_id,
    null as systeme_synthetise_nom,
    null as systeme_synthetise_campagnes,
    etacr.typocan_assol as typo_rotation,
    etacr.nb_culture_sdc as nb_culture_sdc, 
    essrotdbc.surface_betterave as surface_Betterave_SDC,
	essrotdbc.surface_cereale_a_paille_printemps as surface_CaP_Printemps_SDC,
	essrotdbc.surface_cereale_a_paille_hiver as surface_CaP_hiver_SDC,
	essrotdbc.surface_colza as surface_Colza_SDC,
	essrotdbc.surface_legume as surface_Leg_plein_champ_SDC,
	essrotdbc.surface_lin as surface_Lin_fibre_SDC,
	essrotdbc.surface_mais as surface_Mais_Sorgho_SDC,
	essrotdbc.surface_melange_fourrager as surface_Mel_Fourrage_SDC,
	essrotdbc.surface_oleagineux as surface_Olea_SDC,
	essrotdbc.surface_pomme_de_terre as surface_Pdt_SDC,
	essrotdbc.surface_porte_graine as surface_porte_graine_SDC,
	essrotdbc.surface_prairie_temporaire as surface_Prairie_Temp_SDC,
	essrotdbc.surface_proteagineux as surface_Protea_SDC,
	essrotdbc.surface_tournesol as surface_Tournesol_SDC,
	essrotdbc.surface_autre as surface_autre_SDC, 
	esrp.mb_reelle_avec_autoconso as MB_reelle_ac_auto_SDC,
	esrp.msn_reelle_avec_autoconso as MSN_relle_ac_auto_SDC,
	esrp.pb_reel_avec_autoconso as pb_reel_avec_autoconso,
	esrp.co_tot_reelles as CO_reelles_SDC,
	esrp.cm_reelles as CM_reelles_SDC,
	esrp.conso_carburant as conso_carburant_SDC,
	esrp.c_main_oeuvre_tractoriste_std_mil as cout_mo_tractoriste,
	esrp.c_main_oeuvre_manuelle_std_mil as cout_mo_manuelle,
	esrp.nombre_uth_necessaires as nbre_uth_sdc,
	esrp.nbre_de_passages_labour as freq_labour_SDC,
	esrp.nbre_de_passages_tcs as freq_trava_sol_hors_labour_SDC,
	esrp.type_de_travail_du_sol as type_travail_sol_SDC,
	esrp.utili_desherbage_meca as desherbage_mecanique_SDC,
	esrp.nbre_de_passages_desherbage_meca as freq_desh_meca_SDC,
    esrp.ift_cible_non_mil_chimique_tot AS ift_cible_non_mil_chim_tot_SDC,
    esrp.ift_cible_non_mil_chim_tot_hts AS ift_cible_non_mil_chim_tot_hts_SDC,
    esrp.ift_cible_non_mil_biocontrole AS ift_cible_nonmil_biocontrole_SDC,
    esrp.ift_cible_non_mil_h AS ift_cible_non_mil_h_SDC,
    esrp.ift_cible_non_mil_hh AS ift_cible_non_mil_hh_SDC,
    esrp.ift_cible_non_mil_f AS ift_cible_non_mil_f_SDC,
    esrp.ift_cible_non_mil_i AS ift_cible_non_mil_i_SDC,
    esrp.ift_cible_non_mil_a AS ift_cible_non_mil_a_SDC,
    esrp.ift_cible_non_mil_ts AS ift_cible_non_mil_ts_SDC,
    null as ift_norme_sdc, -- TODO
    null as IFT_Hors_TS_Moy_Region, -- TODO
    esrp.qsa_tot AS quantite_mat_active_SDC,
    esrp.qsa_toxique_utilisateur AS quantite_mat_active_danger_SDC,
    esrp.qsa_danger_environnement AS qte_mat_active_danger_env_SDC,
    esrp.qsa_glyphosate AS quantite_mat_active_glypho_SDC,
    esrp.qsa_neonicotinoides AS quantite_mat_active_neonic_SDC,
    esrp.qsa_cuivre_metal_tot AS qte_cuivre_SDC,
    esrp.qsa_cuivre_metal_ferti AS qte_cuivre_engrais_SDC,
    esrp.qsa_cuivre_metal_phyto AS qte_cuivre_phyto_SDC,
    esrp.qsa_soufre_tot AS qte_soufre_SDC,
    esrp.qsa_soufre_ferti AS qte_soufre_engrais_SDC,
    esrp.qsa_soufre_phyto AS qte_soufre_phyto_SDC,
    esrp.ferti_n_tot AS N_SDC,
    esrp.ferti_n_mineral AS N_Mineral_SDC,
    esrp.ferti_n_organique AS N_Orga_SDC,
    esrp.ferti_p2o5_tot AS P_SDC,
    esrp.ferti_p2o5_mineral AS P_Mineral_SDC,
    esrp.ferti_p2o5_organique AS P_Orga_SDC,
    esrp.ferti_k2o_tot AS K_SDC,
    esrp.ferti_k2o_mineral AS K_Mineral_SDC,
    esrp.ferti_k2o_organique AS K_Orga_SDC,
    esrp.conso_eau AS Qte_Eau_mm_ha_SDC,
    esrp.tps_utilisation_materiel AS tps_util_materiel_SDC,
    esrp.tps_utilisation_materiel_janvier AS tps_util_materiel_janvier_SDC,
    esrp.tps_utilisation_materiel_fevrier AS tps_util_materiel_fevrier_SDC,
    esrp.tps_utilisation_materiel_mars AS tps_util_materiel_mars_SDC,
    esrp.tps_utilisation_materiel_avril AS tps_util_materiel_avril_SDC,
    esrp.tps_utilisation_materiel_mai AS tps_util_materiel_mai_SDC,
    esrp.tps_utilisation_materiel_juin AS tps_util_materiel_juin_SDC,
    esrp.tps_utilisation_materiel_juillet AS tps_util_materiel_juillet_SDC,
    esrp.tps_utilisation_materiel_aout AS tps_util_materiel_aout_SDC,
    esrp.tps_utilisation_materiel_sept AS tps_util_materiel_sept_SDC,
    esrp.tps_utilisation_materiel_oct AS tps_util_materiel_oct_SDC,
    esrp.tps_utilisation_materiel_nov AS tps_util_materiel_nov_SDC,
    esrp.tps_utilisation_materiel_dec AS tps_util_materiel_dec_SDC,
    esrp.tps_travail_manuel AS tps_travail_manuel_SDC,
    esrp.tps_travail_manuel_janvier AS tps_travail_manuel_janvier_SDC,
    esrp.tps_travail_manuel_fevrier AS tps_travail_manuel_fevrier_SDC,
    esrp.tps_travail_manuel_mars AS tps_travail_manuel_mars_SDC,
    esrp.tps_travail_manuel_avril AS tps_travail_manuel_avril_SDC,
    esrp.tps_travail_manuel_mai AS tps_travail_manuel_mai_SDC,
    esrp.tps_travail_manuel_juin AS tps_travail_manuel_juin_SDC,
    esrp.tps_travail_manuel_juillet AS tps_travail_manuel_juillet_SDC,
    esrp.tps_travail_manuel_aout AS tps_travail_manuel_aout_SDC,
    esrp.tps_travail_manuel_septembre AS tps_travail_manuel_septembre_SDC,
    esrp.tps_travail_manuel_octobre AS tps_travail_manuel_octobre_SDC,
    esrp.tps_travail_manuel_novembre AS tps_travail_manuel_novembre_SDC,
    esrp.tps_travail_manuel_decembre AS tps_travail_manuel_decembre_SDC,
    esrp.qsa_tot AS quantite_mat_active_SDC,
    esrp.nbre_de_passages AS Nbre_inter_phyto_SDC,
    esrp.ges_carburants_total_ges_total AS GES_SDC,
    esrp.ges_carburants_directes_ges_total AS GES_directes_SDC,
    esrp.ges_carburants_directes_co2 AS Emissions_directes_Fuel_SDC,
    esrp.ges_ferti_min_directes_ges_total AS Emissions_directes_Ferti_SDC,
    esrp.ges_carburants_indirectes_ges_total AS GES_indirectes_SDC,
    esrp.ges_carburants_indirectes_co2 AS Emissions_indirectes_fuel_SDC,
    esrp.ges_ferti_min_indirectes_ges_total AS emissions_indirectes_engrais_SDC,
    esrp.ges_phyto_total_ges_total AS emissions_indirectes_phyto_SDC,
    esrp.alerte_ift_cible_mil_chim_tot_hts AS Alerte_IFT_SDC,
    esrp.alerte_msn_std_mil_avec_autoconso as Alerte_marge_SDC,
    esrp.alerte_pb_std_mil_avec_autoconso as Alerte_produit_SDC,
    esrp.alertes_charges as Alerte_charges_SDC,
    esrp.alerte_cm_std_mil as Alerte_charges_meca_SDC,
    esrp.alerte_ferti_n_tot as Alerte_ferti_azotee_SDC,
    esrp.alerte_co_irrigation_std_mil as Alerte_irrigation_SDC,
    esrp.recours_produits_toxiques_utilisateurs as nb_manip_produit_danger_SDC,
    esrp.recours_produits_danger_environnement as nb_manip_produit_danger_enviro_SDC,
    sdc.type_agriculture || '_' || etacr.typocan_assol as situation_production,
    esrp.co_tot_std_mil AS CO_std_mil_SDC,
    esrp.mb_reelle_sans_autoconso AS MB_reelle_sans_autoconso,
    esrp.mb_std_mil_avec_autoconso AS MB_std_ac_auto_SDC,
    esrp.msn_reelle_sans_autoconso AS MSN_reelle_sans_autoconso,
    esrp.msn_std_mil_avec_autoconso AS MSN_std_ac_auto_SDC,
    esrp.qsa_cmr AS quantite_mat_active_CMR_SDC,
    esrp.recours_produits_cmr AS Nb_intrant_CMR_SDC,
    --esrp.qsa_cmr AS nb_manip_produit_CMR_SDC, ???
    esrp.qsa_diflufenican AS qte_mat_active_diflufeni_SDC,
    esrp.qsa_mancozeb AS qte_mat_active_mancozebe_SDC,
    esrp.qsa_tebuconazole AS qte_mat_active_tebuco_SDC,
    esrp.qsa_bixafen AS qte_mat_active_bixafen_SDC,
    esrp.qsa_boscalid AS qte_mat_active_boscalid_SDC,
    esrp.qsa_dicamba AS qte_mat_active_dicamba_SDC,
    esrp.qsa_prosulfocarbe AS qte_mat_active_prosulfo_SDC,
    esrp.qsa_smetolachlore AS qte_mat_active_smethola_SDC,
    esrp.co_phyto_sans_amm_reelles AS CO_reelles_phytos_SDC,
    esrp.co_fertimin_reel AS CO_reelles_ferti_min_SDC,
    esrp.co_epandage_orga_reelles AS CO_reelles_ferti_orga_SDC,
    esrp.co_irrigation_reelles AS CO_reelles_irrig_SDC,
    esrp.co_semis_reel AS CO_reelles_semences_SDC,
    esrp.co_intrants_autres_reelles AS CO_reelles_autres_SDC,
    esrp.co_phyto_avec_amm_reelles AS CO_reelles_lutte_bio_SDC, 
    sdc.type_agriculture || '_' || etacr.typocan_assol || '_' || COALESCE(TEXT(sdc.campagne), TEXT('sans_campagne')) as situation_production_mill,
	sdc.codes_convention_dephy as codes_convention_dephy,
	esrp.recours_aux_moyens_biologiques as rec_moyens_biologiques_SDC,
	esrp.recours_macroorganismes as recours_magroorganismes_SDC,
	esrp.recours_produits_biotiques_sansamm as recours_pdts_biot_sansamm_SDC,
	esrp.recours_produits_abiotiques_sansamm as recours_ptds_abiot_sansamm_SDC
FROM entrepot_sdc sdc
LEFT JOIN entrepot_dispositif  dispo ON dispo.id = sdc.dispositif_id
LEFT JOIN entrepot_domaine     dom   ON dom.id   = dispo.domaine_id
LEFT JOIN entrepot_commune    comm   ON dom.commune_id = comm.id
left join entrepot_entite_unique_par_sdc_nettoyage eeupsn on sdc.id = eeupsn.sdc_id
left join entrepot_reseaux_rattachement_sdc_outils_tableau_de_bord_can errsotdbc on sdc.id = errsotdbc.id 
left join entrepot_sdc_realise_outils_tableau_de_bord_can esrotdbc on sdc.id = esrotdbc.id
left join entrepot_typologie_assol_can_realise etacr on etacr.sdc_id = sdc.id
left join entrepot_stc_sdc_realise_outils_tableau_de_bord_can essrotdbc on sdc.id = essrotdbc.id
left join entrepot_sdc_realise_performance esrp on sdc.id = esrp.sdc_id 
WHERE (sdc.filiere = 'GRANDES_CULTURES' or sdc.filiere = 'POLYCULTURE_ELEVAGE')
and eeupsn.entite_retenue = 'realise_retenu'
and not dispo.type = 'NOT_DEPHY'
UNION
SELECT
    COALESCE(sdc.code_dephy, 'CODE_DEPHY_ABSENT') || '_' || sdc.campagne
        AS id_code_dephy_campagne,
    sdc.code_dephy as sdc_code_dephy,
    sdc.campagne as campagne_donnees,
    dispo."type" as dispositif_type,
    errsotdbc.reseaux_ir as reseaux_ir,
    errsotdbc.reseaux_it as reseaux_it,
    dom.id as domaine_id,
    dom.nom as domaine_nom,
    dom.departement as departement,
    dom.sau_totale as sau_domaine,
    dom.campagne as domaine_campagne,
    'synthétisé' as approche_de_calcul,
    sdc.id as sdc_id,
    sdc.nom as sdc_nom, 
    sdc.part_sau_domaine as sdc_part_sau_domaine, 
    esusotdb.surface as surface_sdc,
    sdc.type_agriculture as sdc_type_agriculture,
    sdc.type_production as sdc_type_production,
    synthetise.id as systeme_synthetise_id,
    synthetise.nom as systeme_synthetise_nom,
    synthetise.campagnes as systeme_synthetise_campagnes,
    etcrs.typocan_rotation as typo_rotation,
    etcrs.nb_culture_synthetise as nb_culture_sdc,
    essotdbc.surface_betterave as surface_Betterave_SDC,
	essotdbc.surface_cereale_a_paille_printemps as surface_CaP_Printemps_SDC,
	essotdbc.surface_cereale_a_paille_hiver as surface_CaP_hiver_SDC,
	essotdbc.surface_colza as surface_Colza_SDC,
	essotdbc.surface_legume as surface_Leg_plein_champ_SDC,
	essotdbc.surface_lin as surface_Lin_fibre_SDC,
	essotdbc.surface_mais as surface_Mais_Sorgho_SDC,
	essotdbc.surface_melange_fourrager as surface_Mel_Fourrage_SDC,
	essotdbc.surface_oleagineux as surface_Olea_SDC,
	essotdbc.surface_pomme_de_terre as surface_Pdt_SDC,
	essotdbc.surface_porte_graine as surface_porte_graine_SDC,
	essotdbc.surface_prairie_temporaire as surface_Prairie_Temp_SDC,
	essotdbc.surface_proteagineux as surface_Protea_SDC,
	essotdbc.surface_tournesol as surface_Tournesol_SDC,
	essotdbc.surface_autre as surface_autre_SDC, 
	essp.mb_reelle_avec_autoconso as MB_reelle_ac_auto_SDC,
	essp.msn_reelle_avec_autoconso as MSN_relle_ac_auto_SDC,
	essp.pb_reel_avec_autoconso as pb_reel_avec_autoconso,
	essp.co_tot_reelles as CO_reelles_SDC,
	essp.cm_reelles as CM_reelles_SDC,
	essp.conso_carburant as conso_carburant_SDC,
	essp.c_main_oeuvre_tractoriste_std_mil as cout_mo_tractoriste,
	essp.c_main_oeuvre_manuelle_std_mil as cout_mo_manuelle,
	essp.nombre_uth_necessaires as nbre_uth_sdc,
	essp.nbre_de_passages_labour as freq_labour_SDC,
	essp.nbre_de_passages_tcs as freq_trava_sol_hors_labour_SDC,
	essp.type_de_travail_du_sol as type_travail_sol_SDC,
	essp.utili_desherbage_meca as desherbage_mecanique_SDC,
	essp.nbre_de_passages_desherbage_meca as freq_desh_meca_SDC,
    essp.ift_cible_non_mil_chimique_tot AS ift_cible_non_mil_chim_tot_SDC,
    essp.ift_cible_non_mil_chim_tot_hts AS ift_cible_non_mil_chim_tot_hts_SDC,
    essp.ift_cible_non_mil_biocontrole AS ift_cible_nonmil_biocontrole_SDC,
    essp.ift_cible_non_mil_h AS ift_cible_non_mil_h_SDC,
    essp.ift_cible_non_mil_hh AS ift_cible_non_mil_hh_SDC,
    essp.ift_cible_non_mil_f AS ift_cible_non_mil_f_SDC,
    essp.ift_cible_non_mil_i AS ift_cible_non_mil_i_SDC,
    essp.ift_cible_non_mil_a AS ift_cible_non_mil_a_SDC,
    essp.ift_cible_non_mil_ts AS ift_cible_non_mil_ts_SDC,
    null as ift_norme_sdc, -- TODO
    null as IFT_Hors_TS_Moy_Region, -- TODO
    essp.qsa_tot AS quantite_mat_active_SDC,
    essp.qsa_toxique_utilisateur AS quantite_mat_active_danger_SDC,
    essp.qsa_danger_environnement AS qte_mat_active_danger_env_SDC,
    essp.qsa_glyphosate AS quantite_mat_active_glypho_SDC,
    essp.qsa_neonicotinoides AS quantite_mat_active_neonic_SDC,
    essp.qsa_cuivre_metal_tot AS qte_cuivre_SDC,
    essp.qsa_cuivre_metal_ferti AS qte_cuivre_engrais_SDC,
    essp.qsa_cuivre_metal_phyto AS qte_cuivre_phyto_SDC,
    essp.qsa_soufre_tot AS qte_soufre_SDC,
    essp.qsa_soufre_ferti AS qte_soufre_engrais_SDC,
    essp.qsa_soufre_phyto AS qte_soufre_phyto_SDC,
    essp.ferti_n_tot AS N_SDC,
    essp.ferti_n_mineral AS N_Mineral_SDC,
    essp.ferti_n_organique AS N_Orga_SDC,
    essp.ferti_p2o5_tot AS P_SDC,
    essp.ferti_p2o5_mineral AS P_Mineral_SDC,
    essp.ferti_p2o5_organique AS P_Orga_SDC,
    essp.ferti_k2o_tot AS K_SDC,
    essp.ferti_k2o_mineral AS K_Mineral_SDC,
    essp.ferti_k2o_organique AS K_Orga_SDC,
    essp.conso_eau AS Qte_Eau_mm_ha_SDC,
    essp.tps_utilisation_materiel AS tps_util_materiel_SDC,
    essp.tps_utilisation_materiel_janvier AS tps_util_materiel_janvier_SDC,
    essp.tps_utilisation_materiel_fevrier AS tps_util_materiel_fevrier_SDC,
    essp.tps_utilisation_materiel_mars AS tps_util_materiel_mars_SDC,
    essp.tps_utilisation_materiel_avril AS tps_util_materiel_avril_SDC,
    essp.tps_utilisation_materiel_mai AS tps_util_materiel_mai_SDC,
    essp.tps_utilisation_materiel_juin AS tps_util_materiel_juin_SDC,
    essp.tps_utilisation_materiel_juillet AS tps_util_materiel_juillet_SDC,
    essp.tps_utilisation_materiel_aout AS tps_util_materiel_aout_SDC,
    essp.tps_utilisation_materiel_sept AS tps_util_materiel_sept_SDC,
    essp.tps_utilisation_materiel_oct AS tps_util_materiel_oct_SDC,
    essp.tps_utilisation_materiel_nov AS tps_util_materiel_nov_SDC,
    essp.tps_utilisation_materiel_dec AS tps_util_materiel_dec_SDC,
    essp.tps_travail_manuel AS tps_travail_manuel_SDC,
    essp.tps_travail_manuel_janvier AS tps_travail_manuel_janvier_SDC,
    essp.tps_travail_manuel_fevrier AS tps_travail_manuel_fevrier_SDC,
    essp.tps_travail_manuel_mars AS tps_travail_manuel_mars_SDC,
    essp.tps_travail_manuel_avril AS tps_travail_manuel_avril_SDC,
    essp.tps_travail_manuel_mai AS tps_travail_manuel_mai_SDC,
    essp.tps_travail_manuel_juin AS tps_travail_manuel_juin_SDC,
    essp.tps_travail_manuel_juillet AS tps_travail_manuel_juillet_SDC,
    essp.tps_travail_manuel_aout AS tps_travail_manuel_aout_SDC,
    essp.tps_travail_manuel_septembre AS tps_travail_manuel_septembre_SDC,
    essp.tps_travail_manuel_octobre AS tps_travail_manuel_octobre_SDC,
    essp.tps_travail_manuel_novembre AS tps_travail_manuel_novembre_SDC,
    essp.tps_travail_manuel_decembre AS tps_travail_manuel_decembre_SDC,
    essp.qsa_tot AS quantite_mat_active_SDC,
    essp.nbre_de_passages AS Nbre_inter_phyto_SDC,
    essp.ges_carburants_total_ges_total AS GES_SDC,
    essp.ges_carburants_directes_ges_total AS GES_directes_SDC,
    essp.ges_carburants_directes_co2 AS Emissions_directes_Fuel_SDC,
    essp.ges_ferti_min_directes_ges_total AS Emissions_directes_Ferti_SDC,
    essp.ges_carburants_indirectes_ges_total AS GES_indirectes_SDC,
    essp.ges_carburants_indirectes_co2 AS Emissions_indirectes_fuel_SDC,
    essp.ges_ferti_min_indirectes_ges_total AS emissions_indirectes_engrais_SDC,
    essp.ges_phyto_total_ges_total AS emissions_indirectes_phyto_SDC,
    essp.alerte_ift_cible_mil_chim_tot_hts AS Alerte_IFT_SDC,
    essp.alerte_msn_std_mil_avec_autoconso as Alerte_marge_SDC,
    essp.alerte_pb_std_mil_avec_autoconso as Alerte_produit_SDC,
    essp.alertes_charges as Alerte_charges_SDC,
    essp.alerte_cm_std_mil as Alerte_charges_meca_SDC,
    essp.alerte_ferti_n_tot as Alerte_ferti_azotee_SDC,
    essp.alerte_co_irrigation_std_mil as Alerte_irrigation_SDC,
    essp.recours_produits_toxiques_utilisateurs as nb_manip_produit_danger_SDC,
    essp.recours_produits_danger_environnement as nb_manip_produit_danger_enviro_SDC,
    sdc.type_agriculture || '_' || etcrs.typocan_rotation as situation_production,
    essp.co_tot_std_mil AS CO_std_mil_SDC,
    essp.mb_reelle_sans_autoconso AS MB_reelle_sans_autoconso,
    essp.mb_std_mil_avec_autoconso AS MB_std_ac_auto_SDC,
    essp.msn_reelle_sans_autoconso AS MSN_reelle_sans_autoconso,
    essp.msn_std_mil_avec_autoconso AS MSN_std_ac_auto_SDC,
    essp.qsa_cmr AS quantite_mat_active_CMR_SDC,
    essp.recours_produits_cmr AS Nb_intrant_CMR_SDC,
    --essp.qsa_cmr AS nb_manip_produit_CMR_SDC, ???
    essp.qsa_diflufenican AS qte_mat_active_diflufeni_SDC,
    essp.qsa_mancozeb AS qte_mat_active_mancozebe_SDC,
    essp.qsa_tebuconazole AS qte_mat_active_tebuco_SDC,
    essp.qsa_bixafen AS qte_mat_active_bixafen_SDC,
    essp.qsa_boscalid AS qte_mat_active_boscalid_SDC,
    essp.qsa_dicamba AS qte_mat_active_dicamba_SDC,
    essp.qsa_prosulfocarbe AS qte_mat_active_prosulfo_SDC,
    essp.qsa_smetolachlore AS qte_mat_active_smethola_SDC,
    essp.co_phyto_sans_amm_reelles AS CO_reelles_phytos_SDC,
    essp.co_fertimin_reel AS CO_reelles_ferti_min_SDC,
    essp.co_epandage_orga_reelles AS CO_reelles_ferti_orga_SDC,
    essp.co_irrigation_reelles AS CO_reelles_irrig_SDC,
    essp.co_semis_reel AS CO_reelles_semences_SDC,
    essp.co_intrants_autres_reelles AS CO_reelles_autres_SDC,
    essp.co_phyto_avec_amm_reelles AS CO_reelles_lutte_bio_SDC, 
    sdc.type_agriculture || '_' || etcrs.typocan_rotation || '_' || COALESCE(TEXT(sdc.campagne), TEXT('sans_campagne')) as situation_production_mill,
	sdc.codes_convention_dephy as codes_convention_dephy,
	essp.recours_aux_moyens_biologiques as rec_moyens_biologiques_SDC,
	essp.recours_macroorganismes as recours_magroorganismes_SDC,
	essp.recours_produits_biotiques_sansamm as recours_pdts_biot_sansamm_SDC,
	essp.recours_produits_abiotiques_sansamm as recours_ptds_abiot_sansamm_SDC
FROM entrepot_synthetise synthetise 
LEFT JOIN entrepot_sdc sdc on synthetise.sdc_id = sdc.id
LEFT JOIN entrepot_dispositif  dispo ON dispo.id = sdc.dispositif_id
LEFT JOIN entrepot_domaine     dom   ON dom.id   = dispo.domaine_id
LEFT JOIN entrepot_commune    comm   ON dom.commune_id = comm.id
left join entrepot_entite_unique_par_sdc_nettoyage eeupsn on sdc.id = eeupsn.sdc_id
left join entrepot_reseaux_rattachement_sdc_outils_tableau_de_bord_can errsotdbc on sdc.id = errsotdbc.id 
left join entrepot_stc_synthetise_outils_tableau_de_bord_can essotdbc on essotdbc.id = synthetise.id
left join entrepot_surface_synthetise_outils_tableau_de_bord_can esusotdb on esusotdb.id = synthetise.id
left join entrepot_typologie_can_rotation_synthetise etcrs on etcrs.synthetise_id = synthetise.id
--left join entrepot_stc_sdc_realise_outils_tableau_de_bord_can essrotdbc on sdc.id = essrotdbc.id
left join entrepot_synthetise_synthetise_performance essp on synthetise.id = essp.synthetise_id
WHERE (sdc.filiere = 'GRANDES_CULTURES' or sdc.filiere = 'POLYCULTURE_ELEVAGE')
and eeupsn.entite_retenue != 'realise_retenu'
and not dispo.type = 'NOT_DEPHY';