-- SCRIPT SQL POUR LE TRAITEMENT DES DONNÉES MARAÎCHÈRES (maraich_var.csv)
-- Inspiré de sdc_gcpe.sql et aligné sur les colonnes de maraich_var.csv
SELECT
    -- Identification unique du SDC et de la campagne
    COALESCE(sdc.code_dephy, 'CODE_DEPHY_ABSENT') || '_' || sdc.campagne
        AS ID_CODE_DEPHY_CAMPAGNE,
    sdc.code_dephy AS sdc_code_dephy,
    sdc.campagne AS campagne_donnees,
    -- Dispositif et réseaux
    dispo."type" AS dispositif_type,
    errsotdbc.reseaux_it AS reseaux_it,
    errsotdbc.reseaux_ir AS reseau_ir,
    -- Domaine et localisation
    dom.id AS domaine_id,
    dom.nom AS domaine_nom,
    dom.departement AS departement,
    comm.departement AS Nom_Departement, 
    comm.region AS Nom_Region,    
    comm.ancienne_region AS Nom_Ancienne_Region,
    dom.sau_totale AS sau_domaine,
    dom.campagne AS domaine_campagne,
    -- Filière et approche
    'MARAICHAGE' AS sdc_filiere,  -- Filière fixe pour ce script
    'réalisé' AS approche_de_calcul,
    sdc.id AS sdc_id,
    sdc.nom AS sdc_nom,
    sdc.part_sau_domaine AS sdc_part_sau_domaine,
    null AS surface_theorique_SDC,
    null AS sdc_valide,            
    -- Type d'agriculture et système synthétisé
    sdc.type_agriculture AS sdc_type_agriculture,
    null AS systeme_synthetise_id,      -- À remplir si applicable
    null AS systeme_synthetise_nom,      -- Idem
    null AS systeme_synthetise_campagnes,
    null AS systeme_synthetise_validation,
    -- Données économiques et techniques
    esrp.mb_reelle_avec_autoconso AS MB_reelle_ac_auto_SDC,
    esrp.msn_reelle_avec_autoconso AS MSN_relle_ac_auto_SDC,
    esrp.pb_reel_avec_autoconso AS pb_reel_avec_autoconso,
    esrp.co_tot_reelles AS CO_reelles_SDC,
    esrp.cm_reelles AS CM_reelles_SDC,
    esrp.conso_carburant AS conso_carburant_SDC,
    esrp.c_main_oeuvre_tractoriste_std_mil AS cout_mo_tractoriste,
    esrp.c_main_oeuvre_manuelle_std_mil AS cout_mo_manuelle,
    esrp.nombre_uth_necessaires AS nbre_uth_sdc,
    -- IFT et alertes (maraîchage)
    esrp.ift_cible_non_mil_chimique_tot AS ift_cible_non_mil_chim_tot_SDC,
    esrp.ift_cible_non_mil_chim_tot_hts AS ift_cible_non_mil_chim_tot_hts_SDC,
    esrp.ift_cible_non_mil_biocontrole AS ift_cible_non_mil_biocontrole_SDC,
    esrp.ift_cible_non_mil_h AS ift_cible_non_mil_h_SDC,
    esrp.ift_cible_non_mil_hh AS ift_cible_non_mil_hh_SDC,
    esrp.ift_cible_non_mil_f AS ift_cible_non_mil_f_SDC,
    esrp.ift_cible_non_mil_i AS ift_cible_non_mil_i_SDC,
    esrp.ift_cible_non_mil_a AS ift_cible_non_mil_a_SDC,
    esrp.ift_cible_non_mil_ts AS ift_cible_non_mil_ts_SDC,
    esrp.ift_cible_non_mil_hh AS ift_cible_non_mil_hh_hors_TS_SDC,
    null AS Alerte_IFT_total_SDC,         -- À vérifier dans les tables
    null AS Alerte_Absence_unite_dose_SDC,
    null AS alerte_description_rotation,
    null AS alerte_nb_ITK_vide_SdC,
    null AS Alerte_Nb_ITK_sans_ferti,
    null AS Alerte_Nb_ITK_sans_semis,
    null AS Alerte_Nb_ITK_sans_recolte,
    null AS Alerte_Nb_ITK_sans_w_sol,
    null AS Alerte_Nb_ITK_verif_biocontrole,
    null AS Synthese_alertes,
    null AS surface_sdc_itk,
    null AS alerte_renseignement_donnees,
    sdc.type_agriculture AS AB_CONV,
    -- Quantités de matières actives (maraîchage)
    esrp.qsa_tot AS quantite_mat_active_SDC,
    esrp.qsa_toxique_utilisateur AS quantite_mat_active_danger_SDC,
    esrp.qsa_danger_environnement AS qte_mat_active_danger_env_SDC,
    esrp.qsa_glyphosate AS quantite_mat_active_glypho_SDC,
    esrp.qsa_neonicotinoides AS quantite_mat_active_neonic_SDC,
    esrp.qsa_cuivre_metal_tot AS qte_cuivre_SDC,
    esrp.qsa_cuivre_metal_ferti AS qte_cuivre_engrais_SDC,
    esrp.qsa_cuivre_metal_phyto AS qte_cuivre_phyto_SDC,
    esrp.qsa_soufre_tot AS qte_soufre_SDC,
    esrp.qsa_soufre_ferti AS qte_soufre_engrais_SDC,
    esrp.qsa_soufre_phyto AS qte_soufre_phyto_SDC,
    -- Fertilisation (azote, phosphore, potassium)
    esrp.ferti_n_tot AS N_SDC,
    esrp.ferti_n_mineral AS N_Mineral_SDC,
    esrp.ferti_n_organique AS N_Orga_SDC,
    esrp.ferti_p2o5_tot AS P_SDC,
    esrp.ferti_p2o5_mineral AS P_Mineral_SDC,
    esrp.ferti_p2o5_organique AS P_Orga_SDC,
    esrp.ferti_k2o_tot AS K_SDC,
    esrp.ferti_k2o_mineral AS K_Mineral_SDC,
    esrp.ferti_k2o_organique AS K_Orga_SDC,
    -- Eau et temps de travail
    esrp.conso_eau AS Qte_Eau_mm_ha_SDC,
    esrp.tps_utilisation_materiel AS tps_util_materiel_SDC,
    -- Temps mensuels (janvier à décembre)
    esrp.tps_utilisation_materiel_janvier AS tps_util_materiel_janvier_SDC,
    esrp.tps_utilisation_materiel_fevrier AS tps_util_materiel_fevrier_SDC,
    esrp.tps_utilisation_materiel_mars AS tps_util_materiel_mars_SDC,
    esrp.tps_utilisation_materiel_avril AS tps_util_materiel_avril_SDC,
    esrp.tps_utilisation_materiel_mai AS tps_util_materiel_mai_SDC,
    esrp.tps_utilisation_materiel_juin AS tps_util_materiel_juin_SDC,
    esrp.tps_utilisation_materiel_juillet AS tps_util_materiel_juillet_SDC,
    esrp.tps_utilisation_materiel_aout AS tps_util_materiel_aout_SDC,
    esrp.tps_utilisation_materiel_sept AS tps_util_materiel_sept_SDC,
    esrp.tps_utilisation_materiel_oct AS tps_util_materiel_oct_SDC,
    esrp.tps_utilisation_materiel_nov AS tps_util_materiel_nov_SDC,
    esrp.tps_utilisation_materiel_dec AS tps_util_materiel_dec_SDC,
    -- Temps de travail manuel (janvier à décembre)
    esrp.tps_travail_manuel AS tps_travail_manuel_SDC,
    esrp.tps_travail_manuel_janvier AS tps_travail_manuel_janvier_SDC,
    esrp.tps_travail_manuel_fevrier AS tps_travail_manuel_fevrier_SDC,
    esrp.tps_travail_manuel_mars AS tps_travail_manuel_mars_SDC,
    esrp.tps_travail_manuel_avril AS tps_travail_manuel_avril_SDC,
    esrp.tps_travail_manuel_mai AS tps_travail_manuel_mai_SDC,
    esrp.tps_travail_manuel_juin AS tps_travail_manuel_juin_SDC,
    esrp.tps_travail_manuel_juillet AS tps_travail_manuel_juillet_SDC,
    esrp.tps_travail_manuel_aout AS tps_travail_manuel_aout_SDC,
    esrp.tps_travail_manuel_septembre AS tps_travail_manuel_septembre_SDC,
    esrp.tps_travail_manuel_octobre AS tps_travail_manuel_octobre_SDC,
    esrp.tps_travail_manuel_novembre AS tps_travail_manuel_novembre_SDC,
    esrp.tps_travail_manuel_decembre AS tps_travail_manuel_decembre_SDC,
    -- GES et énergie
    esrp.ges_carburants_total_ges_total AS GES_SDC,
    esrp.ges_carburants_directes_ges_total AS GES_directes_SDC,
    esrp.ges_carburants_directes_co2 AS Emissions_directes_Fuel_SDC,
    esrp.ges_ferti_min_directes_ges_total AS Emissions_directes_Ferti_SDC,
    esrp.ges_carburants_indirectes_ges_total AS GES_indirectes_SDC,
    esrp.ges_carburants_indirectes_co2 AS Emissions_indirectes_fuel_SDC,
    esrp.ges_ferti_min_indirectes_ges_total AS emissions_indirectes_engrais_SDC,
    esrp.ges_phyto_total_ges_total AS emissions_indirectes_phyto_SDC,
    esrp.energie_totale_directes + esrp.energie_totale_indirectes AS NRJ_SDC,                     -- Énergie totale
    esrp.energie_carburants_directes + esrp.energie_carburants_indirectes AS Energie_Fuel_SDC,            -- Idem
    esrp.energie_ferti_min + esrp.energie_ferti_orga AS energie_indirecte_engrais_SDC,
    esrp.energie_phyto AS energie_indirecte_phyto_SDC,
    esrp.energie_totale_indirectes AS NRJ_indirecte_SDC,
    -- Variables spécifiques au maraîchage
   	esrp.recours_produits_danger_environnement AS Nb_intrant_dang_env_SDC,
    sdc.type_production AS situation_production,
    esrp.co_tot_std_mil AS CO_std_mil_SDC,
    esrp.mb_reelle_sans_autoconso AS MB_reelle_sans_autoconso,
    esrp.msn_reelle_sans_autoconso AS MSN_reelle_sans_autoconso,
    esrp.qsa_cmr AS quantite_mat_active_CMR_SDC,
    esrp.recours_produits_cmr AS Nb_intrant_CMR_SDC,
    null AS nb_manip_produit_CMR_SDC,
    esrp.qsa_diflufenican AS qte_mat_active_diflufeni_SDC,
    esrp.qsa_mancozeb AS qte_mat_active_mancozebe_SDC,
    esrp.qsa_tebuconazole AS qte_mat_active_tebuco_SDC,
    esrp.qsa_bixafen AS qte_mat_active_bixafen_SDC,
    esrp.qsa_boscalid AS qte_mat_active_boscalid_SDC,
    esrp.qsa_dicamba AS qte_mat_active_dicamba_SDC,
    esrp.qsa_prosulfocarbe AS qte_mat_active_prosulfo_SDC,
    esrp.qsa_smetolachlore AS qte_mat_active_smethola_SDC,
    -- Coûts par poste
    esrp.co_phyto_sans_amm_reelles AS CO_reelles_phytos_SDC,
    esrp.co_fertimin_reel AS CO_reelles_ferti_min_SDC,
    esrp.co_epandage_orga_reelles AS CO_reelles_ferti_orga_SDC,
    esrp.co_irrigation_reelles AS CO_reelles_irrig_SDC,
    esrp.co_semis_reel AS CO_reelles_semences_SDC,
    esrp.co_intrants_autres_reelles AS CO_reelles_autres_SDC,
    esrp.co_phyto_avec_amm_reelles AS CO_reelles_lutte_bio_SDC,
    -- Situation de production détaillée
    sdc.type_agriculture || '_' || comm.bassin_vie || '_' || COALESCE(TEXT(sdc.campagne), TEXT('sans_campagne')) AS situation_production_mill,
    sdc.codes_convention_dephy AS codes_convention_dephy,
    -- Recours aux moyens biologiques
    esrp.recours_aux_moyens_biologiques AS rec_moyens_biologiques_SDC,
    esrp.recours_macroorganismes AS recours_macroorganismes_SDC,
    esrp.recours_produits_biotiques_sansamm AS recours_pdts_biot_sansamm_SDC,
    esrp.recours_produits_abiotiques_sansamm AS recours_ptds_abiot_sansamm_SDC,
    null AS MED_surface_sdc,             -- Si applicable
    null AS MED_ift_histo_chimique_tot_SDC,
    null AS MED_ift_histo_h_SDC,
    null AS MED_ift_histo_f_SDC,
    null AS MED_ift_histo_i_SDC,
    null AS MED_ift_histo_biocontrole_SDC,
    null AS MED_ift_histo_a_SDC,
    null AS MED_ift_histo_ts_SDC,
    null AS MED_ift_histo_hh_SDC,
    null AS MED_quantite_mat_active_intrant,
    null AS MED_qte_mat_active_danger_SDC,
    null AS MED_qte_mat_active_danger_env,
    null AS MED_quantite_cuivre_SDC,
    null AS MED_qte_cuivre_phyto_SDC,
    null AS MED_qte_cuivre_engrais_SDC,
    null AS MED_quantite_soufre_SDC,
    null AS MED_qte_soufre_phyto_SDC,
    null AS MED_qte_soufre_engrais_SDC,
    null AS MED_qte_mat_active_glypho_SDC,
    null AS MED_qte_mat_active_neonic_SDC,
    null AS MED_ift_histo_rec_moy_bio_SDC,
    null AS MED_Nb_intrant_dang_SDC,
    null AS MED_Nb_intrant_danger_enviro_SDC,
    null AS MED_MSN_relle_ac_auto_SDC,
    null AS MED_pb_reel_avec_autoconso,
    null AS MED_CO_reelles_SDC,
    null AS MED_CO_std_mil_SDC,
    null AS MED_CM_reelles_SDC,
    null AS MED_cout_mo_tractoriste,
    null AS MED_cout_mo_manuelle,
    null AS MED_GES_SDC,
    null AS MED_GES_directes_SDC,
    null AS MED_GES_indirectes_SDC,
    null AS MED_Emissions_directes_Fuel_SDC,
    null AS MED_emissions_indir_fuel_SDC,
    null AS MED_Emissions_directes_Ferti_SDC,
    null AS MED_emissions_indir_engrais_SDC,
    null AS MED_emissions_indir_phyto_SDC,
    null AS MED_N_SDC,
    null AS MED_N_Mineral_SDC,
    null AS MED_N_Orga_SDC,
    null AS MED_P_SDC,
    null AS MED_P_Mineral_SDC,
    null AS MED_P_Orga_SDC,
    null AS MED_K_SDC,
    null AS MED_K_Mineral_SDC,
    null AS MED_K_Orga_SDC,
    null AS MED_NRJ_SDC,
    null AS MED_energie_indirecte_phyto_SDC,
    null AS MED_energie_indir_engrais_SDC,
    null AS MED_Energie_Fuel_SDC,
    null AS MED_NRJ_indirecte_SDC,
    null AS MED_conso_carburant_SDC,
    null AS MED_Qte_Eau_SDC_mm_ha,
    null AS MED_MB_reelle_ac_auto_SDC,
    null AS MED_tps_travail_manuel,
    -- Temps mensuels MED (si applicable)
    null AS MED_tps_travail_manuel_janvier,
    null AS MED_tps_travail_manuel_fevrier,
    -- ... (compléter pour tous les mois)
    null AS MED_tps_util_materiel,
    -- Temps mensuels MED pour le matériel (si applicable)
    null AS MED_tps_util_materiel_janvier,
    -- ... (compléter pour tous les mois)
    null AS MED_complexite_SDC,
    null AS MED_nbre_uth_sdc,
    null AS MED_cout_mo_totale,
    null AS MED_cout_totale,
    null AS MED_emissions_fioul,
    null AS MED_emissions_engrais,
    null AS MED_tps_total,
    -- Temps mensuels MED totaux (si applicable)
    null AS MED_tps_total_janv,
    -- ... (compléter pour tous les mois)
    null AS MED_MB_std_ac_auto_SDC,
    null AS MED_MSN_std_ac_auto_SDC,
    null AS MED_quantite_mat_active_CMR_SDC,
    null AS MED_Nb_intrant_CMR_SDC,
    null AS MED_ift_histo_chim_tot_hts_SDC,
    null AS MED_ift_histo_hh_hors_TS_SDC,
    null AS MED_ift_cible_non_mil_chimiq_tot,
    null AS MED_ift_cible_tot_hts_SDC,
    null AS MED_ift_cible_non_mil_biocontrol,
    null AS MED_ift_cible_non_mil_h_SDC,
    null AS MED_ift_cible_non_mil_hh_SDC,
    null AS MED_ift_cible_hh_hors_TS_SDC,
    null AS MED_ift_cible_non_mil_f_SDC,
    null AS MED_ift_cible_non_mil_i_SDC,
    null AS MED_ift_cible_non_mil_a_SDC,
    null AS MED_ift_cible_non_mil_ts_SDC,
    null AS MED_qte_mat_active_bixafen_SDC,
    null AS MED_qte_mat_active_boscalid_SDC,
    null AS MED_qte_mat_active_dicamba_SDC,
    null AS MED_qte_mat_active_diflufeni_SDC,
    null AS MED_qte_mat_active_mancozebe_SDC,
    null AS MED_qte_mat_active_prosulfo_SDC,
    null AS MED_qte_mat_active_smethola_SDC,
    null AS MED_qte_mat_active_tebuco_SDC,
    null AS MED_rec_moyens_biologiques_SDC,
    null AS MED_recours_macroorganismes_SDC,
    null AS MED_rec_pdts_biot_sansamm_SDC,
    null AS MED_rec_pdts_abiot_sansamm_SDC
FROM entrepot_sdc sdc
LEFT JOIN entrepot_dispositif dispo ON dispo.id = sdc.dispositif_id
LEFT JOIN entrepot_domaine dom ON dom.id = dispo.domaine_id
LEFT JOIN entrepot_commune comm ON dom.commune_id = comm.id
LEFT JOIN entrepot_entite_unique_par_sdc_nettoyage eeupsn ON sdc.id = eeupsn.sdc_id
LEFT JOIN entrepot_reseaux_rattachement_sdc_outils_tableau_de_bord_can errsotdbc ON sdc.id = errsotdbc.id
LEFT JOIN entrepot_sdc_realise_outils_tableau_de_bord_can esrotdbc ON sdc.id = esrotdbc.id
LEFT JOIN entrepot_sdc_realise_performance esrp ON sdc.id = esrp.sdc_id
WHERE sdc.filiere = 'MARAICHAGE'  -- Filtre spécifique à la filière maraîchage
AND eeupsn.entite_retenue = 'realise_retenu'
AND NOT dispo.type = 'NOT_DEPHY';
