-- En réalisé
select 
	errd.mode_saisie,
    errd.recolte_id,
    errd.recolte_rendement,
    errd.recolte_unite,
    errd.composant_culture_id,
    errd.espece_id,
    errd.espece_code_botanique,
    errd.espece_libelle_botanique,
    errd.espece_code_qualifiant_aee, 
    errd.espece_libelle_qualifiant_aee,
    errd.espece_code_type_saisonnier_aee,
    errd.espece_libelle_type_saisonnier_aee,
    errd.espece_code_destination_aee,
    errd.espece_libelle_destination_aee,
    errd.espece_typo_can,
    errd.variete_id,
    errd.variete_libelle, 
    errd.culture_id,
    errd.culture_nom,
    errd.culture_est_melange_especes, 
    errd.culture_est_melange_varietes,
    errd.culture_typo_can_sans_compagne,
    errd.culture_typo_can_espece,
    errd.culture_typo_can_espece_sans_compagne,
    errd.culture_typo_can_nbre_composant,
    errd.culture_typo_can_nbre_espece,
    errd.action_id,
    errd.action_type,
    errd.intervention_date_debut,
    errd.intervention_date_fin,
    errd.intervention_type,
    errd.intervention_id,
    errd.noeud_id,
    errd.connexion_id
from entrepot_rendement_realise_dirodur errd
join entrepot_itk_filtre eif on (errd.noeud_id = eif.noeuds_realise_id and errd.culture_id = eif.culture_id)
union all
select
	ersd.mode_saisie,
    ersd.recolte_id,
    ersd.recolte_rendement,
    ersd.recolte_unite,
    ersd.composant_culture_id,
    ersd.espece_id,
    ersd.espece_code_botanique,
    ersd.espece_libelle_botanique,
    ersd.espece_code_qualifiant_aee, 
    ersd.espece_libelle_qualifiant_aee,
    ersd.espece_code_type_saisonnier_aee,
    ersd.espece_libelle_type_saisonnier_aee,
    ersd.espece_code_destination_aee,
    ersd.espece_libelle_destination_aee,
    ersd.espece_typo_can,
    ersd.variete_id,
    ersd.variete_libelle, 
    ersd.culture_id,
    ersd.culture_nom,
    ersd.culture_est_melange_especes, 
    ersd.culture_est_melange_varietes,
    ersd.culture_typo_can_sans_compagne,
    ersd.culture_typo_can_espece,
    ersd.culture_typo_can_espece_sans_compagne,
    ersd.culture_typo_can_nbre_composant,
    ersd.culture_typo_can_nbre_espece,
    ersd.action_id,
    ersd.action_type,
    ersd.intervention_date_debut,
    ersd.intervention_date_fin,
    ersd.intervention_type,
    ersd.intervention_id,
    ersd.noeud_id,
    ersd.connexion_id
from entrepot_rendement_synthetise_dirodur ersd
join entrepot_itk_filtre eif on (ersd.connexion_id = eif.connection_synthetise_id);


