SELECT
    sdc_numero_dephy as sdc_numero_dephy,
    etat_temporel as sdc_etat_temporel,
    STRING_AGG(CAST(domaine_campagne AS TEXT), ', ' ORDER BY domaine_campagne) AS sdc_ag_temp_campagne_domaine,
    STRING_AGG(synthetise_campagnes_unnested, ', ' ORDER BY synthetise_campagnes_unnested) AS sdc_ag_temp_campagnes_synthetise,
    COUNT(*) AS sdc_ag_temp_nb_sdc,
    STRING_AGG(DISTINCT(sdc_code), ', ') AS sdc_ag_temp_sdc_code,
    STRING_AGG(DISTINCT(sdc_filiere), ', ') AS sdc_ag_temp_filieres,
    STRING_AGG(DISTINCT(sdc_type_production), ', ') AS sdc_ag_temp_types_production,
    STRING_AGG(DISTINCT(sdc_type_agriculture), ', ') AS sdc_ag_temp_types_agriculture,
    AVG(sdc_part_sau_domaine) AS sdc_ag_temp_part_sau_domaine_moy,
    AVG(sdc_typo_surface_totale_assol_dvlp) AS sdc_ag_temp_surface_dvlp_real_moy,
    AVG(sdc_typo_surface_totale_assol) AS sdc_ag_temp_surface_real_moy,
    STRING_AGG(DISTINCT(sdc_typo_can_assol_dvlp), ', ') AS sdc_ag_temp_typologie_can_assol_dvlp,
    STRING_AGG(DISTINCT(sdc_typo_can_assol), ', ') AS sdc_ag_temp_typologie_can_assol,
    STRING_AGG(DISTINCT(dispositif_code), ', ') AS sdc_ag_temp_dispositif_code,
    STRING_AGG(DISTINCT(domaine_code), ', ') AS sdc_ag_temp_domaine_code,
    STRING_AGG(DISTINCT(domaine_siret), ', ') AS sdc_ag_temp_siret,
    STRING_AGG(DISTINCT(domaine_type_ferme), ', ') AS sdc_ag_temp_types_ferme,
    STRING_AGG(DISTINCT(domaine_position_departement), ', ') AS sdc_ag_temp_departement,
    STRING_AGG(DISTINCT(domaine_position_commune_id), ', ') AS sdc_ag_temp_commune_id,
    STRING_AGG(DISTINCT(CAST(domaine_position_code_insee AS TEXT)), ', ') AS sdc_ag_temp_code_insee,
    STRING_AGG(DISTINCT(CAST(domaine_position_cellule_safran AS TEXT)), ', ') AS sdc_ag_temp_cellule_safran_id,
    STRING_AGG(DISTINCT(CAST(domaine_position_rmqs_site_id AS TEXT)), ', ') AS sdc_ag_temp_rmqs_site_id,
    STRING_AGG(DISTINCT(domaine_zonage), ', ') AS sdc_ag_temp_zonage,
    AVG(domaine_pct_sau_zone_vulnerable) AS sdc_ag_temp_pct_sau_zone_vulnerable_moy,
    AVG(domaine_pct_sau_zone_excedent_structurel) AS sdc_ag_temp_pct_sau_zone_excedent_structurel_moy,
    AVG(domaine_pct_sau_zone_actions_complementaires) AS sdc_ag_temp_pct_sau_zone_actions_complementaires_moy,
    AVG(domaine_pct_sau_zone_natura_2000) AS sdc_ag_temp_pct_sau_zone_natura_2000_moy,
    AVG(domaine_pct_sau_zone_erosion) AS sdc_ag_temp_pct_sau_zone_erosion_moy,
    AVG(domaine_pct_sau_perimetre_protection_captage) AS sdc_ag_temp_pct_sau_perimetre_protection_captage_moy,
    MAX(domaine_distance_siege_parcelle_max) AS sdc_ag_temp_distance_siege_parcelle_max,
    STRING_AGG(DISTINCT(cast(domaine_annee_naissance_exploitant as text)), ', ') AS sdc_ag_temp_annee_naissance_exploitant,
    AVG(domaine_sau) AS sdc_ag_temp_domaine_sau_moy,
    AVG(domaine_cotisation_msa) AS sdc_ag_temp_cotisation_msa_moy,
    AVG(domaine_fermage_moyen) AS sdc_ag_temp_fermage_moy,
    AVG(domaine_aides_decouplees) AS sdc_ag_temp_aides_decouplees_moy,
    AVG(domaine_nombre_parcelles) AS sdc_ag_temp_nb_parcelles_moy,
    STRING_AGG(DISTINCT(domaine_otex_18_nom), ', ') AS sdc_ag_temp_otex_18,
    STRING_AGG(DISTINCT(domaine_otex_70_nom), ', ') AS sdc_ag_temp_otex_70,
    STRING_AGG(DISTINCT(domaine_statut_juridique_nom), ', ') AS sdc_ag_temp_statut_juridique,
    STRING_AGG(DISTINCT(domaine_objectifs), ', ') AS sdc_ag_temp_objectifs,
    STRING_AGG(DISTINCT(domaine_atouts), ', ') AS sdc_ag_temp_atouts,
    STRING_AGG(DISTINCT(domaine_contraintes), ', ') AS sdc_ag_temp_contraintes,
    STRING_AGG(DISTINCT(domaine_perspectives_evolution), ', ') AS sdc_ag_temp_perspective_evolution,
    STRING_AGG(DISTINCT(CAST(domaine_est_membre_cooperative AS TEXT)), ', ') AS sdc_ag_temp_est_membre_cooperative,
    STRING_AGG(DISTINCT(CAST(domaine_est_membre_groupe_developpement AS TEXT)), ', ') AS sdc_ag_temp_est_membre_groupe_developpement,
    STRING_AGG(DISTINCT(CAST(domaine_est_membre_cuma AS TEXT)), ', ') AS sdc_ag_temp_est_membre_cuma,
    STRING_AGG(DISTINCT(CAST(domaine_est_touristique AS TEXT)), ', ') AS sdc_ag_temp_est_touristique,
    AVG(domaine_main_oeuvre_exploitant) AS sdc_ag_temp_main_oeuvre_exploitant_moy,
    AVG(domaine_main_oeuvre_non_saisoniere) AS sdc_ag_temp_main_oeuvre_non_saisoniere_moy,
    AVG(domaine_main_oeuvre_saisoniere) AS sdc_ag_temp_main_oeuvre_saisoniere_moy,
    AVG(domaine_main_oeuvre_volontaire) AS sdc_ag_temp_main_oeuvre_volontaire_moy,
    STRING_AGG(DISTINCT(CAST(domaine_typologie_ruralite AS TEXT)), ', ') AS sdc_ag_temp_typologie_ruralite,
    STRING_AGG(DISTINCT(CAST(sdc_utili_desherbage_meca AS TEXT)), ', ') AS sdc_ag_temp_utili_desherbage_meca,
    STRING_AGG(DISTINCT(sdc_type_de_travail_du_sol), ', ') AS sdc_ag_temp_type_de_travail_du_sol,
    STRING_AGG(DISTINCT(synthetise_rotation_typo_can), ', ') AS sdc_ag_temp_synthetise_rotation_typo_can,
    AVG(sdc_ift_cible_non_mil_chimique_tot) AS sdc_ag_temp_ift_cible_non_mil_chimique_tot_moy,
    AVG(sdc_ift_cible_non_mil_chim_tot_hts) AS sdc_ag_temp_ift_cible_non_mil_chim_tot_hts_moy,
    AVG(sdc_ift_cible_non_mil_h) AS sdc_ag_temp_ift_cible_non_mil_h_moy,
    AVG(sdc_ift_cible_non_mil_f) AS sdc_ag_temp_ift_cible_non_mil_f_moy,
    AVG(sdc_ift_cible_non_mil_i) AS sdc_ag_temp_ift_cible_non_mil_i_moy,
    AVG(sdc_ift_cible_non_mil_ts) AS sdc_ag_temp_ift_cible_non_mil_ts_moy,
    AVG(sdc_ift_cible_non_mil_a) AS sdc_ag_temp_ift_cible_non_mil_a_moy,
    AVG(sdc_ift_cible_non_mil_hh) AS sdc_ag_temp_ift_cible_non_mil_hh_moy,
    AVG(sdc_ift_cible_non_mil_biocontrole) AS sdc_ag_temp_ift_cible_non_mil_biocontrole_moy,
    AVG(sdc_recours_aux_moyens_biologiques) AS sdc_ag_temp_recours_aux_moyens_biologiques_moy,
    AVG(sdc_recours_macroorganismes) AS sdc_ag_temp_recours_macroorganismes_moy,
    AVG(sdc_recours_produits_biotiques_sans_amm) AS sdc_ag_temp_recours_produits_biotiques_sans_amm_moy,
    AVG(sdc_recours_produits_abiotiques_sans_amm) AS sdc_ag_temp_recours_produits_abiotiques_sans_amm_moy,
    AVG(sdc_tps_utilisation_materiel) AS sdc_ag_temp_tps_utilisation_materiel_moy,
    AVG(sdc_tps_travail_manuel) AS sdc_ag_temp_tps_travail_manuel_moy,
    AVG(sdc_tps_travail_meca) AS sdc_ag_temp_tps_travail_meca_moy,
    AVG(sdc_tps_travail_total) AS sdc_ag_temp_tps_travail_total_moy,
    AVG(sdc_nbre_de_passages) AS sdc_ag_temp_nbre_de_passages_moy,
    AVG(sdc_nbre_de_passages_labour) AS sdc_ag_temp_nbre_de_passages_labour_moy,
    AVG(sdc_nbre_de_passages_tcs) AS sdc_ag_temp_nbre_de_passages_tcs_moy,
    AVG(sdc_nbre_de_passages_desherbage_meca) AS sdc_ag_temp_nbre_de_passages_desherbage_meca_moy,
    AVG(sdc_co_std_mil_tot) AS sdc_ag_temp_co_std_mil_tot_moy,
    AVG(sdc_co_std_mil_semis) AS sdc_ag_temp_co_std_mil_semis_moy,
    AVG(sdc_co_std_mil_fertimin) AS sdc_ag_temp_co_std_mil_fertimin_moy,
    AVG(sdc_co_std_mil_epandage_orga) AS sdc_ag_temp_co_std_mil_epandage_orga_moy,
    AVG(sdc_co_std_mil_phyto_sans_amm) AS sdc_ag_temp_co_std_mil_phyto_sans_amm_moy,
    AVG(sdc_co_std_mil_phyto_avec_amm) AS sdc_ag_temp_co_std_mil_phyto_avec_amm_moy,
    AVG(sdc_co_std_mil_trait_semence) AS sdc_ag_temp_co_std_mil_trait_semence_moy,
    AVG(sdc_co_std_mil_irrigation) AS sdc_ag_temp_co_std_mil_irrigation_moy,
    AVG(sdc_co_std_mil_intrants_autres) AS sdc_ag_temp_co_std_mil_intrants_autres_moy,
    AVG(sdc_cm_std_mil) AS sdc_ag_temp_cm_std_mil_moy,
    AVG(sdc_c_main_oeuvre_std_mil_tot) AS sdc_ag_temp_c_main_oeuvre_std_mil_tot_moy,
    AVG(sdc_c_main_oeuvre_std_mil_tractoriste) AS sdc_ag_temp_c_main_oeuvre_std_mil_tractoriste_moy,
    AVG(sdc_c_main_oeuvre_std_mil_manuelle) AS sdc_ag_temp_c_main_oeuvre_std_mil_manuelle_moy,
    AVG(sdc_pb_std_mil_avec_autoconso) AS sdc_ag_temp_pb_std_mil_avec_autoconso_moy,
    AVG(sdc_pb_std_mil_sans_autoconso) AS sdc_ag_temp_pb_std_mil_sans_autoconso_moy,
    AVG(sdc_mb_std_mil_avec_autoconso) AS sdc_ag_temp_mb_std_mil_avec_autoconso_moy,
    AVG(sdc_mb_std_mil_sans_autoconso) AS sdc_ag_temp_mb_std_mil_sans_autoconso_moy,
    AVG(sdc_msn_std_mil_sans_autoconso) AS sdc_ag_temp_msn_std_mil_sans_autoconso_moy,
    AVG(sdc_msn_std_mil_avec_autoconso) AS sdc_ag_temp_msn_std_mil_avec_autoconso_moy,
    AVG(sdc_md_std_mil_sans_autoconso) AS sdc_ag_temp_md_std_mil_sans_autoconso_moy,
    AVG(sdc_md_std_mil_avec_autoconso) AS sdc_ag_temp_md_std_mil_avec_autoconso_moy,
    AVG(sdc_conso_carburant) AS sdc_ag_temp_conso_carburant_moy,
    AVG(sdc_conso_eau) AS sdc_ag_temp_conso_eau_moy,
    AVG(sdc_ferti_n_mineral) AS sdc_ag_temp_ferti_n_mineral_moy,
    AVG(sdc_ferti_n_organique) AS sdc_ag_temp_ferti_n_organique_moy,
    AVG(sdc_ferti_p2o5_mineral) AS sdc_ag_temp_ferti_p2o5_mineral_moy,
    AVG(sdc_ferti_p2o5_organique) AS sdc_ag_temp_ferti_p2o5_organique_moy,
    AVG(sdc_ferti_k2o_mineral) AS sdc_ag_temp_ferti_k2o_mineral_moy,
    AVG(sdc_ferti_k2o_organique) AS sdc_ag_temp_ferti_k2o_organique_moy,
    AVG(sdc_qsa_tot_hts) AS sdc_ag_temp_qsa_tot_hts_moy,
    AVG(sdc_qsa_tot) AS sdc_ag_temp_qsa_tot_moy,
    AVG(sdc_qsa_danger_environnement_hts) AS sdc_ag_temp_qsa_danger_environnement_hts_moy,
    AVG(sdc_qsa_toxique_utilisateur_hts) AS sdc_ag_temp_qsa_toxique_utilisateur_hts_moy,
    AVG(sdc_qsa_cmr_hts) AS sdc_ag_temp_qsa_cmr_hts_moy,
    AVG(sdc_qsa_substances_candidates_substitution_hts) AS sdc_ag_temp_qsa_substances_candidates_substitution_hts_moy,
    AVG(sdc_qsa_substances_faible_risque_hts) AS sdc_ag_temp_qsa_substances_faible_risque_hts_moy,
    AVG(sdc_qsa_glyphosate_hts) AS sdc_ag_temp_qsa_glyphosate_hts_moy,
    AVG(sdc_qsa_chlortoluron_hts) AS sdc_ag_temp_qsa_chlortoluron_hts_moy,
    AVG(sdc_qsa_diflufenican_hts) AS sdc_ag_temp_qsa_diflufenican_hts_moy,
	AVG(sdc_qsa_prosulfocarbe_hts) AS sdc_ag_temp_qsa_prosulfocarbe_hts_moy,
	AVG(sdc_qsa_smetolachlore_hts) AS sdc_ag_temp_qsa_smetolachlore_hts_moy,
	AVG(sdc_qsa_boscalid_hts) AS sdc_ag_temp_qsa_boscalid_hts_moy,
	AVG(sdc_qsa_fluopyram_hts) AS sdc_ag_temp_qsa_fluopyram_hts_moy,
	AVG(sdc_qsa_lambda_cyhalothrine_hts) AS sdc_ag_temp_qsa_lambda_cyhalothrine_hts_moy,
	AVG(sdc_qsa_cuivre_tot_hts) AS sdc_ag_temp_qsa_cuivre_tot_hts_moy,
	AVG(sdc_qsa_cuivre_tot) AS sdc_ag_temp_qsa_cuivre_tot_moy,
	AVG(sdc_qsa_cuivre_phyto_hts) AS sdc_ag_temp_qsa_cuivre_phyto_hts_moy,
	AVG(sdc_qsa_cuivre_ferti) AS sdc_ag_temp_qsa_cuivre_ferti_moy,
	AVG(sdc_qsa_soufre_tot_hts) AS sdc_ag_temp_qsa_soufre_tot_hts_moy,
	AVG(sdc_qsa_soufre_phyto_hts) AS sdc_ag_temp_qsa_soufre_phyto_hts_moy,
	AVG(sdc_qsa_soufre_ferti) AS sdc_ag_temp_qsa_soufre_ferti_moy,
	AVG(sdc_qsa_bixafen) AS sdc_ag_temp_qsa_bixafen_moy,
	AVG(sdc_qsa_dicamba) AS sdc_ag_temp_qsa_dicamba_moy,
	AVG(sdc_qsa_mancozeb) AS sdc_ag_temp_qsa_mancozeb_moy,
	AVG(sdc_qsa_phosmet) AS sdc_ag_temp_qsa_phosmet_moy,
	AVG(sdc_qsa_tebuconazole) AS sdc_ag_temp_qsa_tebuconazole_moy,
	AVG(sdc_qsa_dimethenamidp) AS sdc_ag_temp_qsa_dimethenamidp_moy,
	AVG(sdc_qsa_pendimethalin) AS sdc_ag_temp_qsa_pendimethalin_moy,
	AVG(sdc_qsa_flufenacet) AS sdc_ag_temp_qsa_flufenacet_moy,
	AVG(sdc_qsa_aclonifen) AS sdc_ag_temp_qsa_aclonifen_moy,
	AVG(sdc_qsa_isoxaben) AS sdc_ag_temp_qsa_isoxaben_moy,
	AVG(sdc_qsa_beflutamid) AS sdc_ag_temp_qsa_beflutamid_moy,
	AVG(sdc_qsa_isoproturon) AS sdc_ag_temp_qsa_isoproturon_moy,
	AVG(sdc_qsa_clothianidine) AS sdc_ag_temp_qsa_clothianidine_moy,
	AVG(sdc_qsa_imidaclopride) AS sdc_ag_temp_qsa_imidaclopride_moy,
	AVG(sdc_qsa_thiamethoxam) AS sdc_ag_temp_qsa_thiamethoxam_moy,
	AVG(sdc_qsa_acetamipride) AS sdc_ag_temp_qsa_acetamipride_moy,
	AVG(sdc_qsa_thiaclopride) AS sdc_ag_temp_qsa_thiaclopride_moy,
	AVG(sdc_qsa_neonicotinoides) AS sdc_ag_temp_qsa_neonicotinoides_moy,
	AVG(sdc_qsa_abamectine_hts) AS sdc_ag_temp_qsa_abamectine_hts_moy,
	AVG(sdc_qsa_alpha_cypermethrine_hts) AS sdc_ag_temp_qsa_alpha_cypermethrine_hts_moy,
	AVG(sdc_qsa_azadirachtine_hts) AS sdc_ag_temp_qsa_azadirachtine_hts_moy,
	AVG(sdc_qsa_beta_cyfluthrine_hts) AS sdc_ag_temp_qsa_beta_cyfluthrine_hts_moy,
	AVG(sdc_qsa_chlorpyrifos_methyl_hts) AS sdc_ag_temp_qsa_chlorpyrifos_methyl_hts_moy,
	AVG(sdc_qsa_cyantraniliprole_hts) AS sdc_ag_temp_qsa_cyantraniliprole_hts_moy,
	AVG(sdc_qsa_cypermethrine_hts) AS sdc_ag_temp_qsa_cypermethrine_hts_moy,
	AVG(sdc_qsa_deltamethrine_hts) AS sdc_ag_temp_qsa_deltamethrine_hts_moy,
	AVG(sdc_qsa_dimethoate_hts) AS sdc_ag_temp_qsa_dimethoate_hts_moy,
	AVG(sdc_qsa_emamectine_hts) AS sdc_ag_temp_qsa_emamectine_hts_moy,
	AVG(sdc_qsa_esfenvalerate_hts) AS sdc_ag_temp_qsa_esfenvalerate_hts_moy,
	AVG(sdc_qsa_flonicamide_hts) AS sdc_ag_temp_qsa_flonicamide_hts_moy,
	AVG(sdc_qsa_huile_de_colza_hts) AS sdc_ag_temp_qsa_huile_de_colza_hts_moy,
	AVG(sdc_qsa_huile_de_paraffine_hts) AS sdc_ag_temp_qsa_huile_de_paraffine_hts_moy,
	AVG(sdc_qsa_indoxacarbe_hts) AS sdc_ag_temp_qsa_indoxacarbe_hts_moy,
	AVG(sdc_qsa_primicarbe_hts) AS sdc_ag_temp_qsa_primicarbe_hts_moy,
	AVG(sdc_qsa_pymetrozine_hts) AS sdc_ag_temp_qsa_pymetrozine_hts_moy,
	AVG(sdc_qsa_pyrethrine_hts) AS sdc_ag_temp_qsa_pyrethrine_hts_moy,
	AVG(sdc_qsa_silicate_aluminium_hts) AS sdc_ag_temp_qsa_silicate_aluminium_hts_moy,
	AVG(sdc_qsa_spinosad_hts) AS sdc_ag_temp_qsa_spinosad_hts_moy,
	AVG(sdc_qsa_spirotetramate_hts) AS sdc_ag_temp_qsa_spirotetramate_hts_moy,
	AVG(sdc_qsa_tau_fluvalinate_hts) AS sdc_ag_temp_qsa_tau_fluvalinate_hts_moy,
	AVG(sdc_hri1_tot) AS sdc_ag_temp_hri1_tot_moy,
	AVG(sdc_hri1_g1_tot) AS sdc_ag_temp_hri1_g1_tot_moy,
	AVG(sdc_hri1_g2_tot) AS sdc_ag_temp_hri1_g2_tot_moy,
	AVG(sdc_hri1_g3_tot) AS sdc_ag_temp_hri1_g3_tot_moy,
	AVG(sdc_hri1_g4_tot) AS sdc_ag_temp_hri1_g4_tot_moy,
	AVG(sdc_ges_tot_directes_co2) AS sdc_ag_temp_ges_tot_directes_co2_moy,
	AVG(sdc_ges_tot_directes_ch4) AS sdc_ag_temp_ges_tot_directes_ch4_moy,
	AVG(sdc_ges_tot_directes_n2o) AS sdc_ag_temp_ges_tot_directes_n2o_moy,
	AVG(sdc_ges_tot_directes) AS sdc_ag_temp_ges_tot_directes_moy,
	AVG(sdc_ges_tot_indirectes_co2) AS sdc_ag_temp_ges_tot_indirectes_co2_moy,
	AVG(sdc_ges_tot_indirectes_ch4) AS sdc_ag_temp_ges_tot_indirectes_ch4_moy,
	AVG(sdc_ges_tot_indirectes_n2o) AS sdc_ag_temp_ges_tot_indirectes_n2o_moy,
	AVG(sdc_ges_tot_indirectes) AS sdc_ag_temp_ges_tot_indirectes_moy
from entrepot_sdc_magasin_dirodur
CROSS JOIN LATERAL UNNEST(string_to_array(synthetise_campagnes, ', ')) AS synthetise_campagnes_unnested
WHERE etat_temporel IN ('pz0','point_I','point_B')
GROUP BY sdc_numero_dephy, etat_temporel;