SELECT
    STRING_AGG(DISTINCT(sdc_numero_dephy), ', ') as numero_dephy,
    STRING_AGG(DISTINCT(etat_temporel), ', ') as etat_temporel,
    STRING_AGG(CAST(domaine_campagne AS TEXT), ', ') AS liste_campagne_domaine,
    STRING_AGG(CAST(synthetise_campagnes AS TEXT), ', ') AS liste_synthetise_campagnes,
    COUNT(*) AS nombre_sdc_agrege,
    STRING_AGG(DISTINCT(sdc_code), ', ') AS liste_sdc_code,
    STRING_AGG(DISTINCT(sdc_filiere), ', ') AS filieres,
    STRING_AGG(DISTINCT(sdc_type_production), ', ') AS types_production,
    STRING_AGG(DISTINCT(sdc_type_agriculture), ', ') AS types_agriculture,
    AVG(sdc_part_sau_domaine) AS part_sau_domaine_moy,
    AVG(sdc_typo_surface_totale_assol_dvlp) AS surface_dvlp_real_moy,
    AVG(sdc_typo_surface_totale_assol) AS surface_real_moy,
    STRING_AGG(DISTINCT(sdc_typo_can_assol_dvlp), ', ') AS liste_typologie_can_assol_dvlp,
    STRING_AGG(DISTINCT(sdc_typo_can_assol), ', ') AS liste_typologie_can_assol,
    STRING_AGG(DISTINCT(dispositif_code), ', ') AS liste_dispositif_code,
    STRING_AGG(DISTINCT(domaine_code), ', ') AS liste_domaine_code,
    STRING_AGG(DISTINCT(domaine_siret), ', ') AS liste_siret,
    STRING_AGG(DISTINCT(domaine_type_ferme), ', ') AS types_ferme,
    STRING_AGG(DISTINCT(domaine_position_departement), ', ') AS departement,
    STRING_AGG(DISTINCT(domaine_position_commune_id), ', ') AS commune_id,
    STRING_AGG(DISTINCT(CAST(domaine_position_code_insee AS TEXT)), ', ') AS code_insee,
    STRING_AGG(DISTINCT(CAST(domaine_position_cellule_safran AS TEXT)), ', ') AS cellule_safran_id,
    STRING_AGG(DISTINCT(CAST(domaine_position_rmqs_site_id AS TEXT)), ', ') AS rmqs_site_id,
    STRING_AGG(DISTINCT(domaine_zonage), ', ') AS zonages,
    AVG(domaine_pct_sau_zone_vulnerable) AS pct_sau_zone_vulnerable_moy,
    AVG(domaine_pct_sau_zone_excedent_structurel) AS pct_sau_zone_excedent_structurel_moy,
    AVG(domaine_pct_sau_zone_actions_complementaires) AS pct_sau_zone_actions_complementaires_moy,
    AVG(domaine_pct_sau_zone_natura_2000) AS pct_sau_zone_natura_2000_moy,
    AVG(domaine_pct_sau_zone_erosion) AS pct_sau_zone_erosion_moy,
    AVG(domaine_pct_sau_perimetre_protection_captage) AS pct_sau_perimetre_protection_captage_moy,
    MAX(domaine_distance_siege_parcelle_max) AS distance_siege_parcelle_max,
    STRING_AGG(DISTINCT(cast(domaine_annee_naissance_exploitant as text)), ', ') AS liste_annee_naissance_exploitant,
    AVG(domaine_sau) AS domaine_sau_moy,
    AVG(domaine_cotisation_msa) AS cotisation_msa_moy,
    AVG(domaine_fermage_moyen) AS fermage_moy,
    AVG(domaine_aides_decouplees) AS aides_decouplees_moy,
    AVG(domaine_nombre_parcelles) AS nb_parcelles_moy,
    STRING_AGG(DISTINCT(domaine_otex_18_nom), ', ') AS liste_otex_18,
    STRING_AGG(DISTINCT(domaine_otex_70_nom), ', ') AS liste_otex_70,
    STRING_AGG(DISTINCT(domaine_statut_juridique_nom), ', ') AS liste_statut_juridique,
    STRING_AGG(DISTINCT(domaine_objectifs), ', ') AS liste_objectifs,
    STRING_AGG(DISTINCT(domaine_atouts), ', ') AS liste_atouts,
    STRING_AGG(DISTINCT(domaine_contraintes), ', ') AS liste_contraintes,
    STRING_AGG(DISTINCT(domaine_perspectives_evolution), ', ') AS liste_perspective_evolution,
    STRING_AGG(DISTINCT(CAST(domaine_est_membre_cooperative AS TEXT)), ', ') AS est_membre_cooperative,
    STRING_AGG(DISTINCT(CAST(domaine_est_membre_groupe_developpement AS TEXT)), ', ') AS est_membre_groupe_developpement,
    STRING_AGG(DISTINCT(CAST(domaine_est_membre_cuma AS TEXT)), ', ') AS est_membre_cuma,
    STRING_AGG(DISTINCT(CAST(domaine_est_touristique AS TEXT)), ', ') AS est_touristique,
    AVG(domaine_main_oeuvre_exploitant) AS domaine_main_oeuvre_exploitant_moy,
    AVG(domaine_main_oeuvre_non_saisoniere) AS domaine_main_oeuvre_non_saisoniere_moy,
    AVG(domaine_main_oeuvre_saisoniere) AS domaine_main_oeuvre_saisoniere_moy,
    AVG(domaine_main_oeuvre_volontaire) AS domaine_main_oeuvre_volontaire_moy,
    STRING_AGG(DISTINCT(cast(domaine_typologie_ruralite AS TEXT)), ', ') AS liste_domaine_typologie_ruralite,
    STRING_AGG(DISTINCT(CAST(sdc_utili_desherbage_meca AS TEXT)), ', ') AS liste_utili_desherbage_meca,
    STRING_AGG(DISTINCT(sdc_type_de_travail_du_sol), ', ') AS liste_type_de_travail_du_sol,
    STRING_AGG(DISTINCT(synthetise_rotation_typo_can), ', ') AS liste_synthetise_rotation_typo_can,
    AVG(sdc_ift_cible_non_mil_chimique_tot) AS ift_cible_non_mil_chimique_tot_moy,
    AVG(sdc_ift_cible_non_mil_chim_tot_hts) AS ift_cible_non_mil_chim_tot_hts_moy,
    AVG(sdc_ift_cible_non_mil_h) AS ift_cible_non_mil_h_moy,
    AVG(sdc_ift_cible_non_mil_f) AS ift_cible_non_mil_f_moy,
    AVG(sdc_ift_cible_non_mil_i) AS ift_cible_non_mil_i_moy,
    AVG(sdc_ift_cible_non_mil_ts) AS ift_cible_non_mil_ts_moy,
    AVG(sdc_ift_cible_non_mil_a) AS ift_cible_non_mil_a_moy,
    AVG(sdc_ift_cible_non_mil_hh) AS ift_cible_non_mil_hh_moy,
    AVG(sdc_ift_cible_non_mil_biocontrole) AS ift_cible_non_mil_biocontrole_moy,
    AVG(sdc_recours_aux_moyens_biologiques) AS recours_aux_moyens_biologiques_moy,
    AVG(sdc_recours_macroorganismes) AS recours_macroorganismes_moy,
    AVG(sdc_recours_produits_biotiques_sans_amm) AS recours_produits_biotiques_sans_amm_moy,
    AVG(sdc_recours_produits_abiotiques_sans_amm) AS recours_produits_abiotiques_sans_amm_moy,
    AVG(sdc_tps_utilisation_materiel) AS tps_utilisation_materiel_moy,
    AVG(sdc_tps_travail_manuel) AS tps_travail_manuel_moy,
    AVG(sdc_tps_travail_meca) AS tps_travail_meca_moy,
    AVG(sdc_tps_travail_total) AS tps_travail_total_moy,
    AVG(sdc_nbre_de_passages) AS nbre_de_passages_moy,
    AVG(sdc_nbre_de_passages_labour) AS nbre_de_passages_labour_moy,
    AVG(sdc_nbre_de_passages_tcs) AS nbre_de_passages_tcs_moy,
    AVG(sdc_nbre_de_passages_desherbage_meca) AS nbre_de_passages_desherbage_meca_moy,
    AVG(sdc_co_std_mil_tot) AS co_std_mil_tot_moy,
    AVG(sdc_co_std_mil_semis) AS co_std_mil_semis_moy,
    AVG(sdc_co_std_mil_fertimin) AS co_std_mil_fertimin_moy,
    AVG(sdc_co_std_mil_epandage_orga) AS co_std_mil_epandage_orga_moy,
    AVG(sdc_co_std_mil_phyto_sans_amm) AS co_std_mil_phyto_sans_amm_moy,
    AVG(sdc_co_std_mil_phyto_avec_amm) AS co_std_mil_phyto_avec_amm_moy,
    AVG(sdc_co_std_mil_trait_semence) AS co_std_mil_trait_semence_moy,
    AVG(sdc_co_std_mil_irrigation) AS co_std_mil_irrigation_moy,
    AVG(sdc_co_std_mil_intrants_autres) AS co_std_mil_intrants_autres_moy,
    AVG(sdc_cm_std_mil) AS cm_std_mil_moy,
    AVG(sdc_c_main_oeuvre_std_mil_tot) AS c_main_oeuvre_std_mil_tot_moy,
    AVG(sdc_c_main_oeuvre_std_mil_tractoriste) AS c_main_oeuvre_std_mil_tractoriste_moy,
    AVG(sdc_c_main_oeuvre_std_mil_manuelle) AS c_main_oeuvre_std_mil_manuelle_moy,
    AVG(sdc_pb_std_mil_avec_autoconso) AS pb_std_mil_avec_autoconso_moy,
    AVG(sdc_pb_std_mil_sans_autoconso) AS pb_std_mil_sans_autoconso_moy,
    AVG(sdc_mb_std_mil_avec_autoconso) AS mb_std_mil_avec_autoconso_moy,
    AVG(sdc_mb_std_mil_sans_autoconso) AS mb_std_mil_sans_autoconso_moy,
    AVG(sdc_msn_std_mil_sans_autoconso) AS msn_std_mil_sans_autoconso_moy,
    AVG(sdc_msn_std_mil_avec_autoconso) AS msn_std_mil_avec_autoconso_moy,
    AVG(sdc_md_std_mil_sans_autoconso) AS md_std_mil_sans_autoconso_moy,
    AVG(sdc_md_std_mil_avec_autoconso) AS md_std_mil_avec_autoconso_moy,
    AVG(sdc_conso_carburant) AS conso_carburant_moy,
    AVG(sdc_conso_eau) AS conso_eau_moy,
    AVG(sdc_ferti_n_mineral) AS ferti_n_mineral_moy,
    AVG(sdc_ferti_n_organique) AS ferti_n_organique_moy,
    AVG(sdc_ferti_p2o5_mineral) AS ferti_p2o5_mineral_moy,
    AVG(sdc_ferti_p2o5_organique) AS ferti_p2o5_organique_moy,
    AVG(sdc_ferti_k2o_mineral) AS ferti_k2o_mineral_moy,
    AVG(sdc_ferti_k2o_organique) AS ferti_k2o_organique_moy,
    AVG(sdc_qsa_tot_hts) AS qsa_tot_hts_moy,
    AVG(sdc_qsa_tot) AS qsa_tot_moy,
    AVG(sdc_qsa_danger_environnement_hts) AS qsa_danger_environnement_hts_moy,
    AVG(sdc_qsa_toxique_utilisateur_hts) AS qsa_toxique_utilisateur_hts_moy,
    AVG(sdc_qsa_cmr_hts) AS qsa_cmr_hts_moy,
    AVG(sdc_qsa_substances_candidates_substitution_hts) AS qsa_substances_candidates_substitution_hts_moy,
    AVG(sdc_qsa_substances_faible_risque_hts) AS qsa_substances_faible_risque_hts_moy,
    AVG(sdc_qsa_glyphosate_hts) AS qsa_glyphosate_hts_moy,
    AVG(sdc_qsa_chlortoluron_hts) AS qsa_chlortoluron_hts_moy,
    AVG(sdc_qsa_diflufenican_hts) AS qsa_diflufenican_hts_moy,
	AVG(sdc_qsa_prosulfocarbe_hts) as qsa_prosulfocarbe_hts_moy,
	AVG(sdc_qsa_smetolachlore_hts) as qsa_smetolachlore_hts_moy,
	AVG(sdc_qsa_boscalid_hts) as qsa_boscalid_hts_moy,
	AVG(sdc_qsa_fluopyram_hts) as qsa_fluopyram_hts_moy,
	AVG(sdc_qsa_lambda_cyhalothrine_hts) as qsa_lambda_cyhalothrine_hts_moy,
	AVG(sdc_qsa_cuivre_tot_hts) as qsa_cuivre_tot_hts_moy,
	AVG(sdc_qsa_cuivre_tot) as qsa_cuivre_tot_moy,
	AVG(sdc_qsa_cuivre_phyto_hts) as qsa_cuivre_phyto_hts_moy,
	AVG(sdc_qsa_cuivre_ferti) as qsa_cuivre_ferti_moy,
	AVG(sdc_qsa_soufre_tot_hts) as qsa_soufre_tot_hts_moy,
	AVG(sdc_qsa_soufre_phyto_hts) as qsa_soufre_phyto_hts_moy,
	AVG(sdc_qsa_soufre_ferti) as qsa_soufre_ferti_moy,
	AVG(sdc_qsa_bixafen) as qsa_bixafen_moy,
	AVG(sdc_qsa_dicamba) as qsa_dicamba_moy,
	AVG(sdc_qsa_mancozeb) as qsa_mancozeb_moy,
	AVG(sdc_qsa_phosmet) as qsa_phosmet_moy,
	AVG(sdc_qsa_tebuconazole) as qsa_tebuconazole_moy,
	AVG(sdc_qsa_dimethenamidp) as qsa_dimethenamidp_moy,
	AVG(sdc_qsa_pendimethalin) as qsa_pendimethalin_moy,
	AVG(sdc_qsa_flufenacet) as qsa_flufenacet_moy,
	AVG(sdc_qsa_aclonifen) as qsa_aclonifen_moy,
	AVG(sdc_qsa_isoxaben) as qsa_isoxaben_moy,
	AVG(sdc_qsa_beflutamid) as qsa_beflutamid_moy,
	AVG(sdc_qsa_isoproturon) as qsa_isoproturon_moy,
	AVG(sdc_qsa_clothianidine) as qsa_clothianidine_moy,
	AVG(sdc_qsa_imidaclopride) as qsa_imidaclopride_moy,
	AVG(sdc_qsa_thiamethoxam) as qsa_thiamethoxam_moy,
	AVG(sdc_qsa_acetamipride) as qsa_acetamipride_moy,
	AVG(sdc_qsa_thiaclopride) as qsa_thiaclopride_moy,
	AVG(sdc_qsa_neonicotinoides) as qsa_neonicotinoides_moy,
	AVG(sdc_qsa_abamectine_hts) as qsa_abamectine_hts_moy,
	AVG(sdc_qsa_alpha_cypermethrine_hts) as qsa_alpha_cypermethrine_hts_moy,
	AVG(sdc_qsa_azadirachtine_hts) as qsa_azadirachtine_hts_moy,
	AVG(sdc_qsa_beta_cyfluthrine_hts) as qsa_beta_cyfluthrine_hts_moy,
	AVG(sdc_qsa_chlorpyrifos_methyl_hts) as qsa_chlorpyrifos_methyl_hts_moy,
	AVG(sdc_qsa_cyantraniliprole_hts) as qsa_cyantraniliprole_hts_moy,
	AVG(sdc_qsa_cypermethrine_hts) as qsa_cypermethrine_hts_moy,
	AVG(sdc_qsa_deltamethrine_hts) as qsa_deltamethrine_hts_moy,
	AVG(sdc_qsa_dimethoate_hts) as qsa_dimethoate_hts_moy,
	AVG(sdc_qsa_emamectine_hts) as qsa_emamectine_hts_moy,
	AVG(sdc_qsa_esfenvalerate_hts) as qsa_esfenvalerate_hts_moy,
	AVG(sdc_qsa_flonicamide_hts) as qsa_flonicamide_hts_moy,
	AVG(sdc_qsa_huile_de_colza_hts) as qsa_huile_de_colza_hts_moy,
	AVG(sdc_qsa_huile_de_paraffine_hts) as qsa_huile_de_paraffine_hts_moy,
	AVG(sdc_qsa_indoxacarbe_hts) as qsa_indoxacarbe_hts_moy,
	AVG(sdc_qsa_primicarbe_hts) as qsa_primicarbe_hts_moy,
	AVG(sdc_qsa_pymetrozine_hts) as qsa_pymetrozine_hts_moy,
	AVG(sdc_qsa_pyrethrine_hts) as qsa_pyrethrine_hts_moy,
	AVG(sdc_qsa_silicate_aluminium_hts) as qsa_silicate_aluminium_hts_moy,
	AVG(sdc_qsa_spinosad_hts) as qsa_spinosad_hts_moy,
	AVG(sdc_qsa_spirotetramate_hts) as qsa_spirotetramate_hts_moy,
	AVG(sdc_qsa_tau_fluvalinate_hts) as qsa_tau_fluvalinate_hts_moy,
	AVG(sdc_hri1_tot) as hri1_tot_moy,
	AVG(sdc_hri1_g1_tot) as hri1_g1_tot_moy,
	AVG(sdc_hri1_g2_tot) as hri1_g2_tot_moy,
	AVG(sdc_hri1_g3_tot) as hri1_g3_tot_moy,
	AVG(sdc_hri1_g4_tot) as hri1_g4_tot_moy,
	AVG(sdc_ges_tot_directes_co2) as ges_tot_directes_co2_moy,
	AVG(sdc_ges_tot_directes_ch4) as ges_tot_directes_ch4_moy,
	AVG(sdc_ges_tot_directes_n2o) as ges_tot_directes_n2o_moy,
	AVG(sdc_ges_tot_directes) as ges_tot_directes_moy,
	AVG(sdc_ges_tot_indirectes_co2) as ges_tot_indirectes_co2_moy,
	AVG(sdc_ges_tot_indirectes_ch4) as ges_tot_indirectes_ch4_moy,
	AVG(sdc_ges_tot_indirectes_n2o) as ges_tot_indirectes_n2o_moy,
	AVG(sdc_ges_tot_indirectes) as ges_tot_indirectes_moy
from entrepot_sdc_magasin_dirodur
WHERE etat_temporel IN ('pz0','point_I','point_B')
GROUP BY sdc_numero_dephy, etat_temporel;