SELECT
    eirp.utili_desherbage_meca_tx_comp,
    eirp.utili_desherbage_meca_chmps_non_rens,
	CASE eirp.utili_desherbage_meca WHEN true THEN 'oui' WHEN false THEN 'non' END utili_desherbage_meca,
    eirp.type_de_travail_du_sol_tx_comp,
    eirp.type_de_travail_du_sol_chmps_non_rens,
    eirp.type_de_travail_du_sol,
    eirp.tps_utilisation_materiel_tx_comp,
    eirp.tps_utilisation_materiel_sept,
    eirp.tps_utilisation_materiel_oct,
    eirp.tps_utilisation_materiel_nov,
    eirp.tps_utilisation_materiel_mars,
    eirp.tps_utilisation_materiel_mai,
    eirp.tps_utilisation_materiel_juin,
    eirp.tps_utilisation_materiel_juillet,
    eirp.tps_utilisation_materiel_janvier,
    eirp.tps_utilisation_materiel_fevrier,
    eirp.tps_utilisation_materiel_dec,
    eirp.tps_utilisation_materiel_avril,
    eirp.tps_utilisation_materiel_aout,
    eirp.tps_utilisation_materiel,
    eirp.tps_util_materiel_chmps_non_rens,
    eirp.tps_travail_total_tx_comp,
    eirp.tps_travail_total_septembre,
    eirp.tps_travail_total_octobre,
    eirp.tps_travail_total_novembre,
    eirp.tps_travail_total_mars,
    eirp.tps_travail_total_mai,
    eirp.tps_travail_total_juin,
    eirp.tps_travail_total_juillet,
    eirp.tps_travail_total_janvier,
    eirp.tps_travail_total_fevrier,
    eirp.tps_travail_total_decembre,
    eirp.tps_travail_total_avril,
    eirp.tps_travail_total_aout,
    eirp.tps_travail_total,
    eirp.tps_travail_mecanise_tx_comp,
    eirp.tps_travail_mecanise_septembre,
    eirp.tps_travail_mecanise_octobre,
    eirp.tps_travail_mecanise_novembre,
    eirp.tps_travail_mecanise_mars,
    eirp.tps_travail_mecanise_mai,
    eirp.tps_travail_mecanise_juin,
    eirp.tps_travail_mecanise_juillet,
    eirp.tps_travail_mecanise_janvier,
    eirp.tps_travail_mecanise_fevrier,
    eirp.tps_travail_mecanise_decembre,
    eirp.tps_travail_mecanise_avril,
    eirp.tps_travail_mecanise_aout,
    eirp.tps_travail_mecanise,
    eirp.tps_travail_manuel_tx_comp,
    eirp.tps_travail_manuel_septembre,
    eirp.tps_travail_manuel_octobre,
    eirp.tps_travail_manuel_novembre,
    eirp.tps_travail_manuel_mars,
    eirp.tps_travail_manuel_mai,
    eirp.tps_travail_manuel_juin,
    eirp.tps_travail_manuel_juillet,
    eirp.tps_travail_manuel_janvier,
    eirp.tps_travail_manuel_fevrier,
    eirp.tps_travail_manuel_decembre,
    eirp.tps_travail_manuel_avril,
    eirp.tps_travail_manuel_aout,
    eirp.tps_travail_manuel,
    eirp.tps_trav_total_chmps_non_rens,
    eirp.tps_trav_mecanise_chmps_non_rens,
    eirp.tps_trav_manuel_chmps_non_rens,
    eirp.recours_produits_biotiques_sansamm,
    eirp.recours_produits_abiotiques_sansamm,
    eirp.recours_macroorganismes,
    eirp.recours_aux_moyens_biologiques,
    eirp.qsa_toxique_utilisateur_hts,
    eirp.qsa_toxique_utilisateur,
    eirp.qsa_tot_taux_de_completion,
    eirp.qsa_tot_hts,
    eirp.qsa_tot_detail_champs_non_renseig,
    eirp.qsa_tot,
    eirp.qsa_substances_faible_risque_hts,
    eirp.qsa_substances_faible_risque,
    eirp.qsa_substances_candidates_substitution_hts,
    eirp.qsa_substances_candidates_substitution,
    eirp.qsa_soufre_tot_hts,
    eirp.qsa_soufre_tot,
    eirp.qsa_soufre_phyto_hts,
    eirp.qsa_soufre_phyto,
    eirp.qsa_soufre_ferti,
    eirp.qsa_smetolachlore_hts,
    eirp.qsa_smetolachlore,
    eirp.qsa_prosulfocarbe_hts,
    eirp.qsa_prosulfocarbe,
    eirp.qsa_lambda_cyhalothrine_hts,
    eirp.qsa_lambda_cyhalothrine,
    eirp.qsa_glyphosate_hts,
    eirp.qsa_glyphosate,
    eirp.qsa_fluopyram_hts,
    eirp.qsa_fluopyram,
    eirp.qsa_diflufenican_hts,
    eirp.qsa_diflufenican,
    eirp.qsa_danger_environnement_hts,
    eirp.qsa_danger_environnement,
    eirp.qsa_cuivre_tot_hts,
    eirp.qsa_cuivre_tot,
    eirp.qsa_cuivre_phyto_hts,
    eirp.qsa_cuivre_phyto,
    eirp.qsa_cuivre_ferti,
    eirp.qsa_cmr_hts,
    eirp.qsa_cmr,
    eirp.qsa_chlortoluron_hts,
    eirp.qsa_chlortoluron,
    eirp.qsa_boscalid_hts,
    eirp.qsa_boscalid,
    eirp.nbre_de_passages_tx_comp,
    eirp.nbre_de_passages_tcs_tx_comp,
    eirp.nbre_de_passages_tcs_chmps_non_rens,
    eirp.nbre_de_passages_tcs,
    eirp.nbre_de_passages_septembre,
    eirp.nbre_de_passages_octobre,
    eirp.nbre_de_passages_novembre,
    eirp.nbre_de_passages_mars,
    eirp.nbre_de_passages_mai,
    eirp.nbre_de_passages_labour_tx_comp,
    eirp.nbre_de_passages_labour_chmps_non_rens,
    eirp.nbre_de_passages_labour,
    eirp.nbre_de_passages_juin,
    eirp.nbre_de_passages_juillet,
    eirp.nbre_de_passages_janvier,
    eirp.nbre_de_passages_fevrier,
    eirp.nbre_de_passages_desherbage_meca_tx_comp,
    eirp.nbre_de_passages_desherbage_meca_chmps_non_rens,
    eirp.nbre_de_passages_desherbage_meca,
    eirp.nbre_de_passages_decembre,
    eirp.nbre_de_passages_chmps_non_rens,
    eirp.nbre_de_passages_avril,
    eirp.nbre_de_passages_aout,
    eirp.nbre_de_passages,
    eirp.intervention_realise_id,
    eirp.ift_histo_tx_comp,
    eirp.ift_histo_ts,
    eirp.ift_histo_i,
    eirp.ift_histo_hh,
    eirp.ift_histo_h,
    eirp.ift_histo_f,
    eirp.ift_histo_chmps_non_rens,
    eirp.ift_histo_chimique_tot,
    eirp.ift_histo_chim_tot_hts,
    eirp.ift_histo_biocontrole,
    eirp.ift_histo_a,
    eirp.ift_culture_non_mil_tx_comp,
    eirp.ift_culture_non_mil_ts,
    eirp.ift_culture_non_mil_i,
    eirp.ift_culture_non_mil_hh,
    eirp.ift_culture_non_mil_h,
    eirp.ift_culture_non_mil_f,
    eirp.ift_culture_non_mil_chmp_no_rens,
    eirp.ift_culture_non_mil_chimique_tot,
    eirp.ift_culture_non_mil_chim_tot_hts,
    eirp.ift_culture_non_mil_biocontrole,
    eirp.ift_culture_non_mil_a,
    eirp.ift_culture_mil_tx_comp,
    eirp.ift_culture_mil_ts,
    eirp.ift_culture_mil_i,
    eirp.ift_culture_mil_hh,
    eirp.ift_culture_mil_h,
    eirp.ift_culture_mil_f,
    eirp.ift_culture_mil_chmps_non_rens,
    eirp.ift_culture_mil_chimique_tot,
    eirp.ift_culture_mil_chim_tot_hts,
    eirp.ift_culture_mil_biocontrole,
    eirp.ift_culture_mil_a,
    eirp.ift_cible_non_mil_tx_comp,
    eirp.ift_cible_non_mil_ts,
    eirp.ift_cible_non_mil_i,
    eirp.ift_cible_non_mil_hh,
    eirp.ift_cible_non_mil_h,
    eirp.ift_cible_non_mil_f,
    eirp.ift_cible_non_mil_chmps_non_rens,
    eirp.ift_cible_non_mil_chimique_tot,
    eirp.ift_cible_non_mil_chim_tot_hts,
    eirp.ift_cible_non_mil_biocontrole,
    eirp.ift_cible_non_mil_a,
    eirp.ift_cible_mil_tx_comp,
    eirp.ift_cible_mil_ts,
    eirp.ift_cible_mil_i,
    eirp.ift_cible_mil_hh,
    eirp.ift_cible_mil_h,
    eirp.ift_cible_mil_f,
    eirp.ift_cible_mil_chmps_non_rens,
    eirp.ift_cible_mil_chimique_tot,
    eirp.ift_cible_mil_chim_tot_hts,
    eirp.ift_cible_mil_biocontrole,
    eirp.ift_cible_mil_a,
    eirp.hri1_tot_taux_de_completion,
    eirp.hri1_tot_detail_champs_non_renseig,
    eirp.hri1_tot,
    eirp.hri1_hts,
    eirp.hri1_g4_tot_taux_de_completion,
    eirp.hri1_g4_tot_detail_champs_non_renseig,
    eirp.hri1_g4_tot,
    eirp.hri1_g4_hts,
    eirp.hri1_g3_tot_taux_de_completion,
    eirp.hri1_g3_tot_detail_champs_non_renseig,
    eirp.hri1_g3_tot,
    eirp.hri1_g3_hts,
    eirp.hri1_g2_tot_taux_de_completion,
    eirp.hri1_g2_tot_detail_champs_non_renseig,
    eirp.hri1_g2_tot,
    eirp.hri1_g2_hts,
    eirp.hri1_g1_tot_taux_de_completion,
    eirp.hri1_g1_tot_detail_champs_non_renseig,
    eirp.hri1_g1_tot,
    eirp.hri1_g1_hts,
    eirp.ferti_zn_mineral,
    eirp.ferti_so3_mineral,
    eirp.ferti_s_organique,
    eirp.ferti_p2o5_tot,
    eirp.ferti_p2o5_organique,
    eirp.ferti_p2o5_mineral,
    eirp.ferti_na2o_mineral,
    eirp.ferti_n_tot,
    eirp.ferti_n_organique,
    eirp.ferti_n_mineral,
    eirp.ferti_mo_mineral,
    eirp.ferti_mn_mineral,
    eirp.ferti_mgo_organique,
    eirp.ferti_mgo_mineral,
    eirp.ferti_k2o_tot,
    eirp.ferti_k2o_organique,
    eirp.ferti_k2o_mineral,
    eirp.ferti_fe_mineral,
    eirp.ferti_cu_mineral,
    eirp.ferti_cao_organique,
    eirp.ferti_ca_mineral,
    eirp.ferti_b_mineral,
    eirp.conso_eau_tx_comp,
    eirp.conso_eau_chmps_non_rens,
    eirp.conso_eau,
    eirp.conso_carburant_tx_comp,
    eirp.conso_carburant_chmps_non_rens,
    eirp.conso_carburant,
    eirp.co_trait_semence_std_mil,
    eirp.co_trait_semence_reelles,
    eirp.co_tot_std_mil_tx_comp,
    eirp.co_tot_std_mil_chp_non_rens,
    eirp.co_tot_std_mil,
    eirp.co_tot_reelles_tx_comp,
    eirp.co_tot_reelles,
    eirp.co_tot_reell_chmps_non_rens,
    eirp.co_substrats_std_mil,
    eirp.co_substrats_reelles,
    eirp.co_semis_std_mil,
    eirp.co_semis_reel,
    eirp.co_pots_std_mil,
    eirp.co_pots_reelles,
    eirp.co_phyto_sans_amm_std_mil,
    eirp.co_phyto_sans_amm_reelles,
    eirp.co_phyto_avec_amm_std_mil,
    eirp.co_phyto_avec_amm_reelles,
    eirp.co_irrigation_std_mil,
    eirp.co_irrigation_reelles,
    eirp.co_intrants_autres_std_mil,
    eirp.co_intrants_autres_reelles,
    eirp.co_fertimin_std_mil,
    eirp.co_fertimin_reel,
    eirp.co_epandage_orga_std_mil,
    eirp.co_epandage_orga_reelles,
    eirp.co_decomposees_std_mil_tx_comp,
    eirp.co_decomposees_std_mil_chp_non_rens,
    eirp.co_decomposees_reel_tx_comp,
    eirp.co_decomposees_reel_chp_non_rens,
    eirp.cm_std_mil_tx_comp,
    eirp.cm_std_mil_chmps_non_rens,
    eirp.cm_std_mil,
    eirp.cm_reelles_tx_comp,
    eirp.cm_reelles,
    eirp.cm_reel_chmps_non_rens,
    eirp.c_main_oeuvre_tractoriste_std_mil_tx_comp,
    eirp.c_main_oeuvre_tractoriste_std_mil_chmps_non_rens,
    eirp.c_main_oeuvre_tractoriste_std_mil,
    eirp.c_main_oeuvre_tractoriste_reelle_tx_comp,
    eirp.c_main_oeuvre_tractoriste_reelle_chmps_non_rens,
    eirp.c_main_oeuvre_tractoriste_reelle,
    eirp.c_main_oeuvre_tot_std_mil_tx_comp,
    eirp.c_main_oeuvre_tot_std_mil_chmps_non_rens,
    eirp.c_main_oeuvre_tot_std_mil,
    eirp.c_main_oeuvre_tot_reelle_tx_comp,
    eirp.c_main_oeuvre_tot_reelle_chmps_non_rens,
    eirp.c_main_oeuvre_tot_reelle,
    eirp.c_main_oeuvre_manuelle_std_mil_tx_comp,
    eirp.c_main_oeuvre_manuelle_std_mil_chmps_non_rens,
    eirp.c_main_oeuvre_manuelle_std_mil,
    eirp.c_main_oeuvre_manuelle_reelle_tx_comp,
    eirp.c_main_oeuvre_manuelle_reelle_chmps_non_rens,
    eirp.c_main_oeuvre_manuelle_reelle,
    eirp.surface_par_unite_de_travail_humain as surf_unite_de_w_humain,
	eirp.surface_par_unite_de_travail_humain_taux_de_completion as surf_unite_de_w_humain_tx_comp,
	eirp.surface_par_unite_de_travail_humain_detail_champs_non_renseig as surf_unite_de_w_hum_chp_non_rens,
   	sdc_context.domaine_nom,
   	sdc_context.domaine_id,
   	sdc_context.domaine_campagne,
   	sdc_context.domaine_type,
   	sdc_context.domaine_departement as departement,
   	sdc_context.dispositif_id,
   	sdc_context.dispositif_type,
   	sdc_context.nom_reseau_it,
   	sdc_context.nom_reseau_ir,
   	sdc_context.sdc_filiere,
   	sdc_context.sdc_nom,
   	sdc_context.sdc_id,
   	eirma.parcelle_id,
    ep.nom as parcelle_nom,
   	ez.nom as zone_nom,
   	eirma.zone_id,
   	sdc_context.sdc_num_dephy as sdc_code_dephy, 
    sdc_context.sdc_modalite_suivi_dephy as sdc_modalite_suivi_dephy,
   	sdc_context.sdc_valide,
   	sdc_context.sdc_type_conduite as sdc_type_agriculture,
   	ec.nom as culture_nom,
   	ec.id as culture_id, 
    ec.code as culture_code,
   	ens.rang+1 as culture_rang,
    ecoc.complet_espece_edi_nettoye as culture_especes_edi,
    ecoc.variete_nom,
    eiroc.precedent_nom as precedent_nom,
    eiroc.precedent_id as precedent_id,
    epppr.type as phase,
    epppr.id as phase_id,
    eis.nom as intervention_nom,
    eis.id as intervention_id,
    to_char(eis.date_debut, 'DD/MM/YYYY') as date_debut,
    to_char(eis.date_debut, 'DD/MM/YYYY') as date_fin,
    eiroc.interventions_actions,
    eiroc.interventions_intrants,
    eiroc.interventions_cibles_trait,
    ez.surface as zonearea,
    eiroc.esp as especes_intervention,
    eiroc.var as varietes_intervention, 
    eiroc.rendement_total,
    eiroc.nb_intrants,
    eirma.plantation_perenne_realise_id as plantation_id
from entrepot_intervention_realise_performance eirp
join  entrepot_intervention_realise_outils_can eiroc on eiroc.id = eirp.intervention_realise_id
join entrepot_intervention_realise eis on eiroc.id = eis.id
join entrepot_intervention_realise_agrege eirma on eirma.id = eirp.intervention_realise_id 
join entrepot_zone ez on ez.id = eirma.zone_id
join entrepot_parcelle ep on ep.id = ez.parcelle_id
join entrepot_context_performance_sdc sdc_context on eirma.sdc_id = sdc_context.sdc_id
left join entrepot_noeuds_realise ens on ens.id = eirma.noeuds_realise_id
join entrepot_culture ec on ec.id = eirma.culture_id -- on utilise l'information dans le df agrégé pour avoir le cas à la fois des perennes et des assolées
join entrepot_culture_outils_can ecoc on ec.id = ecoc.id
left join entrepot_plantation_perenne_phases_realise epppr ON epppr.id = CAST(eirma.plantation_perenne_phases_realise_id AS VARCHAR)
left join entrepot_plantation_perenne_realise epps  ON CAST(eirma.plantation_perenne_realise_id AS VARCHAR) = epps.id;