SELECT
    eisp.intervention_synthetise_id,
    eisp.approche_de_calcul,
    eisp.ift_histo_chimique_tot,
    eisp.ift_histo_chim_tot_hts,
    eisp.ift_histo_h,
    eisp.ift_histo_f,
    eisp.ift_histo_i,
    eisp.ift_histo_ts,
    eisp.ift_histo_a,
    eisp.ift_histo_hh,
    eisp.ift_histo_biocontrole,
    eisp.ift_histo_tx_comp,
    eisp.ift_histo_chmps_non_rens,
    eisp.ift_cible_non_mil_chimique_tot,
    eisp.ift_cible_non_mil_chim_tot_hts,
    eisp.ift_cible_non_mil_h,
    eisp.ift_cible_non_mil_f,
    eisp.ift_cible_non_mil_i,
    eisp.ift_cible_non_mil_ts,
    eisp.ift_cible_non_mil_a,
    eisp.ift_cible_non_mil_hh,
    eisp.ift_cible_non_mil_biocontrole,
    eisp.ift_cible_non_mil_tx_comp,
    eisp.ift_cible_non_mil_chmps_non_rens,
    eisp.ift_cible_mil_chimique_tot,
    eisp.ift_cible_mil_chim_tot_hts,
    eisp.ift_cible_mil_h,
    eisp.ift_cible_mil_f,
    eisp.ift_cible_mil_i,
    eisp.ift_cible_mil_ts,
    eisp.ift_cible_mil_a,
    eisp.ift_cible_mil_hh,
    eisp.ift_cible_mil_biocontrole,
    eisp.ift_cible_mil_tx_comp,
    eisp.ift_cible_mil_chmps_non_rens,
    eisp.ift_culture_non_mil_chimique_tot,
    eisp.ift_culture_non_mil_chim_tot_hts,
    eisp.ift_culture_non_mil_h,
    eisp.ift_culture_non_mil_f,
    eisp.ift_culture_non_mil_i,
    eisp.ift_culture_non_mil_ts,
    eisp.ift_culture_non_mil_a,
    eisp.ift_culture_non_mil_hh,
    eisp.ift_culture_non_mil_biocontrole,
    eisp.ift_culture_non_mil_tx_comp,
    eisp.ift_culture_non_mil_chmp_no_rens,
    eisp.ift_culture_mil_chimique_tot,
    eisp.ift_culture_mil_chim_tot_hts,
    eisp.ift_culture_mil_h,
    eisp.ift_culture_mil_f,
    eisp.ift_culture_mil_i,
    eisp.ift_culture_mil_ts,
    eisp.ift_culture_mil_a,
    eisp.ift_culture_mil_hh,
    eisp.ift_culture_mil_biocontrole,
    eisp.ift_culture_mil_tx_comp,
    eisp.ift_culture_mil_chmps_non_rens,
    eisp.recours_aux_moyens_biologiques,
    eisp.recours_macroorganismes,
    eisp.recours_produits_biotiques_sansamm,
    eisp.recours_produits_abiotiques_sansamm,
    eisp.tps_utilisation_materiel_janvier,
    eisp.tps_utilisation_materiel_fevrier,
    eisp.tps_utilisation_materiel_mars,
    eisp.tps_utilisation_materiel_avril,
    eisp.tps_utilisation_materiel_mai,
    eisp.tps_utilisation_materiel_juin,
    eisp.tps_utilisation_materiel_juillet,
    eisp.tps_utilisation_materiel_aout,
    eisp.tps_utilisation_materiel_sept,
    eisp.tps_utilisation_materiel_oct,
    eisp.tps_utilisation_materiel_nov,
    eisp.tps_utilisation_materiel_dec,
    eisp.tps_utilisation_materiel,
    eisp.tps_utilisation_materiel_tx_comp,
    eisp.tps_util_materiel_chmps_non_rens,
    eisp.tps_travail_manuel_janvier,
    eisp.tps_travail_manuel_fevrier,
    eisp.tps_travail_manuel_mars,
    eisp.tps_travail_manuel_avril,
    eisp.tps_travail_manuel_mai,
    eisp.tps_travail_manuel_juin,
    eisp.tps_travail_manuel_juillet,
    eisp.tps_travail_manuel_aout,
    eisp.tps_travail_manuel_septembre,
    eisp.tps_travail_manuel_octobre,
    eisp.tps_travail_manuel_novembre,
    eisp.tps_travail_manuel_decembre,
    eisp.tps_travail_manuel,
    eisp.tps_travail_manuel_tx_comp,
    eisp.tps_trav_manuel_chmps_non_rens,
    eisp.tps_travail_mecanise_janvier,
    eisp.tps_travail_mecanise_fevrier,
    eisp.tps_travail_mecanise_mars,
    eisp.tps_travail_mecanise_avril,
    eisp.tps_travail_mecanise_mai,
    eisp.tps_travail_mecanise_juin,
    eisp.tps_travail_mecanise_juillet,
    eisp.tps_travail_mecanise_aout,
    eisp.tps_travail_mecanise_septembre,
    eisp.tps_travail_mecanise_octobre,
    eisp.tps_travail_mecanise_novembre,
    eisp.tps_travail_mecanise_decembre,
    eisp.tps_travail_mecanise,
    eisp.tps_travail_mecanise_tx_comp,
    eisp.tps_trav_mecanise_chmps_non_rens,
    eisp.tps_travail_total_janvier,
    eisp.tps_travail_total_fevrier,
    eisp.tps_travail_total_mars,
    eisp.tps_travail_total_avril,
    eisp.tps_travail_total_mai,
    eisp.tps_travail_total_juin,
    eisp.tps_travail_total_juillet,
    eisp.tps_travail_total_aout,
    eisp.tps_travail_total_septembre,
    eisp.tps_travail_total_octobre,
    eisp.tps_travail_total_novembre,
    eisp.tps_travail_total_decembre,
    eisp.tps_travail_total,
    eisp.tps_travail_total_tx_comp,
    eisp.tps_trav_total_chmps_non_rens,
    eisp.nbre_de_passages_janvier,
    eisp.nbre_de_passages_fevrier,
    eisp.nbre_de_passages_mars,
    eisp.nbre_de_passages_avril,
    eisp.nbre_de_passages_mai,
    eisp.nbre_de_passages_juin,
    eisp.nbre_de_passages_juillet,
    eisp.nbre_de_passages_aout,
    eisp.nbre_de_passages_septembre,
    eisp.nbre_de_passages_octobre,
    eisp.nbre_de_passages_novembre,
    eisp.nbre_de_passages_decembre,
    eisp.nbre_de_passages,
    eisp.nbre_de_passages_tx_comp,
    eisp.nbre_de_passages_chmps_non_rens,
    eisp.nbre_de_passages_labour,
    eisp.nbre_de_passages_labour_tx_comp,
    eisp.nbre_de_passages_labour_chmps_non_rens,
    eisp.nbre_de_passages_tcs,
    eisp.nbre_de_passages_tcs_tx_comp,
    eisp.nbre_de_passages_tcs_chmps_non_rens,
    eisp.nbre_de_passages_desherbage_meca,
    eisp.nbre_de_passages_desherbage_meca_tx_comp,
    eisp.nbre_de_passages_desherbage_meca_chmps_non_rens,
    CASE CAST(eisp.utili_desherbage_meca AS BOOLEAN) WHEN true THEN 'oui' WHEN false THEN 'non' END utili_desherbage_meca,
    eisp.utili_desherbage_meca_tx_comp,
    eisp.utili_desherbage_meca_chmps_non_rens,
    eisp.type_de_travail_du_sol,
    eisp.type_de_travail_du_sol_tx_comp,
    eisp.type_de_travail_du_sol_chmps_non_rens,
    eisp.co_tot_reelles,
    eisp.co_tot_reelles_tx_comp,
    eisp.co_tot_reell_chmps_non_rens,
    eisp.co_tot_std_mil,
    eisp.co_tot_std_mil_tx_comp,
    eisp.co_tot_std_mil_chp_non_rens,
    eisp.co_semis_reel,
    eisp.co_semis_std_mil,
    eisp.co_fertimin_reel,
    eisp.co_fertimin_std_mil,
    eisp.co_epandage_orga_reelles,
    eisp.co_epandage_orga_std_mil,
    eisp.co_phyto_sans_amm_reelles,
    eisp.co_phyto_sans_amm_std_mil,
    eisp.co_phyto_avec_amm_reelles,
    eisp.co_phyto_avec_amm_std_mil,
    eisp.co_trait_semence_reelles,
    eisp.co_trait_semence_std_mil,
    eisp.co_irrigation_reelles,
    eisp.co_irrigation_std_mil,
    eisp.co_substrats_reelles,
    eisp.co_substrats_std_mil,
    eisp.co_pots_reelles,
    eisp.co_pots_std_mil,
    eisp.co_intrants_autres_reelles,
    eisp.co_intrants_autres_std_mil,
    eisp.co_decomposees_reel_tx_comp,
    eisp.co_decomposees_std_mil_tx_comp,
    eisp.co_decomposees_reel_chp_non_rens,
    eisp.co_decomposees_std_mil_chp_non_rens,
    eisp.cm_reelles,
    eisp.cm_reelles_tx_comp,
    eisp.cm_reel_chmps_non_rens,
    eisp.cm_std_mil,
    eisp.cm_std_mil_tx_comp,
    eisp.cm_std_mil_chmps_non_rens,
    eisp.c_main_oeuvre_tot_reelle,
    eisp.c_main_oeuvre_tot_reelle_tx_comp,
    eisp.c_main_oeuvre_tot_reelle_chmps_non_rens,
    eisp.c_main_oeuvre_tot_std_mil,
    eisp.c_main_oeuvre_tot_std_mil_tx_comp,
    eisp.c_main_oeuvre_tot_std_mil_chmps_non_rens,
    eisp.c_main_oeuvre_tractoriste_reelle,
    eisp.c_main_oeuvre_tractoriste_reelle_tx_comp,
    eisp.c_main_oeuvre_tractoriste_reelle_chmps_non_rens,
    eisp.c_main_oeuvre_tractoriste_std_mil,
    eisp.c_main_oeuvre_tractoriste_std_mil_tx_comp,
    eisp.c_main_oeuvre_tractoriste_std_mil_chmps_non_rens,
    eisp.c_main_oeuvre_manuelle_reelle,
    eisp.c_main_oeuvre_manuelle_reelle_tx_comp,
    eisp.c_main_oeuvre_manuelle_reelle_chmps_non_rens,
    eisp.c_main_oeuvre_manuelle_std_mil,
    eisp.c_main_oeuvre_manuelle_std_mil_tx_comp,
    eisp.c_main_oeuvre_manuelle_std_mil_chmps_non_rens,
    eisp.conso_carburant,
    eisp.conso_carburant_tx_comp,
    eisp.conso_carburant_chmps_non_rens,
    eisp.conso_eau,
    eisp.conso_eau_tx_comp,
    eisp.conso_eau_chmps_non_rens,
    eisp.ferti_n_tot,
    eisp.ferti_n_mineral,
    eisp.ferti_n_organique,
    eisp.ferti_p2o5_tot,
    eisp.ferti_p2o5_mineral,
    eisp.ferti_p2o5_organique,
    eisp.ferti_k2o_tot,
    eisp.ferti_k2o_mineral,
    eisp.ferti_k2o_organique,
    eisp.ferti_ca_mineral,
    eisp.ferti_cao_organique,
    eisp.ferti_mgo_mineral,
    eisp.ferti_mgo_organique,
    eisp.ferti_so3_mineral,
    eisp.ferti_s_organique,
    eisp.ferti_b_mineral,
    eisp.ferti_cu_mineral,
    eisp.ferti_fe_mineral,
    eisp.ferti_mn_mineral,
    eisp.ferti_mo_mineral,
    eisp.ferti_na2o_mineral,
    eisp.ferti_zn_mineral,
    eisp.hri1_tot,
    eisp.hri1_hts,
    eisp.hri1_tot_taux_de_completion,
    eisp.hri1_tot_detail_champs_non_renseig,
    eisp.hri1_g1_tot,
    eisp.hri1_g1_hts,
    eisp.hri1_g1_tot_taux_de_completion,
    eisp.hri1_g1_tot_detail_champs_non_renseig,
    eisp.hri1_g2_tot,
    eisp.hri1_g2_hts,
    eisp.hri1_g2_tot_taux_de_completion,
    eisp.hri1_g2_tot_detail_champs_non_renseig,
    eisp.hri1_g3_tot,
    eisp.hri1_g3_hts,
    eisp.hri1_g3_tot_taux_de_completion,
    eisp.hri1_g3_tot_detail_champs_non_renseig,
    eisp.hri1_g4_tot,
    eisp.hri1_g4_hts,
    eisp.hri1_g4_tot_taux_de_completion,
    eisp.hri1_g4_tot_detail_champs_non_renseig,
    eisp.qsa_tot,
    eisp.qsa_tot_hts,
    eisp.qsa_tot_taux_de_completion,
    eisp.qsa_tot_detail_champs_non_renseig,
    eisp.qsa_danger_environnement,
    eisp.qsa_danger_environnement_hts,
    eisp.qsa_toxique_utilisateur,
    eisp.qsa_toxique_utilisateur_hts,
    eisp.qsa_cmr,
    eisp.qsa_cmr_hts,
    eisp.qsa_substances_candidates_substitution,
    eisp.qsa_substances_candidates_substitution_hts,
    eisp.qsa_substances_faible_risque,
    eisp.qsa_substances_faible_risque_hts,
    eisp.qsa_glyphosate,
    eisp.qsa_glyphosate_hts,
    eisp.qsa_chlortoluron,
    eisp.qsa_chlortoluron_hts,
    eisp.qsa_diflufenican,
    eisp.qsa_diflufenican_hts,
    eisp.qsa_prosulfocarbe,
    eisp.qsa_prosulfocarbe_hts,
    eisp.qsa_smetolachlore,
    eisp.qsa_smetolachlore_hts,
    eisp.qsa_boscalid,
    eisp.qsa_boscalid_hts,
    eisp.qsa_fluopyram,
    eisp.qsa_fluopyram_hts,
    eisp.qsa_lambda_cyhalothrine,
    eisp.qsa_lambda_cyhalothrine_hts,
    eisp.qsa_cuivre_tot,
    eisp.qsa_cuivre_tot_hts,
    eisp.qsa_cuivre_phyto,
    eisp.qsa_cuivre_phyto_hts,
    eisp.qsa_cuivre_ferti,
    eisp.qsa_soufre_tot,
    eisp.qsa_soufre_tot_hts,
    eisp.qsa_soufre_phyto,
    eisp.qsa_soufre_phyto_hts,
    eisp.qsa_soufre_ferti,
    eisp.surface_par_unite_de_travail_humain as surf_unite_de_w_humain,
	  eisp.surface_par_unite_de_travail_humain_taux_de_completion as surf_unite_de_w_humain_tx_comp,
	  eisp.surface_par_unite_de_travail_humain_detail_champs_non_renseig as surf_unite_de_w_hum_chp_non_rens,
   	sdc_context.domaine_nom,
   	sdc_context.domaine_id,
   	sdc_context.domaine_campagne,
   	sdc_context.domaine_type,
   	sdc_context.domaine_departement as departement,
   	sdc_context.dispositif_id,
   	sdc_context.dispositif_type,
   	sdc_context.nom_reseau_it,
   	sdc_context.nom_reseau_ir,
   	sdc_context.sdc_nom,
   	sdc_context.sdc_id,
   	sdc_context.sdc_num_dephy as sdc_code_dephy, 
   	sdc_context.sdc_filiere,
   	sdc_context.sdc_valide,
   	sdc_context.sdc_type_conduite as sdc_type_agriculture,
    es.nom as systeme_synthetise_nom,
    CASE CAST(es.valide AS BOOLEAN) WHEN true THEN 'oui' WHEN false THEN 'non' END synthetise_valide,
  	es.campagnes as synthetise_campagnes,
  	ec_intermediaire.id as culture_id, -- il ne s'agit pas forcément de la culture intermediaire.
    ec_intermediaire.nom as culture_nom, 
    ec_intermediaire.code as culture_code,
    ens.rang as culture_rang,
    ecoc.complet_espece_edi_nettoye as culture_especes_edi,
    ecoc.variete_nom,
    eisoc.precedent_nom as precedent_nom,
    eisoc.precedent_code as precedent_code,
    eppps.type as phase,
    eppps.id as phase_id,
    epps.pct_occupation_sol as pourcentage_sole_sdc,
    eis.nom as intervention_nom,
    eis.id as intervention_id,
    eis.date_debut,
    eis.date_fin,
    eisoc.interventions_actions,
    eisoc.interventions_intrants,
    eisoc.interventions_cibles_trait,
    eisoc.precedent_id as precedent_id,
    eisoc.esp as especes_intervention,
    eisoc.var as varietes_intervention, 
    eisoc.rendement_total,
    eisoc.nb_intrants,
    eisoc.interventions_groupe_cible,
    eisoc.biocontrole,
    eismae.synthetise_id as systeme_synthetise_id,
    eismae.plantation_perenne_synthetise_id as plantation_id,
    eismae.cible_noeuds_synthetise_id as noeuds_synthetise_id
from entrepot_intervention_synthetise_performance eisp
join  entrepot_intervention_synthetise_outils_can eisoc on eisoc.id = eisp.intervention_synthetise_id
join entrepot_intervention_synthetise eis on eisoc.id = eis.id
join entrepot_intervention_synthetise_agrege_extanded eismae on eismae.id = eisp.intervention_synthetise_id 
join entrepot_synthetise es on es.id = eismae.synthetise_id
join entrepot_context_performance_sdc sdc_context on eismae.sdc_id = sdc_context.sdc_id
left join entrepot_noeuds_synthetise ens on ens.id = eismae.cible_noeuds_synthetise_id
left join entrepot_plantation_perenne_phases_synthetise eppps on eppps.id = CAST(eismae.plantation_perenne_phases_synthetise_id AS VARCHAR)
left join entrepot_plantation_perenne_synthetise epps on CAST(eismae.plantation_perenne_synthetise_id AS VARCHAR)= epps.id
join entrepot_culture ec on ec.id = eismae.culture_id
join entrepot_culture_outils_can ecoc on ecoc.id = ec.id
left join entrepot_culture ec_intermediaire on ec_intermediaire.id = eisoc.culture_id; -- on récupère les infos car la culture n'est pas forcément la culture principale 