select 
	eirp.culture_id,
	eirp.zone_id,
	eirp.ift_histo_chimique_tot,
	eirp.ift_histo_chim_tot_hts,
	eirp.ift_histo_h,
	eirp.ift_histo_f,
	eirp.ift_histo_i,
	eirp.ift_histo_ts,
	eirp.ift_histo_a,
	eirp.ift_histo_hh,
	eirp.ift_histo_biocontrole,
	eirp.ift_histo_tx_comp,
	eirp.ift_cible_non_mil_chimique_tot,
	eirp.ift_cible_non_mil_chim_tot_hts,
	eirp.ift_cible_non_mil_h,
	eirp.ift_cible_non_mil_f,
	eirp.ift_cible_non_mil_i,
	eirp.ift_cible_non_mil_ts,
	eirp.ift_cible_non_mil_a,
	eirp.ift_cible_non_mil_hh,
	eirp.ift_cible_non_mil_biocontrole,
	eirp.ift_cible_non_mil_tx_comp,
	eirp.ift_cible_mil_chimique_tot,
	eirp.ift_cible_mil_chim_tot_hts,
	eirp.ift_cible_mil_h,
	eirp.ift_cible_mil_f,
	eirp.ift_cible_mil_i,
	eirp.ift_cible_mil_ts,
	eirp.ift_cible_mil_a,
	eirp.ift_cible_mil_hh,
	eirp.ift_cible_mil_biocontrole,
	eirp.ift_cible_mil_tx_comp,
	eirp.ift_culture_non_mil_chimique_tot,
	eirp.ift_culture_non_mil_chim_tot_hts,
	eirp.ift_culture_non_mil_h,
	eirp.ift_culture_non_mil_f,
	eirp.ift_culture_non_mil_i,
	eirp.ift_culture_non_mil_ts,
	eirp.ift_culture_non_mil_a,
	eirp.ift_culture_non_mil_hh,
	eirp.ift_culture_non_mil_biocontrole,
	eirp.ift_culture_non_mil_tx_comp,
	eirp.ift_culture_mil_chimique_tot,
	eirp.ift_culture_mil_chim_tot_hts,
	eirp.ift_culture_mil_h,
	eirp.ift_culture_mil_f,
	eirp.ift_culture_mil_i,
	eirp.ift_culture_mil_ts,
	eirp.ift_culture_mil_a,
	eirp.ift_culture_mil_hh,
	eirp.ift_culture_mil_biocontrole,
	eirp.ift_culture_mil_tx_comp,
	eirp.recours_aux_moyens_biologiques,
	eirp.recours_macroorganismes,
	eirp.recours_produits_biotiques_sansamm,
	eirp.recours_produits_abiotiques_sansamm,
	eirp.co_tot_reelles,
	eirp.co_tot_reelles_tx_comp,
	eirp.co_tot_std_mil,
	eirp.co_tot_std_mil_tx_comp,
	eirp.co_semis_reel,
	eirp.co_semis_std_mil,
	eirp.co_fertimin_reel,
	eirp.co_fertimin_std_mil,
	eirp.co_epandage_orga_reelles,
	eirp.co_epandage_orga_std_mil,
	eirp.co_phyto_sans_amm_reelles,
	eirp.co_phyto_sans_amm_std_mil,
	eirp.co_phyto_avec_amm_reelles,
	eirp.co_phyto_avec_amm_std_mil,
	eirp.co_trait_semence_reelles,
	eirp.co_trait_semence_std_mil,
	eirp.co_irrigation_reelles,
	eirp.co_irrigation_std_mil,
	eirp.co_substrats_reelles,
	eirp.co_substrats_std_mil,
	eirp.co_pots_reelles,
	eirp.co_pots_std_mil,
	eirp.co_intrants_autres_reelles,
	eirp.co_intrants_autres_std_mil,
	eirp.co_decomposees_reel_tx_comp,
	eirp.co_decomposees_std_mil_tx_comp,
	eirp.ferti_n_tot,
	eirp.ferti_n_mineral,
	eirp.ferti_n_organique,
	eirp.ferti_p2o5_tot,
	eirp.ferti_p2o5_mineral,
	eirp.ferti_p2o5_organique,
	eirp.ferti_k2o_tot,
	eirp.ferti_k2o_mineral,
	eirp.ferti_k2o_organique,
	eirp.ferti_ca_mineral,
	eirp.ferti_cao_organique,
	eirp.ferti_mgo_mineral,
	eirp.ferti_mgo_organique,
	eirp.ferti_so3_mineral,
	eirp.ferti_s_organique,
	eirp.ferti_b_mineral,
	eirp.ferti_cu_mineral,
	eirp.ferti_fe_mineral,
	eirp.ferti_mn_mineral,
	eirp.ferti_mo_mineral,
	eirp.ferti_na2o_mineral,
	eirp.ferti_zn_mineral,
	eirp.hri1_tot,
	eirp.hri1_hts,
	eirp.hri1_tot_taux_de_completion,
	eirp.hri1_g1_tot,
	eirp.hri1_g1_hts,
	eirp.hri1_g1_tot_taux_de_completion,
	eirp.hri1_g2_tot,
	eirp.hri1_g2_hts,
	eirp.hri1_g2_tot_taux_de_completion,
	eirp.hri1_g3_tot,
	eirp.hri1_g3_hts,
	eirp.hri1_g3_tot_taux_de_completion,
	eirp.hri1_g4_tot,
	eirp.hri1_g4_hts,
	eirp.hri1_g4_tot_taux_de_completion,
	eirp.qsa_tot,
	eirp.qsa_tot_hts,
	eirp.qsa_tot_taux_de_completion,
	eirp.qsa_danger_environnement,
	eirp.qsa_danger_environnement_hts,
	eirp.qsa_toxique_utilisateur,
	eirp.qsa_toxique_utilisateur_hts,
	eirp.qsa_cmr,
	eirp.qsa_cmr_hts,
	eirp.qsa_substances_candidates_substitution,
	eirp.qsa_substances_candidates_substitution_hts,
	eirp.qsa_substances_faible_risque,
	eirp.qsa_substances_faible_risque_hts,
	eirp.qsa_glyphosate,
	eirp.qsa_glyphosate_hts,
	eirp.qsa_chlortoluron,
	eirp.qsa_chlortoluron_hts,
	eirp.qsa_diflufenican,
	eirp.qsa_diflufenican_hts,
	eirp.qsa_prosulfocarbe,
	eirp.qsa_prosulfocarbe_hts,
	eirp.qsa_smetolachlore,
	eirp.qsa_smetolachlore_hts,
	eirp.qsa_boscalid,
	eirp.qsa_boscalid_hts,
	eirp.qsa_fluopyram,
	eirp.qsa_fluopyram_hts,
	eirp.qsa_lambda_cyhalothrine,
	eirp.qsa_lambda_cyhalothrine_hts,
	eirp.qsa_cuivre_metal_tot AS qsa_cuivre_tot,
	eirp.qsa_cuivre_metal_tot_hts AS qsa_cuivre_tot_hts,
	eirp.qsa_cuivre_phyto,
	eirp.qsa_cuivre_phyto_hts,
	eirp.qsa_cuivre_metal_ferti AS qsa_cuivre_ferti,
	eirp.qsa_soufre_tot,
	eirp.qsa_soufre_tot_hts,
	eirp.qsa_soufre_phyto,
	eirp.qsa_soufre_phyto_hts,
	eirp.qsa_soufre_ferti,
	ecps.domaine_nom,
	ecps.domaine_id,
	ecps.domaine_campagne,
	ecps.domaine_type,
	ecps.domaine_departement as departement,
	ecps.nom_reseau_it,
	ecps.nom_reseau_ir,
	ecps.dispositif_id,
	ecps.dispositif_type,
	ecps.sdc_filiere,
	ecps.sdc_nom,
	ecps.sdc_id,
	ep.nom as parcelle_nom, 
	ep.id as parcelle_id, 
	ez.nom as zone_nom,
	sdc_num_dephy as sdc_code_dephy,
	sdc_type_conduite as sdc_type_agriculture,
	sdc_valide,
	ec.nom as culture_nom, 
	ec.code as culture_code,
	enr.rang as culture_rang,
	ecoc.complet_espece_edi as culture_especes_edi,
	ecoc.variete_nom, 
	ec_prec.nom as precedent_nom, 
	ec_prec.id as precedent_id,
	ec_prec.code as precedent_code,
	epppr."type" as phase,
	epppr.id as phase_id
from entrepot_itk_realise_performance eirp
left join entrepot_culture_outils_can ecoc on eirp.culture_id = ecoc.id
left join entrepot_noeuds_realise enr on (enr.culture_id = eirp.culture_id and enr.zone_id = eirp.zone_id)
left join entrepot_plantation_perenne_realise eppr on (enr.culture_id = eppr.culture_id and enr.zone_id = eppr.zone_id)
left join entrepot_plantation_perenne_phases_realise epppr on (epppr.plantation_perenne_realise_id = eppr.id and eirp.plantation_perenne_phases_realise_id = epppr.id)
left join entrepot_culture ec on ec.id = eirp.culture_id 
left join entrepot_zone ez on ez.id = eirp.zone_id
left join entrepot_parcelle ep on ep.id = ez.parcelle_id
join entrepot_context_performance_sdc ecps on ecps.sdc_id = ep.sdc_id
left join entrepot_connection_realise ecr on ecr.cible_noeuds_realise_id = enr.id
left join entrepot_noeuds_realise enr_prec on enr_prec.id = ecr.source_noeuds_realise_id
left join entrepot_culture ec_prec on enr_prec.culture_id = ec_prec.id
UNION ALL
select --requête spécifique aux parcelles non rattachées 
	eirp.culture_id,
	eirp.zone_id,
	eirp.ift_histo_chimique_tot,
	eirp.ift_histo_chim_tot_hts,
	eirp.ift_histo_h,
	eirp.ift_histo_f,
	eirp.ift_histo_i,
	eirp.ift_histo_ts,
	eirp.ift_histo_a,
	eirp.ift_histo_hh,
	eirp.ift_histo_biocontrole,
	eirp.ift_histo_tx_comp,
	eirp.ift_cible_non_mil_chimique_tot,
	eirp.ift_cible_non_mil_chim_tot_hts,
	eirp.ift_cible_non_mil_h,
	eirp.ift_cible_non_mil_f,
	eirp.ift_cible_non_mil_i,
	eirp.ift_cible_non_mil_ts,
	eirp.ift_cible_non_mil_a,
	eirp.ift_cible_non_mil_hh,
	eirp.ift_cible_non_mil_biocontrole,
	eirp.ift_cible_non_mil_tx_comp,
	eirp.ift_cible_mil_chimique_tot,
	eirp.ift_cible_mil_chim_tot_hts,
	eirp.ift_cible_mil_h,
	eirp.ift_cible_mil_f,
	eirp.ift_cible_mil_i,
	eirp.ift_cible_mil_ts,
	eirp.ift_cible_mil_a,
	eirp.ift_cible_mil_hh,
	eirp.ift_cible_mil_biocontrole,
	eirp.ift_cible_mil_tx_comp,
	eirp.ift_culture_non_mil_chimique_tot,
	eirp.ift_culture_non_mil_chim_tot_hts,
	eirp.ift_culture_non_mil_h,
	eirp.ift_culture_non_mil_f,
	eirp.ift_culture_non_mil_i,
	eirp.ift_culture_non_mil_ts,
	eirp.ift_culture_non_mil_a,
	eirp.ift_culture_non_mil_hh,
	eirp.ift_culture_non_mil_biocontrole,
	eirp.ift_culture_non_mil_tx_comp,
	eirp.ift_culture_mil_chimique_tot,
	eirp.ift_culture_mil_chim_tot_hts,
	eirp.ift_culture_mil_h,
	eirp.ift_culture_mil_f,
	eirp.ift_culture_mil_i,
	eirp.ift_culture_mil_ts,
	eirp.ift_culture_mil_a,
	eirp.ift_culture_mil_hh,
	eirp.ift_culture_mil_biocontrole,
	eirp.ift_culture_mil_tx_comp,
	eirp.recours_aux_moyens_biologiques,
	eirp.recours_macroorganismes,
	eirp.recours_produits_biotiques_sansamm,
	eirp.recours_produits_abiotiques_sansamm,
	eirp.co_tot_reelles,
	eirp.co_tot_reelles_tx_comp,
	eirp.co_tot_std_mil,
	eirp.co_tot_std_mil_tx_comp,
	eirp.co_semis_reel,
	eirp.co_semis_std_mil,
	eirp.co_fertimin_reel,
	eirp.co_fertimin_std_mil,
	eirp.co_epandage_orga_reelles,
	eirp.co_epandage_orga_std_mil,
	eirp.co_phyto_sans_amm_reelles,
	eirp.co_phyto_sans_amm_std_mil,
	eirp.co_phyto_avec_amm_reelles,
	eirp.co_phyto_avec_amm_std_mil,
	eirp.co_trait_semence_reelles,
	eirp.co_trait_semence_std_mil,
	eirp.co_irrigation_reelles,
	eirp.co_irrigation_std_mil,
	eirp.co_substrats_reelles,
	eirp.co_substrats_std_mil,
	eirp.co_pots_reelles,
	eirp.co_pots_std_mil,
	eirp.co_intrants_autres_reelles,
	eirp.co_intrants_autres_std_mil,
	eirp.co_decomposees_reel_tx_comp,
	eirp.co_decomposees_std_mil_tx_comp,
	eirp.ferti_n_tot,
	eirp.ferti_n_mineral,
	eirp.ferti_n_organique,
	eirp.ferti_p2o5_tot,
	eirp.ferti_p2o5_mineral,
	eirp.ferti_p2o5_organique,
	eirp.ferti_k2o_tot,
	eirp.ferti_k2o_mineral,
	eirp.ferti_k2o_organique,
	eirp.ferti_ca_mineral,
	eirp.ferti_cao_organique,
	eirp.ferti_mgo_mineral,
	eirp.ferti_mgo_organique,
	eirp.ferti_so3_mineral,
	eirp.ferti_s_organique,
	eirp.ferti_b_mineral,
	eirp.ferti_cu_mineral,
	eirp.ferti_fe_mineral,
	eirp.ferti_mn_mineral,
	eirp.ferti_mo_mineral,
	eirp.ferti_na2o_mineral,
	eirp.ferti_zn_mineral,
	eirp.hri1_tot,
	eirp.hri1_hts,
	eirp.hri1_tot_taux_de_completion,
	eirp.hri1_g1_tot,
	eirp.hri1_g1_hts,
	eirp.hri1_g1_tot_taux_de_completion,
	eirp.hri1_g2_tot,
	eirp.hri1_g2_hts,
	eirp.hri1_g2_tot_taux_de_completion,
	eirp.hri1_g3_tot,
	eirp.hri1_g3_hts,
	eirp.hri1_g3_tot_taux_de_completion,
	eirp.hri1_g4_tot,
	eirp.hri1_g4_hts,
	eirp.hri1_g4_tot_taux_de_completion,
	eirp.qsa_tot,
	eirp.qsa_tot_hts,
	eirp.qsa_tot_taux_de_completion,
	eirp.qsa_danger_environnement,
	eirp.qsa_danger_environnement_hts,
	eirp.qsa_toxique_utilisateur,
	eirp.qsa_toxique_utilisateur_hts,
	eirp.qsa_cmr,
	eirp.qsa_cmr_hts,
	eirp.qsa_substances_candidates_substitution,
	eirp.qsa_substances_candidates_substitution_hts,
	eirp.qsa_substances_faible_risque,
	eirp.qsa_substances_faible_risque_hts,
	eirp.qsa_glyphosate,
	eirp.qsa_glyphosate_hts,
	eirp.qsa_chlortoluron,
	eirp.qsa_chlortoluron_hts,
	eirp.qsa_diflufenican,
	eirp.qsa_diflufenican_hts,
	eirp.qsa_prosulfocarbe,
	eirp.qsa_prosulfocarbe_hts,
	eirp.qsa_smetolachlore,
	eirp.qsa_smetolachlore_hts,
	eirp.qsa_boscalid,
	eirp.qsa_boscalid_hts,
	eirp.qsa_fluopyram,
	eirp.qsa_fluopyram_hts,
	eirp.qsa_lambda_cyhalothrine,
	eirp.qsa_lambda_cyhalothrine_hts,
	eirp.qsa_cuivre_metal_tot AS qsa_cuivre_tot,
	eirp.qsa_cuivre_metal_tot_hts AS qsa_cuivre_tot_hts,
	eirp.qsa_cuivre_phyto,
	eirp.qsa_cuivre_phyto_hts,
	eirp.qsa_cuivre_metal_ferti AS qsa_cuivre_ferti,
	eirp.qsa_soufre_tot,
	eirp.qsa_soufre_tot_hts,
	eirp.qsa_soufre_phyto,
	eirp.qsa_soufre_phyto_hts,
	eirp.qsa_soufre_ferti,
	ed.nom as domaine_nom,
	ed.id as domaine_id,
	ed.campagne as domaine_campagne,
	ed.type_ferme as domaine_type,
	ed.departement as departement,
	null as nom_reseau_it,
	null as nom_reseau_ir,
	null as dispositif_id,
	null as dispositif_type,
	null as sdc_filiere,
	null as sdc_nom,
	null as sdc_id,
	ep.nom as parcelle_nom, 
	ep.id as parcelle_id, 
	ez.nom as zone_nom,
	null as sdc_code_dephy,
	null as sdc_type_agriculture,
	null as sdc_valide,
	ec.nom as culture_nom, 
	ec.code as culture_code,
	enr.rang as culture_rang,
	ecoc.complet_espece_edi as culture_especes_edi,
	ecoc.variete_nom, 
	ec_prec.nom as precedent_nom, 
	ec_prec.id as precedent_id,
	ec_prec.code as precedent_code,
	epppr."type" as phase,
	epppr.id as phase_id
from entrepot_itk_realise_performance eirp
left join entrepot_culture_outils_can ecoc on eirp.culture_id = ecoc.id
left join entrepot_noeuds_realise enr on (enr.culture_id = eirp.culture_id and enr.zone_id = eirp.zone_id)
left join entrepot_plantation_perenne_realise eppr on (enr.culture_id = eppr.culture_id and enr.zone_id = eppr.zone_id)
left join entrepot_plantation_perenne_phases_realise epppr on (epppr.plantation_perenne_realise_id = eppr.id and eirp.plantation_perenne_phases_realise_id = epppr.id)
left join entrepot_culture ec on ec.id = eirp.culture_id 
left join entrepot_zone ez on ez.id = eirp.zone_id
left join entrepot_parcelle ep on ep.id = ez.parcelle_id
left join entrepot_domaine ed on ep.domaine_id = ed.id
left join entrepot_connection_realise ecr on ecr.cible_noeuds_realise_id = enr.id
left join entrepot_noeuds_realise enr_prec on enr_prec.id = ecr.source_noeuds_realise_id
left join entrepot_culture ec_prec on enr_prec.culture_id = ec_prec.id
where ep.sdc_id is null;