-- SYNTHETISE 
select 
	euip.utilisation_intrant_id,
	euip.ift_histo_chimique_tot,
	euip.ift_histo_chim_tot_hts,
	euip.ift_histo_h,
	euip.ift_histo_f,
	euip.ift_histo_i,
	euip.ift_histo_ts,
	euip.ift_histo_a,
	euip.ift_histo_hh,
	euip.ift_histo_biocontrole,
	euip.ift_histo_tx_comp,
	euip.ift_histo_chmps_non_rens,
	euip.ift_histo_dose_ref,
	euip.ift_histo_dose_ref_unite,
	euip.ift_cible_non_mil_chimique_tot,
	euip.ift_cible_non_mil_chim_tot_hts,
	euip.ift_cible_non_mil_h,
	euip.ift_cible_non_mil_f,
	euip.ift_cible_non_mil_i,
	euip.ift_cible_non_mil_ts,
	euip.ift_cible_non_mil_a,
	euip.ift_cible_non_mil_hh,
	euip.ift_cible_non_mil_biocontrole,
	euip.ift_cible_non_mil_tx_comp,
	euip.ift_cible_non_mil_chmps_non_rens,
	euip.ift_cible_non_mil_dose_ref,
	euip.ift_cible_non_mil_dose_ref_unite,
	euip.ift_cible_mil_chimique_tot,
	euip.ift_cible_mil_chim_tot_hts,
	euip.ift_cible_mil_h,
	euip.ift_cible_mil_f,
	euip.ift_cible_mil_i,
	euip.ift_cible_mil_ts,
	euip.ift_cible_mil_a,
	euip.ift_cible_mil_hh,
	euip.ift_cible_mil_biocontrole,
	euip.ift_cible_mil_tx_comp,
	euip.ift_cible_mil_chmps_non_rens,
	euip.ift_cible_mil_dose_ref,
	euip.ift_cible_mil_dose_ref_unite,
	euip.ift_culture_non_mil_chimique_tot,
	euip.ift_culture_non_mil_chim_tot_hts,
	euip.ift_culture_non_mil_h,
	euip.ift_culture_non_mil_f,
	euip.ift_culture_non_mil_i,
	euip.ift_culture_non_mil_ts,
	euip.ift_culture_non_mil_a,
	euip.ift_culture_non_mil_hh,
	euip.ift_culture_non_mil_biocontrole,
	euip.ift_culture_non_mil_tx_comp,
	euip.ift_culture_non_mil_chmp_no_rens,
	euip.ift_culture_non_mil_dose_ref,
	euip.ift_culture_non_mil_dose_ref_unite,
	euip.ift_culture_mil_chimique_tot,
	euip.ift_culture_mil_chim_tot_hts,
	euip.ift_culture_mil_h,
	euip.ift_culture_mil_f,
	euip.ift_culture_mil_i,
	euip.ift_culture_mil_ts,
	euip.ift_culture_mil_a,
	euip.ift_culture_mil_hh,
	euip.ift_culture_mil_biocontrole,
	euip.ift_culture_mil_tx_comp,
	euip.ift_culture_mil_chmps_non_rens,
	euip.ift_culture_mil_dose_ref,
	euip.ift_culture_mil_dose_ref_unite,
	euip.recours_aux_moyens_biologiques,
	euip.recours_macroorganismes,
	euip.recours_produits_biotiques_sansamm,
	euip.recours_produits_abiotiques_sansamm,
	euip.co_tot_reelles,
	euip.co_tot_reelles_tx_comp,
	euip.co_tot_reell_chmps_non_rens,
	euip.co_tot_std_mil,
	euip.co_tot_std_mil_tx_comp,
	euip.co_tot_std_mil_chp_non_rens,
	euip.co_semis_reel,
	euip.co_semis_std_mil,
	euip.co_fertimin_reel,
	euip.co_fertimin_std_mil,
	euip.co_epandage_orga_reelles,
	euip.co_epandage_orga_std_mil,
	euip.co_phyto_sans_amm_reelles,
	euip.co_phyto_sans_amm_std_mil,
	euip.co_phyto_avec_amm_reelles,
	euip.co_phyto_avec_amm_std_mil,
	euip.co_trait_semence_reelles,
	euip.co_trait_semence_std_mil,
	euip.co_irrigation_reelles,
	euip.co_irrigation_std_mil,
	euip.co_substrats_reelles,
	euip.co_substrats_std_mil,
	euip.co_pots_reelles,
	euip.co_pots_std_mil,
	euip.co_intrants_autres_reelles,
	euip.co_intrants_autres_std_mil,
	euip.co_decomposees_reel_tx_comp,
	euip.co_decomposees_std_mil_tx_comp,
	euip.co_decomposees_reel_chp_non_rens,
	euip.co_decomposees_std_mil_chp_non_rens,
	euip.ferti_n_tot,
	euip.ferti_n_mineral,
	euip.ferti_n_organique,
	euip.ferti_p2o5_tot,
	euip.ferti_p2o5_mineral,
	euip.ferti_p2o5_organique,
	euip.ferti_k2o_tot,
	euip.ferti_k2o_mineral,
	euip.ferti_k2o_organique,
	euip.ferti_ca_mineral,
	euip.ferti_cao_organique,
	euip.ferti_mgo_mineral,
	euip.ferti_mgo_organique,
	euip.ferti_so3_mineral,
	euip.ferti_s_organique,
	euip.ferti_b_mineral,
	euip.ferti_cu_mineral,
	euip.ferti_fe_mineral,
	euip.ferti_mn_mineral,
	euip.ferti_mo_mineral,
	euip.ferti_na2o_mineral,
	euip.ferti_zn_mineral,
	euip.hri1_tot,
	euip.hri1_hts,
	euip.hri1_tot_taux_de_completion,
	euip.hri1_tot_detail_champs_non_renseig,
	euip.hri1_g1_tot,
	euip.hri1_g1_hts,
	euip.hri1_g1_tot_taux_de_completion,
	euip.hri1_g1_tot_detail_champs_non_renseig,
	euip.hri1_g2_tot,
	euip.hri1_g2_hts,
	euip.hri1_g2_tot_taux_de_completion,
	euip.hri1_g2_tot_detail_champs_non_renseig,
	euip.hri1_g3_tot,
	euip.hri1_g3_hts,
	euip.hri1_g3_tot_taux_de_completion,
	euip.hri1_g3_tot_detail_champs_non_renseig,
	euip.hri1_g4_tot,
	euip.hri1_g4_hts,
	euip.hri1_g4_tot_taux_de_completion,
	euip.hri1_g4_tot_detail_champs_non_renseig,
	euip.qsa_tot,
	euip.qsa_tot_hts,
	euip.qsa_tot_taux_de_completion,
	euip.qsa_tot_detail_champs_non_renseig,
	euip.qsa_danger_environnement,
	euip.qsa_danger_environnement_hts,
	euip.qsa_toxique_utilisateur,
	euip.qsa_toxique_utilisateur_hts,
	euip.qsa_cmr,
	euip.qsa_cmr_hts,
	euip.qsa_substances_candidates_substitution,
	euip.qsa_substances_candidates_substitution_hts,
	euip.qsa_substances_faible_risque,
	euip.qsa_substances_faible_risque_hts,
	euip.qsa_glyphosate,
	euip.qsa_glyphosate_hts,
	euip.qsa_chlortoluron,
	euip.qsa_chlortoluron_hts,
	euip.qsa_diflufenican,
	euip.qsa_diflufenican_hts,
	euip.qsa_prosulfocarbe,
	euip.qsa_prosulfocarbe_hts,
	euip.qsa_smetolachlore,
	euip.qsa_smetolachlore_hts,
	euip.qsa_boscalid,
	euip.qsa_boscalid_hts,
	euip.qsa_fluopyram,
	euip.qsa_fluopyram_hts,
	euip.qsa_lambda_cyhalothrine,
	euip.qsa_lambda_cyhalothrine_hts,
	eprp.qsa_cuivre_metal_tot as qsa_cuivre_tot,
	eprp.qsa_cuivre_metal_tot_hts as qsa_cuivre_tot_hts,
	eprp.qsa_cuivre_metal_phyto as qsa_cuivre_phyto,
	eprp.qsa_cuivre_metal_phyto_hts as qsa_cuivre_phyto_hts,
	eprp.qsa_cuivre_metal_ferti as qsa_cuivre_ferti,
	euip.qsa_soufre_tot,
	euip.qsa_soufre_tot_hts,
	euip.qsa_soufre_phyto,
	euip.qsa_soufre_phyto_hts,
	euip.qsa_soufre_ferti,
	sdc_context.domaine_nom as nom_domaine_exploitation,
	sdc_context.domaine_id as id_domaine, 
	sdc_context.domaine_campagne,
	sdc_context.domaine_type,
	sdc_context.domaine_departement as departement, 
	sdc_context.nom_reseau_it,
	sdc_context.nom_reseau_ir,
	sdc_context.dispositif_id,
	sdc_context.dispositif_type,
	sdc_context.sdc_id,
	sdc_context.sdc_filiere, 
	sdc_context.sdc_nom,
	sdc_context.sdc_num_dephy,
	sdc_context.sdc_type_conduite, 
	sdc_context.sdc_valide, 
	sdc_context.sdc_modalite_suivi_dephy, 
	es.nom as nom_systeme_synthetise,
	es.id as id_systeme_synthetise,
	es.valide as synthetise_valide,
	es.campagnes as synthetise_campagnes,
	null as parcelle_id,
	null as parcelle,
	null as zone_id,
	null as zone,
	ec.nom as culture, 
	ec.id as culture_id, 
	ec.code as culture_code,
	ecoc.complet_espece_edi_nettoye as especes,
	eisoc.precedent_nom as culture_precedente, 
	eisoc.precedent_id as culture_precedente_id, 
	eisoc.precedent_code as culture_precedente_code,
	eppps.id as phase_id,
	eppps."type" as phase,
	epps.pct_occupation_sol,
	ens.rang as rang,
	eisoc.interventions_actions as action,
	ei.nom_utilisateur as intrant_nom,
	eis.nom as intervention,
	eis.id as intervention_id,
	cast(eis.date_debut as text) as debut_intervention,
	cast(eis.date_fin as text) as fin_intervention,
	eisoc.interventions_cibles_trait as cibles_traitement
from entrepot_utilisation_intrant_performance euip 
join entrepot_utilisation_intrant_synthetise euis on euis.id = euip.utilisation_intrant_id 
join entrepot_utilisation_intrant_synthetise_agrege euisa on euis.id = euisa.id
join entrepot_intervention_synthetise_outils_can eisoc on euisa.intervention_synthetise_id = eisoc.id
join entrepot_intervention_synthetise_agrege_extanded eismae on eismae.id = euisa.intervention_synthetise_id 
join entrepot_intervention_synthetise eis on eis.id = euisa.intervention_synthetise_id 
join entrepot_synthetise es on euisa.synthetise_id = es.id
join entrepot_context_performance_sdc sdc_context on euisa.sdc_id = sdc_context.sdc_id
join entrepot_culture ec on ec.id = eismae.culture_id
join entrepot_culture_outils_can ecoc on ecoc.id = ec.id
left join entrepot_intrant ei on euis.intrant_id = ei.id
left join entrepot_noeuds_synthetise ens on ens.id = eismae.cible_noeuds_synthetise_id
left join entrepot_plantation_perenne_phases_synthetise eppps on eppps.id = CAST(eismae.plantation_perenne_phases_synthetise_id AS VARCHAR)
left join entrepot_plantation_perenne_synthetise epps on CAST(eismae.plantation_perenne_synthetise_id AS VARCHAR) = epps.id
UNION
-- REALISE 
select 
	euip.*,
	sdc_context.domaine_nom as nom_domaine_exploitation,
	sdc_context.domaine_id as id_domaine, 
	sdc_context.domaine_campagne,
	sdc_context.domaine_type,
	sdc_context.domaine_departement as departement, 
	sdc_context.nom_reseau_it,
	sdc_context.nom_reseau_ir,
	sdc_context.dispositif_id,
	sdc_context.dispositif_type,
	sdc_context.sdc_id,
	sdc_context.sdc_filiere, 
	sdc_context.sdc_nom,
	sdc_context.sdc_num_dephy,
	sdc_context.sdc_type_conduite, 
	sdc_context.sdc_valide, 
	sdc_context.sdc_modalite_suivi_dephy, 
	null as nom_systeme_synthetise,
	null as id_systeme_synthetise,
	null as synthetise_valide,
	null as synthetise_campagnes,
	ep.id as parcelle_id,
	ep.nom as parcelle,
	ez.id as zone_id,
	ez.nom as zone,
	ec.nom as culture, 
	ec.id as culture_id, 
	ec.code as culture_code,
	ecoc.complet_espece_edi_nettoye as especes,
	eiroc.precedent_nom as culture_precedente, 
	eiroc.precedent_id as culture_precedente_id, 
	null as culture_precedente_code,
	epppr.id as phase_id,
	epppr."type" as phase,
	null as pct_occupation_sol,
	enr.rang as rang,
	eiroc.interventions_actions as action,
	ei.nom_utilisateur as intrant_nom,
	eir.nom as intervention,
	eir.id as intervention_id,
	cast(eir.date_debut as text) as debut_intervention,
	cast(eir.date_fin as text) as fin_intervention,
	eiroc.interventions_cibles_trait as cibles_traitement
from entrepot_utilisation_intrant_performance euip 
join entrepot_utilisation_intrant_realise euir on euir.id = euip.utilisation_intrant_id 
join entrepot_utilisation_intrant_realise_agrege euira on euir.id = euira.id
join entrepot_intervention_realise_outils_can eiroc on euira.intervention_realise_id = eiroc.id
join entrepot_intervention_realise eir on eir.id = euira.intervention_realise_id 
join entrepot_context_performance_sdc sdc_context on euira.sdc_id = sdc_context.sdc_id
join entrepot_culture ec on ec.id = euira.culture_id
join entrepot_culture_outils_can ecoc on ecoc.id = ec.id
left join entrepot_parcelle ep on euira.parcelle_id = ep.id
left join entrepot_zone ez on euira.zone_id = ez.id
left join entrepot_intrant ei on euir.intrant_id = ei.id
left join entrepot_noeuds_realise enr on enr.id = euira.noeuds_realise_id
left join entrepot_plantation_perenne_phases_realise epppr on epppr.id = CAST(euira.plantation_perenne_phases_realise_id AS VARCHAR)
left join entrepot_plantation_perenne_realise eppr on CAST(euira.plantation_perenne_realise_id AS VARCHAR) = eppr.id;