
import configparser
import pandas as pd

#Fetch the sql files 
path_sql_files = 'scripts/'

#Obtenir les paramètres de connexion pour psycopg2
config = configparser.ConfigParser()
config.read(r'../../../../00_config/config.ini')

DATA_PATH = config.get('entrepot_local', 'data_path') 

# Charger les DataFrames éponymes
eprp = pd.read_csv(DATA_PATH+'parcelle_realise_performance.csv')
eproc = pd.read_csv(DATA_PATH+'parcelle_realise_outils_can.csv')
ep = pd.read_csv(DATA_PATH+'parcelle.csv')
ecps = pd.read_csv(DATA_PATH+'context_performance_sdc.csv')

# Jointures sur les colonnes appropriées
df = eprp.merge(eproc, left_on='parcelle_id', right_on='id', suffixes=('', '_eproc')) \
         .merge(ep, left_on='parcelle_id', right_on='id', suffixes=('', '_ep')) \
         .merge(ecps, left_on='sdc_id', right_on='sdc_id', suffixes=('', '_ecps'))

# Sélection des colonnes nécessaires
df_selection = df[[
    'parcelle_id',
    'approche_de_calcul',
    'ift_histo_chimique_tot',
    'ift_histo_chim_tot_hts',
    'ift_histo_h',
    'ift_histo_f',
    'ift_histo_i',
    'ift_histo_ts',
    'ift_histo_a',
    'ift_histo_hh',
    'ift_histo_biocontrole',
    'ift_histo_tx_comp',
    'ift_cible_non_mil_chimique_tot',
    'ift_cible_non_mil_chim_tot_hts',
    'ift_cible_non_mil_h',
    'ift_cible_non_mil_f',
    'ift_cible_non_mil_i',
    'ift_cible_non_mil_ts',
    'ift_cible_non_mil_a',
    'ift_cible_non_mil_hh',
    'ift_cible_non_mil_biocontrole',
    'ift_cible_non_mil_tx_comp',
    'ift_cible_mil_chimique_tot',
    'ift_cible_mil_chim_tot_hts',
    'ift_cible_mil_h',
    'ift_cible_mil_f',
    'ift_cible_mil_i',
    'ift_cible_mil_ts',
    'ift_cible_mil_a',
    'ift_cible_mil_hh',
    'ift_cible_mil_biocontrole',
    'ift_cible_mil_tx_comp',
    'ift_culture_non_mil_chimique_tot',
    'ift_culture_non_mil_chim_tot_hts',
    'ift_culture_non_mil_h',
    'ift_culture_non_mil_f',
    'ift_culture_non_mil_i',
    'ift_culture_non_mil_ts',
    'ift_culture_non_mil_a',
    'ift_culture_non_mil_hh',
    'ift_culture_non_mil_biocontrole',
    'ift_culture_non_mil_tx_comp',
    'ift_culture_mil_chimique_tot',
    'ift_culture_mil_chim_tot_hts',
    'ift_culture_mil_h',
    'ift_culture_mil_f',
    'ift_culture_mil_i',
    'ift_culture_mil_ts',
    'ift_culture_mil_a',
    'ift_culture_mil_hh',
    'ift_culture_mil_biocontrole',
    'ift_culture_mil_tx_comp',
    'recours_aux_moyens_biologiques',
    'recours_macroorganismes',
    'recours_produits_biotiques_sansamm',
    'recours_produits_abiotiques_sansamm',
    'tps_utilisation_materiel_janvier',
    'tps_utilisation_materiel_fevrier',
    'tps_utilisation_materiel_mars',
    'tps_utilisation_materiel_avril',
    'tps_utilisation_materiel_mai',
    'tps_utilisation_materiel_juin',
    'tps_utilisation_materiel_juillet',
    'tps_utilisation_materiel_aout',
    'tps_utilisation_materiel_sept',
    'tps_utilisation_materiel_oct',
    'tps_utilisation_materiel_nov',
    'tps_utilisation_materiel_dec',
    'tps_utilisation_materiel',
    'tps_utilisation_materiel_tx_comp',
    'tps_travail_manuel_janvier',
    'tps_travail_manuel_fevrier',
    'tps_travail_manuel_mars',
    'tps_travail_manuel_avril',
    'tps_travail_manuel_mai',
    'tps_travail_manuel_juin',
    'tps_travail_manuel_juillet',
    'tps_travail_manuel_aout',
    'tps_travail_manuel_septembre',
    'tps_travail_manuel_octobre',
    'tps_travail_manuel_novembre',
    'tps_travail_manuel_decembre',
    'tps_travail_manuel',
    'tps_travail_manuel_tx_comp',
    'tps_travail_mecanise_janvier',
    'tps_travail_mecanise_fevrier',
    'tps_travail_mecanise_mars',
    'tps_travail_mecanise_avril',
    'tps_travail_mecanise_mai',
    'tps_travail_mecanise_juin',
    'tps_travail_mecanise_juillet',
    'tps_travail_mecanise_aout',
    'tps_travail_mecanise_septembre',
    'tps_travail_mecanise_octobre',
    'tps_travail_mecanise_novembre',
    'tps_travail_mecanise_decembre',
    'tps_travail_mecanise',
    'tps_travail_mecanise_tx_comp',
    'tps_travail_total_janvier',
    'tps_travail_total_fevrier',
    'tps_travail_total_mars',
    'tps_travail_total_avril',
    'tps_travail_total_mai',
    'tps_travail_total_juin',
    'tps_travail_total_juillet',
    'tps_travail_total_aout',
    'tps_travail_total_septembre',
    'tps_travail_total_octobre',
    'tps_travail_total_novembre',
    'tps_travail_total_decembre',
    'tps_travail_total',
    'tps_travail_total_tx_comp',
    'nbre_de_passages_janvier',
    'nbre_de_passages_fevrier',
    'nbre_de_passages_mars',
    'nbre_de_passages_avril',
    'nbre_de_passages_mai',
    'nbre_de_passages_juin',
    'nbre_de_passages_juillet',
    'nbre_de_passages_aout',
    'nbre_de_passages_septembre',
    'nbre_de_passages_octobre',
    'nbre_de_passages_novembre',
    'nbre_de_passages_decembre',
    'nbre_de_passages',
    'nbre_de_passages_tx_comp',
    'nbre_de_passages_labour',
    'nbre_de_passages_labour_tx_comp',
    'nbre_de_passages_tcs',
    'nbre_de_passages_tcs_tx_comp',
    'nbre_de_passages_desherbage_meca',
    'nbre_de_passages_desherbage_meca_tx_comp',
    'utili_desherbage_meca',
    'utili_desherbage_meca_tx_comp',
    'type_de_travail_du_sol',
    'type_de_travail_du_sol_tx_comp',
    'co_tot_reelles',
    'co_tot_reelles_tx_comp',
    'co_tot_std_mil',
    'co_tot_std_mil_tx_comp',
    'co_semis_reel',
    'co_semis_std_mil',
    'co_fertimin_reel',
    'co_fertimin_std_mil',
    'co_epandage_orga_reelles',
    'co_epandage_orga_std_mil',
    'co_phyto_sans_amm_reelles',
    'co_phyto_sans_amm_std_mil',
    'co_phyto_avec_amm_reelles',
    'co_phyto_avec_amm_std_mil',
    'co_trait_semence_reelles',
    'co_trait_semence_std_mil',
    'co_irrigation_reelles',
    'co_irrigation_std_mil',
    'co_substrats_reelles',
    'co_substrats_std_mil',
    'co_pots_reelles',
    'co_pots_std_mil',
    'co_intrants_autres_reelles',
    'co_intrants_autres_std_mil',
    'co_decomposees_reel_tx_comp',
    'co_decomposees_std_mil_tx_comp',
    'cm_reelles',
    'cm_reelles_tx_comp',
    'cm_std_mil',
    'cm_std_mil_tx_comp',
    'c_main_oeuvre_tot_reelle',
    'c_main_oeuvre_tot_reelle_tx_comp',
    'c_main_oeuvre_tot_std_mil',
    'c_main_oeuvre_tot_std_mil_tx_comp',
    'c_main_oeuvre_tractoriste_reelles',
    'c_main_oeuvre_tractoriste_std_mil',
    'c_main_oeuvre_ouvrier_reelles',
    'c_main_oeuvre_ouvrier_std_mil',
    'c_main_oeuvre_saisonnier_reelles',
    'c_main_oeuvre_saisonnier_std_mil',
    'co_intrants_tx_comp',
    'co_tot_reelles_tx_comp',
    'cm_reelles_tx_comp',
    'c_main_oeuvre_tot_reelle_tx_comp'
]]

# Afficher ou sauvegarder le DataFrame final
df_selection.to_csv('resultat_selection.csv', index=False)
print(df_selection.head())