select
 	"id"::text,
	code_dephy::text as "dephynb",
	"realized"::text,
    true as "validation",
	"sdc_id"::text,
	synthetise_id::text as "systeme_synthetise_id",
	-- entite_id,
	-- dispositif_id,
	-- domaine_id,
	-- commune_id,
    "reseaux_ir"::text,
	"reseaux_it"::text,
	"latitude"::numeric,
	"longitude"::numeric,
	codeinsee::text as "codeinsee",
	"arrondissement"::text,
	---------
	'DEPHY Ferme' as "c100_networksource",
	filiere::text as "c101_sector",
	pz0::text as "c102_pz0",
	"c103_networkyears"::text,
	new_campagne::integer as "c104_campaign_dis",
	region::text as "c105_administrativeregion",
	ancienne_region::text as "c106_regionpre2015",
	departement::text as "c107_departement",
	bassin_viticole::text as "c108_winebasin",
    'France' as "c109_country",
	---------
	type_agriculture::text as "c110_managementtype",
	"c111_species"::text,
	"c112_variety"::text,
	"c113_grapevar"::text,
	---------
	-- type_production,
	"c120_arboriculture_typo_sdc"::text,
	"c121_maraichage_typo_sdc"::text,
	"c122_horticulture_typo_sdc"::text,
	"c123_cult_tropicales_typo_sdc"::text,
	"c124_gcpe_typo_sdc"::text,
	---------
	-- surface_par_unite_de_travail_humain,
	-- nombre_uth_necessaires,
	type_de_travail_du_sol::text as "c201_groundworktype",
	utili_desherbage_meca::text as "c203_mechanicalweeding",
	nbre_de_passages_desherbage_meca::double precision as "c204_mechanicalweedinginterventionfrequency",
	---------
	tps_travail_total as "c301_workingtime",
	tps_utilisation_materiel as "c302_mechanizationtime",
	tps_travail_manuel as "c303_labourtime",
	conso_carburant as "c304_fuelconsumption",
	---------
	ferti_n_tot as "c401_fertilizationunityn",
	ferti_n_mineral as "c402_fertilizationmineralunityn",
	ferti_n_organique as "c403_fertilizationorganicunityn",
	ferti_p2o5_tot as "c404_fertilizationunityp",
	ferti_p2o5_mineral as "c405_fertilizationmineralunityp",
	ferti_p2o5_organique as "c406_fertilizationorganicunityp",
	ferti_k2o_tot as "c407_fertilizationunityk",
	ferti_k2o_mineral as "c408_fertilizationmineralunityk",
	ferti_k2o_organique as "c409_fertilizationorganicunityk",
	---------
	pb_std_mil_avec_autoconso as "c501_grossproceeds",
	mb_std_mil_avec_autoconso as "c502_grossprofit",
	msn_reelle_avec_autoconso as "c503_seminetmargin",
	"c504_outlabourtotalexpenses",
	co_tot_std_mil as "c505_operatingexpenses",
	-- c_main_oeuvre_tractoriste_std_mil,
	-- c_main_oeuvre_manuelle_std_mil,
	c_main_oeuvre_tot_std_mil as "c506_labourexpenses",
	cm_std_mil as "c507_mechanizationexpenses",
	md_std_mil_avec_autoconso as "c508_directmargin",                     -- invisible
	---------
	-- ift_cible_non_mil_chimique_tot,
	ift_cible_non_mil_chim_tot_hts as "c601_totalift",
	-- ift_cible_non_mil_hh,
	"c602_ift_hh_hts",
    ift_cible_non_mil_biocontrole as "c603_biocontrolift",
	ift_cible_non_mil_h as "c605_herbicideift",
	ift_cible_non_mil_i as "c607_insecticideift",
	ift_cible_non_mil_f as "c608_fungicideift",
	-- ift_cible_non_mil_ts,
	ift_cible_non_mil_a as "c609_otherift",
	recours_aux_moyens_biologiques as "c610_biologicalwayssolution",
	---------
	hri1_hts as "c633_hri1tothts",
	hri1_g1_hts as "c634_hri1g1hts",
	hri1_g2_hts as "c635_hri1g2hts",
	hri1_g3_hts as "c636_hri1g3hts",
	hri1_g4_hts as "c637_hri1g4hts",
	---------
	qsa_tot_hts as "c640_qtesubstactive",                                 -- invisible
	qsa_cmr_hts as "c641_qtesubstcmr",                                    -- invisible
	qsa_toxique_utilisateur_hts as "c642_qtesubsttoxique",                -- invisible
	qsa_glyphosate_hts as "c643_qtesubstglyphosate",                      -- invisible
	qsa_danger_environnement_hts as "c644_qtesubstdangerenvironnement",   -- invisible
	qsa_cuivre_tot_hts as "c645_qtesubstcuivre",                          -- invisible
	qsa_soufre_tot_hts as "c646_qtesubstsoufre",                          -- invisible
	---------
	-- "c701_totalift_evol_diff",
	-- "c702_ift_hh_hts_evol_diff",
	-- "c703_biocontrolift_evol_diff",
	-- "c705_herbicideift_evol_diff",
	-- "c707_insecticideift_evol_diff",
	-- "c708_fungicideift_evol_diff",
	-- "c709_otherift_evol_diff",
	-- "c710_biologicalwayssolution_evol_diff",
	---------
	"c701_totalift_evol_ratio",
	"c702_ift_hh_hts_evol_ratio",
	"c703_biocontrolift_evol_ratio",
	"c705_herbicideift_evol_ratio",
	"c707_insecticideift_evol_ratio",
	"c708_fungicideift_evol_ratio",
	"c709_otherift_evol_ratio",
	"c710_biologicalwayssolution_evol_ratio",
	-- c640_stdtotalift
	------- pour ipm
    'DEPHY Ferme' as "c1001_networksource",
    null::double precision as "c9303_labourtime",
    null::double precision as "c9502_grossprofit",
    null::double precision as "c9503_seminetmargin",
    null::double precision as "c9506_labourexpenses",
    null::double precision as "c9633_hri1tothts_ipm",
    null::double precision as "c9634_hri1g1hts_ipm" ,
    null::double precision as "c9635_hri1g2hts_ipm",
    null::double precision as "c9636_hri1g3hts_ipm",
    null::double precision as "c9637_hri1g4hts_ipm"
from entrepot_donnees_dephyferme_pour_dephygraph
where entrepot_donnees_dephyferme_pour_dephygraph.filiere != 'cultures tropicales'
union all
select
	cast(uuid_generate_v4() as text) as "id",
	"dephynb"::text,
	null::text as "realized",
	true as "validation",
	"sdc_id"::text,
	"systeme_synthetise_id"::text,
	null::text as "reseaux_ir",
	null::text as "reseaux_it",
	"latitude"::numeric,
	"longitude"::numeric,
	null::text as "codeinsee",
	c107_departement::text as "arrondissement",
	--------
	'DEPHY Ferme' as "c100_networksource",
	"c101_sector"::text,
	"c102_pz0"::text,
	"c103_networkyears"::text,
	"c104_campaign_dis"::integer,
	"c105_administrativeregion"::text,
	"c106_regionpre2015"::text,
	"c107_departement"::text,
	null::text as "c108_winebasin",
	'France' as "c109_country",
	---------
	"c110_managementtype"::text,
	"c111_species"::text,
	"c112_variety"::text,
	null::text as "c113_grapevar",
	---------
	"c120_arboriculture_typo_sdc"::text,
	"c121_maraichage_typo_sdc"::text,
	"c122_horticulture_typo_sdc"::text,
	"c123_cult_tropicales_typo_sdc"::text,
	"c124_gcpe_typo_sdc"::text,
	---------
	"c201_groundworktype"::text,
	"c203_mechanicalweeding"::text,
	"c204_mechanicalweedinginterventionfrequency",
	---------
	"c301_workingtime",
	"c302_mechanizationtime",
	"c303_labourtime",
	"c304_fuelconsumption",
	---------
	"c401_fertilizationunityn",
	"c402_fertilizationmineralunityn",
	"c403_fertilizationorganicunityn",
	"c404_fertilizationunityp",
	"c405_fertilizationmineralunityp",
	"c406_fertilizationorganicunityp",
	"c407_fertilizationunityk",
	"c408_fertilizationmineralunityk",
	"c409_fertilizationorganicunityk",
	---------
	"c501_grossproceeds",
	"c502_grossprofit",
	"c503_seminetmargin",
	"c504_outlabourtotalexpenses",
	"c505_operatingexpenses",
	"c506_labourexpenses",
	"c507_mechanizationexpenses",
	null::double precision as "c508_directmargin",
	---------
	"c601_totalift",
	"c602_ift_hh_hts",
	"c603_biocontrolift",
	"c605_herbicideift",
	"c607_insecticideift",
	"c608_fungicideift",
	"c609_otherift",
	"c610_biologicalwayssolution",
	---------
	null::double precision as "c633_hri1tothts",
	null::double precision as "c634_hri1g1hts",
	null::double precision as "c635_hri1g2hts",
	null::double precision as "c636_hri1g3hts",
	null::double precision as "c637_hri1g4hts",
	---------
	null::double precision as "c640_qtesubstactive",
	null::double precision as "c641_qtesubstcmr",
	null::double precision as "c642_qtesubsttoxique",
	null::double precision as "c643_qtesubstglyphosate",
	null::double precision as "c644_qtesubstdangerenvironnement",
	null::double precision as "c645_qtesubstcuivre",
	null::double precision as "c646_qtesubstsoufre",
	---------
	"c701_totalift_evol_ratio",
	"c702_ift_hh_hts_evol_ratio",
	"c703_biocontrolift_evol_ratio",
	"c705_herbicideift_evol_ratio",
	"c707_insecticideift_evol_ratio",
	"c708_fungicideift_evol_ratio",
	"c709_otherift_evol_ratio",
	"c710_biologicalwayssolution_evol_ratio",
	------- pour ipm
	'DEPHY Ferme' as "c1001_networksource",
	null::double precision as "c9303_labourtime",
	null::double precision as "c9502_grossprofit",
	null::double precision as "c9503_seminetmargin",
	null::double precision as "c9506_labourexpenses",
	null::double precision as "c9633_hri1tothts_ipm",
	null::double precision as "c9634_hri1g1hts_ipm",
	null::double precision as "c9635_hri1g2hts_ipm",
	null::double precision as "c9636_hri1g3hts_ipm",
	null::double precision as "c9637_hri1g4hts_ipm"
from entrepot_donnees_culture_trop_pour_dephygraph
union all
select
	cast(uuid_generate_v4() as text) as "id", 
	"dephynb"::text,
	"realized"::text,
	true as "validation",
	"sdc_id"::text,
	"systeme_synthetise_id"::text,
	null::text as "reseaux_ir", 
	null::text as "reseaux_it",
	"latitude"::numeric,
	"longitude"::numeric,
	null::text as "codeinsee", 
	"arrondissement"::text,
	---------
	"c100_networksource"::text,
	"c101_sector"::text,
	"c102_pz0"::text,
	"c103_networkyears"::text,
	"c104_campaign_dis"::integer,
	"c105_administrativeregion"::text,
	"c106_regionpre2015"::text,
	"c107_departement"::text,
	"c108_winebasin"::text,
	"c109_country"::text,
	---------
	"c110_managementtype"::text,
	"c111_species"::text,
	"c112_variety"::text,
	"c113_grapevar"::text,
	---------
	"c120_arboriculture_typo_sdc"::text,
	"c121_maraichage_typo_sdc"::text,
	"c122_horticulture_typo_sdc"::text,
	"c123_cult_tropicales_typo_sdc"::text,
	"c124_gcpe_typo_sdc"::text,
	---------
	"c201_groundworktype"::text,
	"c203_mechanicalweeding"::text,
	"c204_mechanicalweedinginterventionfrequency",
	---------
	"c301_workingtime",
	"c302_mechanizationtime",
	"c303_labourtime",
	"c304_fuelconsumption",
	---------
	"c401_fertilizationunityn",
	"c402_fertilizationmineralunityn",
	"c403_fertilizationorganicunityn",
	"c404_fertilizationunityp",
	"c405_fertilizationmineralunityp",
	"c406_fertilizationorganicunityp",
	"c407_fertilizationunityk",
	"c408_fertilizationmineralunityk",
	"c409_fertilizationorganicunityk",
	---------
	"c501_grossproceeds",
	"c502_grossprofit",
	"c503_seminetmargin",
	"c504_outlabourtotalexpenses",
	"c505_operatingexpenses",
	"c506_labourexpenses",
	"c507_mechanizationexpenses",
	"c508_directmargin",
	---------
	"c601_totalift",
	"c602_ift_hh_hts",
	"c603_biocontrolift",
	"c605_herbicideift",
	"c607_insecticideift",
	"c608_fungicideift",
	"c609_otherift",
	"c610_biologicalwayssolution",
	---------
	"c633_hri1tothts",
	"c634_hri1g1hts",
	"c635_hri1g2hts",
	"c636_hri1g3hts",
	"c637_hri1g4hts",
	---------
	"c640_qtesubstactive",
	"c641_qtesubstcmr",
	"c642_qtesubsttoxique",
	"c643_qtesubstglyphosate",
	"c644_qtesubstdangerenvironnement",
	"c645_qtesubstcuivre",
	"c646_qtesubstsoufre",
	---------
	"c701_totalift_evol_ratio",
	"c702_ift_hh_hts_evol_ratio",
	"c703_biocontrolift_evol_ratio",
	"c705_herbicideift_evol_ratio",
	"c707_insecticideift_evol_ratio",
	"c708_fungicideift_evol_ratio",
	"c709_otherift_evol_ratio",
	"c710_biologicalwayssolution_evol_ratio",
	--------- pour ipm
	"c1001_networksource",
	"c9303_labourtime",
	"c9502_grossprofit",
	"c9503_seminetmargin",
	"c9506_labourexpenses",
	"c9633_hri1tothts_ipm",
	"c9634_hri1g1hts_ipm",
	"c9635_hri1g2hts_ipm",
	"c9636_hri1g3hts_ipm",
	"c9637_hri1g4hts_ipm"
from entrepot_donnees_ipmgraph_pour_dephygraph;