name: Tests

on:
  push:
    branches:
        - 'main'
    paths:
        - 03_magasins/can/unactivate
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y openconnect
    - name: Connect to VPN
      env:
        VPN_USERNAME: ${{ secrets.VPN_USERNAME }}
        VPN_PASSWORD: ${{ secrets.VPN_PASSWORD }}
      run: |
        echo "$VPN_PASSWORD" | sudo openconnect --protocol=gp acces.intranet.inra.fr -u $VPN_USERNAME --csd-wrapper=/usr/libexec/openconnect/hipreport.sh --passwd-on-stdin --background --authgroup=gateway_pad-dc-idf     
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: copy file via ssh password
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST_TEST }}
        username: ${{ secrets.USERNAME_TEST }}
        password: ${{ secrets.PASSWORD_TEST }}
        port: ${{ secrets.PORT }}
        overwrite: true
        source: "03_magasins/"
        target: "/home/${{ secrets.USERNAME_TEST }}"
    - name: Add new magasins scripts in test
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST_TEST }}
        username: ${{ secrets.USERNAME_TEST }}
        password: ${{ secrets.PASSWORD_TEST }}
        port: ${{ secrets.PORT }}
        script: docker cp /home/${{ secrets.USERNAME_TEST }}/03_magasins/* datagrosyst-tests-datagrosyst-1:/app/magasins/
    - name: copy file via ssh password
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST_PROD }}
        username: ${{ secrets.USERNAME_PROD }}
        password: ${{ secrets.PASSWORD_PROD }}
        port: ${{ secrets.PORT }}
        overwrite: true
        source: "03_magasins/"
        target: "/home/${{ secrets.USERNAME_TEST }}"
    - name: Add new magasins scripts in prod
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST_PROD }}
        username: ${{ secrets.USERNAME_PROD }}
        password: ${{ secrets.PASSWORD_PROD }}
        port: ${{ secrets.PORT }}
        script: docker cp /home/${{ secrets.USERNAME_PROD }}/03_magasins/* datagrosyst-prod-datagrosyst-1:/app/magasins/
